Вторая часть рефакторинга парсера
andrey-terekhov/RuC pull request #104
Opened 2021-03-22 12:06 UTC by bugdea1er

В этом запросе проведен рефакторинг `parser_expr.c` и использован новый интерфейс дерева
- Переход на новый интерфейс дерева
- Переход на чтение исходного файла одним токеном: упрощает интерфейс парсера выражений, в будущем позволит проще указывать на ошибки
- Взаимодействие с анонимным стеком вынесено в отдельные функции: после рефакторинга стандартных функций стек можно будет вынести в отдельную структуру, а массив заменить на вектор
- Небольшое улучшение читаемости кода парсера выражений

**Стандартные функции не были затронуты**, кроме небольших переименований. Для них предлагалось изменить парсинг, чтобы сократить количество кода (а для хорошего восстановления придется дублировать еще больше строк), я это предложение поддерживаю. К разбору функций относятся: функция `parse_standard_function` и все функции с префиксом `mustbe`.

Про именование: функции внешнего интерфейса разбора выражений, которые были вынесены в прошлых запросах, кроме самого разбора выполняют дополнительные действия, например, вставку пометок для копирования структур. Тем не менее, хотелось бы оставить им такие простые названия для чистоты кода, который вызывает разбор выражений, поэтому наименование внутренних функций не соответствует грамматике. Естественно, этот вопрос открыт к обсуждению.

2021-03-27 20:36 UTC, Victor-Y-Fadeev requested changes
В общем, по `parser_expr.c` слишком много одинаковых замечаний, поэтому буду смотреть когда исправите массово:
- Прямой доступ к дереву строго запрещен!
- Имена функций не соответствуют [стайлгайду](https://github.com/andrey-terekhov/RuC/wiki/%D0%A1%D1%82%D0%B0%D0%B9%D0%BB%D0%B3%D0%B0%D0%B9%D0%B4)
- Проблемы со "стеками", они ими как минимум не являются
- Не хватает логических отступов
- Лишние комментарии `// 1`

Также создайте (иначе не будет работать обратная совместимость):
```c
/**
 *	Create tree reference for backward compatibility
 *
 *	@param	prs			Parser structure
 *
 *	@return	Tree reference
 */
item_t tree_reference(parser *const prs)
{
	return (item_t)vector_size(&prs->sx->tree);
}
```

И кстати, почему не везде возможно передавать родителя параметром? Для чего `to_tree`?

2021-03-27 20:36 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
- Что значит `// 1`?
- Добавьте отступ после `if`
- Зачем лишние скобки во втором `if`?
- Принудительное изменение `prs->sopnd`, это уже точно не стек...

2021-03-27 20:36 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
>  void mustbepointstring(parser *const prs)
Исправьте название, как минимум нет разделителей...

2021-03-27 20:36 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +				double_to_tree(&nd_init_list, nd_init_list.argc, sign * (double)prs->lxr->num);
А еще лучше, просто смените **локальный** интерфейс добавления `double` на:
```c
node_add_double(node *const nd, const double value);
node_set_double(node *const nd, const size_t index, const double value);
node_get_double(node *const nd, const size_t index);
```

2021-03-27 20:36 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		  mode_is_string(prs->sx, mode_get(prs->sx, (size_t)prs->ansttype + 1))))
Запишите через ИЛИ, сложно читать.

2021-03-27 20:36 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
>  	prs->sopnd--;
Уже писал. И ко всей функции те же вопросы, что и к предыдущей.

2021-04-01 13:36 UTC, bugdea1er commented on libs/compiler/parser.h
> +token_t token_peek(parser *const prs);
Для единообразия. Все функции работы с токенами принимают аргументом парсер. Стоит убрать?

2021-04-01 13:50 UTC, bugdea1er commented on libs/compiler/parser_stmt.c
> +	switch (prs->token)
Точно, здесь смотрим на первый токен, если идентификатор - второй (он же peek token)

2021-04-01 13:50 UTC, bugdea1er commented on libs/compiler/parser_stmt.c
> -	else
Да, вообще так и было сначала, я зря это сюда добавил в прошлом слиянии

2021-04-01 13:51 UTC, bugdea1er commented on libs/compiler/parser_expr.c
> +				node_set_arg(&prs->nd, 0, prs->anstdispl);
Раньше стирали конец дерева и вместо него писали, теперь просто меняем тип тех же узлов - результат один

2021-04-01 13:58 UTC, bugdea1er commented on libs/compiler/parser.h
> +
Теперь используется как тип для поля anst
Это нужно, чтобы знать, какой операнд попал на стек: число, переменная, ссылка или уже подготовленное значение, от этого зависит дальнейшая работа с ним

2021-04-01 14:11 UTC, bugdea1er commented
- Анонимный стек вынесен допилен, он остался только в разборе стандартных функций и в строке 1514 файла parser_expr.c. Полностью обращение к нему уйдет после рефакторинга стандартных функций: функции parse_standard_function просто не будет, а поле parser.leftansttype уйдет после переделки аргументов-списков инициализации: тип будет передаваться не сверху вниз, а снизу вверх.
- Интерфейс дерева исправлен, но осталось прямое обращение к дереву в логических операторах && и ||: они требуют индекса дерева, если это заменить на ноды (что сделать можно), потеряется совместимость с MIPS
- Нода присваивается, а не копируется, с расчетом на работу с полноценным деревом. На данный момент нода не является ссылочным типом, но будет, и в данных случаях мне нужно скопировать ссылку, а не дублировать ноду.

Надеюсь, что больше ничего не забыл

2021-04-08 00:38 UTC, Victor-Y-Fadeev requested changes
По поводу сокращений `op`, откажитесь от них, у вас уже 3 значения для них:
- `operand`
- `operator`
- `operation`

Интерфейс дерева будет обновлен, когда смердите откатите свои модификации. Для отказа от прямой записи в дерево и функции `tree_reference` будут добавлены следующие функции:
```c
size_t node_store(node *const nd);
node node_restore(vector *const tree, const size_t index);

// OR

size_t node_save(node *const nd);
node node_load(vector *const tree, const size_t index);
```

Используйте `node_copy`, когда вы напрямую присваиваете ноды - это все равно что прямой доступ к полям! Даже если они потом станут указателями, при таком присвоении вы потеряете ссылку на область памяти и не сможете ее очистить -> получите сегментацию. `node_copy` безопаснее, а по скорости почти не отличается (будет копировать 2 числа, вместо одного).

**P.s. Если же хотите работать со ссылками, то и `prs->nd` сделайте типа `node *`. Также полностью откажитесь от разыменований.**

2021-04-08 00:38 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		const operand_type righttanst = anst_peek(prs);
Надо бы переименовать...

2021-04-08 00:38 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +					: righttanst == variable ? COPY10 : COPY11;
Распишите, например вот так:
```c
operator = leftanst == variable
	? righttanst == variable
		? COPY00 : COPY01
	: righttanst == variable
		? COPY10 : COPY11;
```

2021-04-08 00:38 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		// Эта функция учитывает тот факт, что начало в виде унарного выражения уже выкушано
- "**на** тот факт"
- "начало, в виде унарного выражения," - запятые

2021-04-08 00:38 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +	for (size_t i = 0; i < (size_t)prs->lxr->num; i++)
В данном случае лучше создать `int` переменную, чем использовать приведение.

2021-04-08 00:38 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +	prs->nd = *parent;
Если хотите таким образом работать с нодами (без `node_copy`), сделайте `prs->nd` типа `node *`, а не `node`.

2021-04-08 00:38 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +	prs->nd = *parent;
- Либо `node_copy`
- Либо `prs->nd` типа `node *`

2021-04-08 00:38 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +	prs->nd = *parent;
- Либо `node_copy`
- Либо `prs->nd` типа `node *`

2021-04-08 00:38 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +	prs->nd = *parent;
- Либо `node_copy`
- Либо `prs->nd` типа `node *`

2021-04-08 00:38 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +	prs->nd = *parent;
- Либо `node_copy`
- Либо `prs->nd` типа `node *`

2021-04-08 00:38 UTC, Victor-Y-Fadeev commented on libs/compiler/tokens.h
> +	identifier			= 109,		/**< Identifier [C99 6.4.2] */
Конкретные числа - нехорошо. Почему удалили константу?

2021-04-08 00:38 UTC, Victor-Y-Fadeev commented on libs/compiler/defs.h
> -#define IDENT		109
Куда значения дели? Совместимость отвалится.

2021-04-08 00:38 UTC, Victor-Y-Fadeev commented on libs/compiler/defs.h
> -#define ADDR 111
Не будет совместимости.

2021-04-08 00:38 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +	prs->nd = *parent;
- Либо `node_copy`
- Либо `prs->nd` типа `node *`

2021-04-08 07:48 UTC, bugdea1er commented on libs/compiler/tokens.h
> +	identifier			= 109,		/**< Identifier [C99 6.4.2] */
Раньше это было до обратной совместимости, теперь эти def'ы ушли, надо присваивать конкретные числа. Без чисел не обойтись, потому что у некоторых должны быть отрицательные коды, у некоторых - степени двойки

2021-04-08 07:49 UTC, bugdea1er commented on libs/compiler/defs.h
> -#define IDENT		109
Эти константы больше нигде не используются, они были только для анонимного стека и токенов, в MIPS они тоже не нужны

2021-04-08 07:50 UTC, bugdea1er commented on libs/compiler/defs.h
> -#define ADDR 111
Ответил выше

2021-04-08 08:05 UTC, bugdea1er commented on libs/compiler/parser_expr.c
> +void totree_float_operation(parser *const prs, const item_t type, const item_t op)
Зачем? Эта функция записывает оператор в дерево, в названии нужно как-то упомянуть это

2021-04-08 12:16 UTC, bugdea1er commented on libs/compiler/parser_expr.c
> +uint8_t operator_precedence(const token_t operator)
Вроде для операторов чаще используется precedence
https://en.wikipedia.org/wiki/Operator_(computer_programming)#Operator_features_in_programming_languages

2021-04-08 12:26 UTC, bugdea1er commented on libs/compiler/parser_expr.c
> +		// Эта функция учитывает тот факт, что начало в виде унарного выражения уже выкушано
"Тот факт" убрал вообще, запятая уж тут точно не нужна, это ж не причастный оборот

2021-04-14 18:45 UTC, Victor-Y-Fadeev requested changes
- Стеки все еще стоит доделать, так как тип операнда - это не значение с верхушки стека, а просто последний добавленный!
- Зачем начали удалять константы? Это вполне себе тянет на отдельную задачу и не такую простую как кажется. Этим будем заниматься при следующем слиянии, а сейчас откатить.
- От `tree_reference` надо избавится, благо теперь есть замена в виде `node_save`. Я написал как это сделать, на забудьте удалить `tree_reference`. И не меняйте внутреннее состояние индекса.
- Удалите `#define TREE` я уже 3 или 4 раз об этом прошу.

2021-04-14 18:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +				int is_global = prs->operand_displ < 0 ? -1 : 1;
```c
const item_t sign = prs->operand_displ < 0 ? -1 : 1;
```

2021-04-14 18:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		int operator = prs->token == plusplus ? POSTINC : POSTDEC;
`item_t` или `token_t`.

2021-04-14 18:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		prs->operators[prs->operators_size++] = operator;
Это все  уйдет...

2021-04-14 18:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +				const item_t old_addr_if = addr_if;
Отступ.

2021-04-14 18:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +			const item_t old_addr_if = addr_if;
Отступ.

2021-04-14 18:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +			node_addr = node_get_child(&node_addr, 0);
Отступ.

2021-04-14 18:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		while (addr_if != TExprend)
А вечный цикл в ошибочных тестах сам вылечился? Добавьте:
```c
while (addr_if != TExprend && addr_if != ITEM_MAX)
```

2021-04-14 18:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +	operand_t type = anst_peek(prs);
`const`.

2021-04-14 18:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +	node_add_arg(&nd, 0); // for max_displ
Нужно избавляться от `tree_reference`:
```c
node nd = node_add_child(parent, TFuncdef);
node_add_arg(&nd, (item_t)function_id);
node_add_arg(&nd, 0); // for max_displ

func_set(prs->sx, function_number, node_save(&nd)); // Ссылка на расположение в дереве
```

2021-04-14 18:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_stmt.c
> +		parse_statement(prs, &nd);
Давайте попробуем полностью избавится от `tree_reference`:
```c
parse_statement(prs, &nd);

node child = node_get_child(&nd, 0);
node_set_arg(&nd, 0, node_save(&child));
```

P.s. Если не выйдет с ходу, то оставьте.

2021-04-14 18:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_stmt.c
> +	node_set_arg(&nd, 3, tree_reference(prs)); // ref_statement
Просто удалить.

2021-04-14 18:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_stmt.c
> +	node_add_arg(&nd, 0); // ref_statement
Сюда пихнуть `1`, как вы и хотели.

2021-04-14 18:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_stmt.c
>  	prs->flag_in_loop = old_in_loop;
Все предыдущие установки `tree_reference` заменить на `1`, а сюда дописать:
```c
// Just for backward compatibility
node child = node_get_child(&nd, 0);
node_set_arg(&nd, 0, node_save(&child));	// ref_inition
child = node_get_child(&nd, 1);
node_set_arg(&nd, 1, node_save(&child));	// ref_condition
child = node_get_child(&nd, 2);
node_set_arg(&nd, 2, node_save(&child));	// ref_increment
child = node_get_child(&nd, 3);
node_set_arg(&nd, 3, node_save(&child));	// ref_statement
```

2021-04-14 19:06 UTC, bugdea1er commented on libs/compiler/parser_expr.c
> +	token_t func = prs->token;
Не пойдет, если это abs(), то в случае целого аргумента нужно заменить значение

2021-04-14 19:15 UTC, bugdea1er commented on libs/compiler/parser_expr.c
> +				int is_global = prs->operand_displ < 0 ? -1 : 1;
Как-то многовато для знака. Плюс еще в лексере такая же переменная типа int

2021-04-14 19:16 UTC, bugdea1er commented on libs/compiler/parser_expr.c
> +		while (addr_if != TExprend)
Выше есть проверка was_error

2021-04-14 20:39 UTC, Victor-Y-Fadeev commented
```c
/**
 *	Create tree reference of last child for backward compatibility
 *
 *	@param	nd			Parent node
 *
 *	@return	Tree reference
 */
item_t tree_reference(node *const nd)
{
	node child = node_get_child(nd, node_get_amount(nd) - 1);
	return (item_t)node_save(&child);
}
```

2021-04-14 20:41 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +				int is_global = prs->operand_displ < 0 ? -1 : 1;
`item_t` может быть и меньше `int`, это нужно чтобы приведение типов не вызывалось.

2021-04-14 20:51 UTC, bugdea1er commented on libs/compiler/defs.h
> +	mode_void_pointer = 15,
Раньше тип void* указывал куда-то за пределы modetab, и это никто не проверял. Кажется, момент с void* и тем, где он может появляться, надо уточнять

2021-04-14 21:45 UTC, Victor-Y-Fadeev requested changes
Осталось чуть чуть, пока исправляете я сравню выходные деревья.

2021-04-14 21:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.h
- Запятую после `FUNCBODY`
- 2 отступа между группами структур и перечислений

2021-04-14 21:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.c
> + */
Достаточно было добавить документацию только в header, удалить.

2021-04-14 21:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +} operator;
Блок структур определяется до деклараций, и отделяется 2 отступами.

2021-04-14 21:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
2 отступа после деклараций.

2021-04-14 21:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
>  }
Вот только раньше он у вас возвращал `type` и вы продолжаете этим пользоваться, так что скорее так:
```c
operand_t operands_push(parser *const prs, const operand_t type, const item_t mode)
{
	stack_push(&prs->anonymous, mode);
	prs->last_type = type;
	return type;
}
```

2021-04-14 21:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +
Один отступ.

2021-04-14 21:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		node_add_arg(&prs->nd, 0);
Не исправлено, туда мусор пишется из-за инкрементации!

2021-04-14 21:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +				while (operators_size(prs) > old_operators_size)
Когда меньшее слева читать удобнее:
```c
while (old_operators_size < operators_size(prs))
```

2021-04-14 21:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		while (operators_size(prs) > old_operators_size && operators_peek(prs).priority >= priority)
Опять про меньшее слева:
```c
while (old_operators_size < operators_size(prs) && priority <= operators_peek(prs).priority)
```

2021-04-14 21:45 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +	while (operators_size(prs) > old_operators_size)
```c
while (old_operators_size < operators_size(prs))
```

2021-04-14 22:01 UTC, bugdea1er commented on libs/compiler/parser_expr.c
>  }
Убрал использование возвращаемого значения, оно дальше функции разбора литералов никуда не шло

2021-04-14 22:06 UTC, Victor-Y-Fadeev approved these changes

2021-04-14 23:37 UTC, merged