Условные выражения и циклы
andrey-terekhov/RuC pull request #115
Opened 2021-04-22 08:38 UTC by IvanArkhipov1999

В связи с разговором 21.04.2021 представляю урезанную реализацию условий и циклов. Условные конструкции и циклы работают за исключением некоторых случаев. Следующие задачи пока не сделаны:

- объединить функции arithmetic_expression и logic_expression в связи с дубликацией кода
- реализовать битовое отрицание (в прошлом pull request по арифметическим выражениям забыл сделать это)
- реализовать работу && и || с нелогическими выражениями (например, сейчас не будет работать i && 5)
- протестировать и при необходимости реализовать случай, когда && и || есть в арифметических выражениях
- цикл for сейчас работает только в случае, если присутствуют все блоки: инициализация, условие, модификация. Соответсвенно, нужно реализовать и для случаев с их отсутвием
- в цикле for не проверено, что будет, если условие не является логическим

Данные замечания продублированы в коде в комментариях TODO. В остальном по условным выражениям и циклам всё сделано

2021-05-12 19:57 UTC, Victor-Y-Fadeev requested changes
Я наконец-то смог проверить запрос... В общем:
- Зачем хранить массивы, у вас используется только текущий?
- Смещение нельзя использовать как идентификатор
- Зачем вы добавили `mode` в `block`?
- `label_if` и `label_else` - это скорее `label_true` и `label_false`
- Функция `logic_expression` является сплошным копипастом, не делайте так

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			info->label_else = label_else;
А зачем вообще локальные `label_if` и `label_else`? Почему бы сразу не присвоить:
```c
info->label_if = info->label_num++;
info->label_else = info->label_num++;
const item_t label_end = info->label_num++;
```

P.s. Не забудьте отступ перед этим блоком.

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +
Этот отступ скорее лишний.

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +
Лишний отступ.

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			to_code_label(info, label_else);
А вот здесь видимо не хватает, как то здесь все странно сгруппировано...

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			info->label_else = label_end;
Если эти лейблы универсальные, то может стоит назвать их `label_true` и `label_false`?
Про локальные переменные см. выше.

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  			expression(info, nd);
Это все вроде как один блок обработки условия, поэтому отступы наверное стоит убрать.

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +
А здесь видимо тело, насчет второго отступа не уверен.

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  			statement(info, nd);
Вроде как обработка тела (без отступов)...

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			info->label_else = label_end;
Опять не по назначению и лишние локальные переменные... Либо же, если лейблы из `info` совсем не используются, не делайте присвоение в них! Тогда можно будет перейти на локальные, это даже лучше, но вот дублирование - плохо.

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			if (info->flag_dynamic == 1)
Не сравнивайте такие флаги с конкретными значениями:
```c
if (info->has_dynamic)
// OR
if (info->was_dynamic)
```

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			// TODO: добавить обработку других ответов (ALOGIC)
Отступ наверное.

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +					// но об этом потом
Пройтись по дереву дальше или спросить количество потомков. Динамическим может быть только последнее измерение, причем с инициализацией.

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +					}
- Зачем вы его сохраняете (больше никогда не используется)?
- Присвоение структуры с массивом - это медленно
- **Смещение != Идентификатор**, - это ну ооочень дорого, сколько памяти уходит в никуда...
- Про сравнение таких флагов с конкретными числами я уже говорил

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	}
Почему вдруг понадобилось?

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	info.flag_dynamic = 0;
Это не здесь инициализируется, а в обработке `TFuncdef`.

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	item_t to_declare_stack_functions = 0;
- Флаги типа `int`
- Перенести к следующей группе (не имеет никакого отношения к `info`)
- Вместо `to_declare` лучше `has` или `was`

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  					uni_printf(info.io, "define i32 @main(");
А если `void`?

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				}
Что с другими типами?

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				block(&info, &root, -1);
Почему? `TEnd` вроде бы не исчезал...

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				}
```c
has_stack_functions |= info.has_dynamic;
// OR
was_stack_functions |= info.was_dynamic;
```

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				info.flag_dynamic = 0;
Не по месту, удалить.

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	if (to_declare_stack_functions == 1)
Опять про конкретные числа.

2021-05-12 19:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +}
**Это просто ужасный копипаст!!!**
Удалите и больше так не делайте, у вас разница всего в одну строчку (предпоследнюю).

2021-05-13 12:31 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +	array_info arrays_info[MAX_ARRAY_DISPL];	/**< Информация о массивах. Доступ осуществляется по displ */
Пока сделано только объявление массивов, поэтому действительно используется только текущий массив. Сохраняю я необходимую информацию о массивах для вырезки, там нужно будет знать и размерность, и границы, а узел вырезки такой информацией не располагает.

2021-05-13 12:32 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +
Выше написал, зачем я сохраняю информацию.

2021-05-13 12:47 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +					}
По поводу Смещение != Идентификатор, меня самого очень корёжит от того, что в массиве структур большая часть памяти уходит в никуда. Как я написал выше, я сохраняю информацию о массивах для обработки узла вырезки. Он даёт мне только смещение и тип элемента. Так как смещение для каждого массива уникальное, то я его и стал использовать в качестве идентификатора. Можно сохранять структуры с информацией о массивах подряд, а смещение хранить как поле структуры. Память будет использоваться разумнее, но тогда придётся вместо простой вырезки по смещению вызывать функцию поиска структуры с информацией по смещению. Это работает дольше, и всё равно смещение выступает в качестве идентификатора. А так как массив для хранения структур с информацией о массивах всё равно выделяется статически, то я и подумал, что с такой небрежной работой с памятью можно смириться.

2021-05-13 12:53 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +	}
Если block вызывается при обработке узла объявления функции TFuncdef, то TEnd пропускать не нужно, иначе нужно. Подобный паттерн я увидел в кодгене виртуальной машины для функции expression и подумал, что здесь он тоже подойдёт.

2021-05-13 12:54 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
>  					uni_printf(info.io, "define i32 @main(");
Описан в коде ниже.

2021-05-13 12:54 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +				}
Другие типы пока не поддержаны.

2021-05-13 12:55 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +				block(&info, &root, -1);
Проблема с TEnd была не видна, пока я не начал реализовывать объявление нескольких функций.

2021-05-13 13:46 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +static void block(information *const info, node *const nd, int mode);
Уже не актуально, но всё же интересно: имеется в виду const у mode?

2021-05-13 13:52 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +static void block(information *const info, node *const nd, int mode);
Где const пропущен? У mode?

2021-05-13 13:54 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +static void to_code_alloc_array_static(information *const info, item_t id)
Где пропущен const?

2021-05-13 14:02 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +static void to_code_alloc_array_dynamic(information *const info, item_t id)
Аналогичные вопросы выше

2021-05-17 12:53 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +			info->label_else = label_else;
В процессе обхода дерева `info->label_if` и `info->label_else` могут поменяться, а мне в процессе генерации меток нужно знать их неизменённые значения, которые я сохраняю в `label_if` и `label_else`

2021-05-17 13:17 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +			info->label_else = label_end;
Про локальные переменные здесь такая же ситуация, как описано выше

2021-05-17 13:20 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +			info->label_else = label_end;
Здесь такая же ситуация, как я описал выше. Лейблы из `info` используются при генерации условий в командах перехода, поэтому сделать их локальными точно не получится

2021-05-17 13:26 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +					// но об этом потом
Может быть массив вида `int a[5][i][j]`, в котором часть границ статическая, а часть динамическая. По крайней мере парсер на такое не ругается

2021-05-17 14:08 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +	array_info arrays_info[MAX_ARRAY_DISPL];	/**< Информация о массивах. Доступ осуществляется по displ */
Предполагается следующая структура, для которой нужно написать интерфейс(типа взять значение по идентификатору)? 
```
typedef struct array_info
{
	vector dimension;
	vector is_static;
	vector borders[MAX_ARRAY_DIMENSION];
}
```

2021-05-22 22:06 UTC, Victor-Y-Fadeev requested changes
В общем нужно обсудить хеш-таблицу... Также вынесите работу с вещественными в другую ветку. Очень сложно проводить ревью когда вы меняете уже проверенный код, не делайте так. Запрос слияния предполагает, что вы закончили работу над какой-то частью и будете только исправлять замечания, а не дописывать новый код.

2021-05-22 22:06 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	array_info arrays_info[MAX_ARRAY_DISPL];	/**< Информация о массивах. Доступ осуществляется по displ */
Возможно нам стоит написать эту библиотеку в утилиты... Нужно обсудить в общей коференции.

2021-05-23 08:57 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +	array_info arrays_info[MAX_ARRAY_DISPL];	/**< Информация о массивах. Доступ осуществляется по displ */
Хэш таблица, пожалуй, лучшее решение. Я о подобном думал, но так как это динамическая структура, а в проекте от всей динамики было принято решение отказаться, я и от такой идеи отказался

2021-05-31 18:30 UTC, Victor-Y-Fadeev requested changes
Все еще много лишнего и недоделано взаимодействие с хеш-таблицей. Перенесите часть относящуюся к массивам из `case TDeclid` в `case TDeclarr` и избавьтесь от `current` переменных. Добавьте очистку памяти, пропускать ее - это грубая ошибка!

2021-05-31 18:30 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  				return -1;
Не очистили память!!!
```c
hash_clear(&info.arrays);
```

P.s. Не забудьте создать тело.

2021-05-31 18:30 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  	return 0;
Не очистили память!!!
```c
hash_clear(&info.arrays);
```

2021-05-31 18:30 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +		break;
Зачем тело, когда один оператор?

2021-06-01 09:35 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +} array_info_t;
Хотелось избавиться от безымянных констант. Например, `hash_set_by_index(&info->arrays, index, IS_STATIC, 0);` выглядит гораздо понятнее `hash_set_by_index(&info->arrays, index, 1, 0);`

2021-06-02 14:28 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +} array_info_t;
Начал я избавляться от `IS_STATIC` и `BORDERS` и мне как-то совсем не понравилось то, что получилось, поэтому решил оставить.

2021-06-02 14:30 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +					}
Нужно, вырезки для статических и динамических массивов обрабатываются различным образом, а узел вырезки такой информации не даёт.

2021-06-02 15:50 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +} array_info_t;
Отказано, удалить! Смысл имелся разве что в `IS_STATIC`, но у вас ни одного использования. А вот бесконечные прибавления единиц в виде `BORDERS` выглядят не читаемо, у вас во всех использованиях есть цикл, нумеруйте его с `1` включая последний элемент и везде будет читаемо.

По поводу `IS_STATIC`, можно сделать исключение только для него, так как используется вне циклов. Для этого можно завести обычную константу:
```c
const size_t IS_STATIC = 0;
```

2021-06-02 16:19 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				item_t current_array_is_static = 1;
Создавайте `N` после `displ` и сделайте его сразу `size_t`, это будет ближе к месту использования (плюс будет комментарий):
```c
const size_t N = (size_t)node_get_arg(&id, 2);	// node_get_arg(nd, 0);
```

Про тип флагов я уже писал, должен быть `int`. Его инициализацию тоже нужно перенести ближе к месту использования, например после `index`.

2021-06-02 16:19 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				item_t current_array_is_static = 1;
А вообще удалите его, зачем он вам? Это же дубликат.

2021-06-02 16:19 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				for (size_t i = 0; i < (size_t)N; i++)
```c
const size_t index = hash_add(&info->arrays, displ, N + 1);
hash_set_by_index(&info->arrays, index, IS_STATIC, 1);

node_set_next(nd);
for (item_t i = 1; i <= N; i++)

```

2021-06-02 16:19 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +						}
Этого никогда не произойдет, такие ситуации ловятся в парсере.

2021-06-02 16:19 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +						hash_set_by_index(&info->arrays, index, BORDERS + i, info->answer_const);
По моему, это проще:
```c
hash_set_by_index(&info->arrays, index, i, info->answer_const);
```
Чем это:
```c
hash_set_by_index(&info->arrays, index, BORDERS + i, info->answer_const);
```

2021-06-02 16:19 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +						current_array_is_static = 0;
```c
hash_set_by_index(&info->arrays, index, i, info->answer_reg);
hash_set_by_index(&info->arrays, index, IS_STATIC, 0);
```

2021-06-02 16:19 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				hash_set_by_index(&(info->arrays), index, IS_STATIC, current_array_is_static);
Удалить.

2021-06-02 16:19 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +						}
А в чем смысл? Вы же не выходите по ошибке. И должно быть так:
```c
if (hash_get_by_index(&info->arrays, index, IS_STATIC) && i > 1)
```

2021-06-02 16:19 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				if (current_array_is_static)
```c
if (hash_get_by_index(&info->arrays, index, IS_STATIC)
```

2021-06-02 16:19 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  				for (item_t i = 0; i < N; i++)
Недоделано.

2021-06-02 16:23 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	const size_t dim = hash_get_amount_by_index(&info->arrays, index) - 1;
Создано не по месту использования, должно быть прямо перед `for`.

2021-06-02 16:23 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	const size_t dim = hash_get_amount_by_index(&info->arrays, index) - 1;
Создано не по месту использования, должно быть прямо перед `for`.

2021-06-02 16:23 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	}
Не исправлено.

2021-06-02 16:40 UTC, Victor-Y-Fadeev requested changes
`BORDERS` как минимум используется неправильно, ибо его надо не прибавлять, а начинать считать с него, причем до `hash_get_amount - BORDERS`. А вообще не стоит плодить лишние сущности, к полю `info->arrays` есть нормальная документация и при наведении она подскажет что куда пишется. Если очень сильно хочется создайте константу:
```c
const size_t IS_STATIC = 0;
```

2021-06-02 16:40 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	}
Не исправлено, вы на каждой итерации делаете сложение, зачем? А еще код длиннее. 
```c
for (item_t i = 1; i <= dim; i++)
{
	uni_printf(info->io, "[%" PRIitem " x ", hash_get(&info->arrays, index, i));
}
```

2021-06-02 16:40 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	}
Вообще все съехало... Должно быть от `1` до `dim` включая границы и без `BORDERS`:
```c
for (size_t i = 1; i <= dim; i++)
{
	uni_printf(info->io, " %%.%" PRIitem " = mul nuw i32 %%.%" PRIitem ", %%.%" PRIitem "\n",
		info->register_num, to_alloc, hash_get_by_index(&info->arrays, index, i));
	to_alloc = info->register_num++;
}
```

А еще у вас пробел после запятой.

2021-06-02 16:40 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	for (size_t i = 0; i < dim; i++)
Давайте все же (для однородности):
```c
for (size_t i = 1; i <= dim; i++)
```

2021-06-02 16:40 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  				return -1;
Не исправлено!!!

2021-06-02 16:40 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
Отступ лишний.

2021-06-02 16:40 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	info.arrays = hash_create(HASH_TABLE_SIZE);
Так, а давайте ка сделаем по уму, вынесем инициализацию и деинициализацию наружу, а в функцию передадим готовую `info`. Это более правильно, потому что теперь есть работа с таблицами.

2021-06-03 08:45 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +				item_t current_array_is_static = 1;
Я бы этот флаг оставил скорее для читабельности, мне как-то понятнее `current_array_is_static`, чем `hash_get_by_index(&info->arrays, index, IS_STATIC)`. Да и вызывать каждый раз `hash_get_by_index` и `hash_set_by_index` не хотелось

2021-06-03 08:48 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +						}
А вот и нет, я проверял

2021-06-03 09:00 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
>  				return -1;
Разве не достаточно очищать память в конце `codegen`?

2021-06-03 09:03 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +	info.arrays = hash_create(HASH_TABLE_SIZE);
Я правильно понимаю, что память под таблицу будет выделяться в `encode_to_llvm`, а очищаться в `codegen`? Как-то странно выделять и освобождать память в разных местах

2021-06-03 09:16 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  				return -1;
Нет конечно, вы же выходите в этом месте.

2021-06-03 09:25 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +							@c value[1..MAX] - границы массива */
Да, расположение относительно начала комментария теперь правильное, но вот относительно остальных комментариев в структуре нет. Выровняйте комментарии, они должны начинаться на одном уровне.

2021-06-03 09:25 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	item_t label_false;									/**< Метка перехода при false */
У вас слишком большой отступ у комментариев, думаю можно удалить по 4 `TAB` перед каждым комментарием в структуре.

2021-06-03 09:25 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	int was_dynamic;									/**< Если в функции были динамические массивы, то @c 1, иначе @c 0 */
Думаю будет лучше:
```c
int was_dynamic;	/**< Истина, если в функции были динамические массивы */
// OR
int was_dynamic;	/**< Установлен, если в функции были динамические массивы */
```

P.s. Не забудьте про выравнивание.

2021-06-03 09:25 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				item_t current_array_is_static = 1;
Вызов этих функций ничего не стоит, они `inline`.

2021-06-03 09:33 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	item_t to_alloc = hash_get_by_index(&info->arrays, index, 1);
Почему, что такого особенного в первой границе?

2021-06-03 09:33 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	for (size_t i = 2; i <= dim; i++)
Это точно правильно? Почему со второй границы? И что если она всего одна?

2021-06-03 09:33 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	info.arrays = hash_create(HASH_TABLE_SIZE);
Нет, неправильно, я специально попросил перенести инициализацию в `encode_to_llvm`, чтобы там и очищать.

2021-06-03 09:33 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +						}
Пришлите тест.

2021-06-03 09:37 UTC, Victor-Y-Fadeev requested changes
Пришлите тест на вызов ошибки из комментария.

2021-06-03 09:37 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	hash_clear(&info->arrays);
Удалить, работа с памятью перенесена в `encode_to_llvm`.

2021-06-03 09:37 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  	while (node_set_next(&root) == 0)
Теперь стоит добавить сюда отступ.

2021-06-03 09:37 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	info.arrays = hash_create(HASH_TABLE_SIZE);
Отступ, так как блок выделения памяти.

2021-06-03 09:37 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	return codegen(&info);
Должно быть так:
```c
const int ret = codegen(&info);

hash_clear(&info.arrays);
return ret;
```

2021-06-03 09:55 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +	item_t to_alloc = hash_get_by_index(&info->arrays, index, 1);
Для того чтобы для динамического массива выделить память, нужно перемножить его границы. Перемножать границы можно только начиная со второй. Если одна граница, то даже и перемножать не нужно

2021-06-03 10:20 UTC, Victor-Y-Fadeev approved these changes

2021-06-03 10:20 UTC, merged