Сортировка констант
andrey-terekhov/RuC pull request #122
Opened 2021-05-21 19:16 UTC by bugdea1er

https://gitlab.softcom.su/ruc/ruc/-/issues/122

2021-06-02 11:26 UTC, Victor-Y-Fadeev requested changes
- В большом количестве мест не хватает разделителей (`_`), их не стоит ставить только в именах собственных, например `strcpy`
- В комментария стоит использовать одинарные кавычки, так проще читать
- Библиотеку `node.h` и ее содержимое стоит переименовать в `type.h`
- Огромные `switch`-`case` - нехорошо, так как не масштабируется от слова совсем, если я добавлю новое значение придется в "10" местах правки вносить (вам нужна совместимость только кодов виртуальной машины)
- Создавайте и пользуйтесь промежутками, они гораздо быстрее `case` написанных подряд (в разумных пределах, например непересекающиеся)
- Пользуйтесь своими функциями конвертации, тогда вспомогательные типы будут изолированы

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.h
> + *	@return	@c 1 on assignment operator
```c
 *	@return	@c 1 on true, @c 0 on false
```

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.h
> +int node_is_assignment_operator(const node_t node);
Если везде убрать постфикс `operator` будет однороднее (и `ver` не ставить).

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.c
> +#include "stdio.h"
Зачем?

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.c
> +
2 отступа.

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.c
> +	}
Суть задачи была в том, чтобы избавится от этого. Часть про обратную совместимость упоминалась в обсуждении как вариант хорошего старта, а не решения. Исключение только совместимость кодов.

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.c
> +	}
Уже написал, подумайте как сделать по другому (внутренние значения констант самого транслятора можно менять).

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.c
> +	}
Еще раз.

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.c
> +	}
- В таких случаях сразу пишется `return`
- Сравнение конкретных значений убивает расширяемость, вводите промежутки!
- Магическое число **`200`**
  - Во первых, используйте локальные константы в `*.c`
  - Во вторых, если корректно введете промежутки, эти константы будут вида `BEGIN_SECOND - BEGIN_FIRST`

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.c
> +	}
Актуальны все замечания из `node_void_operator`.

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.c
> +		|| (op >= ND_POSTINCR && op <= ND_PREDECR) || (op >= ND_POSTINCRV && op <= ND_PREDECRV))
Все замечания из `node_void_operator` и здесь даже сокращенная запись условного оператора не нужна, сразу возвращайте результат условного выражения.

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_stmt.c
>  			return 1;
А нельзя проверить промежутком?

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		case TOK_GREATEREQUAL:
Опять про промежуток.

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +			|| token == TOK_GREATERGREATER || token == TOK_LESSLESS || token == TOK_PERCENT)
А получится промежутком?

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +				node_set_type(&prs->nd, mode_is_float(type) ? ND_IDENTTOVALD : ND_IDENTTOVAL);
У вас же есть функция конвертации...

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +				to_tree(prs, mode_is_float(type) ? ND_ADDRTOVALD : ND_ADDRTOVAL);
Пользуйтесь функциями конвертации.

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +	to_tree(prs, mode_is_float(type) ? ND_STRINGD : ND_STRING);
Пользуйтесь функциями конвертации.

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		case TOK_STRLEN:
Промежутком возможно?

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		case TOK_RECEIVE_STRING:
Здесь точно получится промежутком.

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		case TOK_GETNUM:
И здесь, это все функции работы с потоками.

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		case TOK_CARETEQUAL:			// '^='
Можно ли промежутком?

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		case TOK_MINUSEQUAL:			// '-='
Промежуток?

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +	node_set_type(&prs->nd, node_void_operator((node_t)node_get_type(&prs->nd)));
А без приведения не работает?

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.h
> +	ND_EXPRESSION_END,		/**< End of expression node */
Думаю тут вполне можно и сократить до `T_EXPR_END` (раз `DECL` сократили).

2021-06-02 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/instructions.h
> +	IC__DOUBLE,			/**< "_DOUBLE" instruction code */
Нельзя ли переназвать? Двойное подчеркивание ни о чем не говорит и плохо заметно.

2021-06-02 11:41 UTC, bugdea1er commented on libs/compiler/instructions.h
> +	IC__DOUBLE,			/**< "_DOUBLE" instruction code */
Названия инструкций не изменялось с предыдущей версии
Если здесь менять, то и в интерпретаторе надо будет переименовывать

2021-06-02 11:43 UTC, bugdea1er commented on libs/compiler/tokens.h
> +#define STANDARD_FUNC_START  TOK_PRINT
Границы не должны относиться к перечислению, мне кажется, что лучше через define - так они явно выделяются средой другим форматированием и не являются членом перечисления (к тому же, такой способ не дает пересечений внутри enum)

2021-06-02 11:44 UTC, bugdea1er commented on libs/compiler/codes.c
> -			break;
Не видел ни одного использования этого узла и до этого

2021-06-02 11:47 UTC, bugdea1er commented on libs/compiler/errors.c
> +			sprintf(msg, "максимально в printf/печатьф можно выводить %zu значений", MAXPRINTFPARAMS);
Разве? size_t должен быть беззнаковым, u - unsigned, i - для знаковых целых
Clang предлагает ставить %zu

2021-06-02 11:48 UTC, bugdea1er commented on libs/compiler/syntax.h
> +#define MAXSTRINGL	128
Это не относится к тем перечислениям, нужно какое-то другое место

2021-06-02 11:49 UTC, bugdea1er commented on libs/compiler/nodes.h
> +	ND_NOT = 8052,			/**< "BITNOT" node */
Эти числа используются только изнутри, снаружи ни значение, ни разница значений не используется

2021-06-02 11:50 UTC, bugdea1er commented on libs/compiler/nodes.h
> +typedef enum NODE
`type` звучит не особо конкретно, предлагаю тогда уж `node_type`

2021-06-02 11:52 UTC, bugdea1er commented on libs/compiler/nodes.c
> +	}
Это конвертация из одного перечисления в другое. Им нельзя знать конкретные детали друг о друге, например, порядок следования констант. Других способов сделать это я не вижу

2021-06-02 11:53 UTC, bugdea1er commented on libs/compiler/nodes.c
> +	}
Здесь аналогично два отдельных перечисления

2021-06-02 11:55 UTC, bugdea1er commented on libs/compiler/nodes.c
> +	}
Здесь проблема в том, что не у каждого оператора есть версии с плавающей точкой, адресной арифметикой и так далее. У одного оператора их может быть 8, у другого - только 2. Если хотим оставить код простым (`+ const` вместо switch-case), то большинству из них придется руками задавать код. Если задавать это промежутками через отдельные константы, то:
1. Они будут видны снаружи, что не нужно и вроде как неправильно
2. Перечисление в размерах вырастет еще больше

2021-06-02 11:57 UTC, bugdea1er commented on libs/compiler/parser_stmt.c
>  			return 1;
Этот промежуток, как и несколько ниже, используются по одному разу, и состоят из 6-8 констант. Думаю, что лучше так оставить, читается вполне хорошо, не нужно следить за порядком констант

2021-06-02 11:59 UTC, bugdea1er commented on libs/compiler/parser_expr.c
> +				node_set_type(&prs->nd, mode_is_float(type) ? ND_IDENTTOVALD : ND_IDENTTOVAL);
Опять же, такое вызывается по одному разу, а чтобы использовать функцию конвертации, нужно в float_operation прописать по case на каждый такой случай + в конвертации еще пару строк
Читаемости это не поможет, а код увеличит

2021-06-02 14:57 UTC, Victor-Y-Fadeev commented on libs/compiler/tokens.h
> +#define STANDARD_FUNC_START  TOK_PRINT
Как раз границы должны принадлежать `enum`, тогда они будут и константными и типизированными. Если пересечение значений для вас критично, а сами значения нет, то можно перейти к строгим неравенствам и отказаться от инициализации.
По поводу препроцессора, его стоит использовать как можно меньше, только когда по другому никак. Препроцессор определяет не типизированные константы и происходит в отдельный этап, поэтому результат его работы сложнее анализировать -> меньше возможных предупреждений -> больше чуть возможностей ошибиться.

2021-06-02 14:57 UTC, Victor-Y-Fadeev commented on libs/compiler/codes.c
> -			break;
Принято.

2021-06-02 15:03 UTC, Victor-Y-Fadeev commented on libs/compiler/errors.c
> +			sprintf(msg, "максимально в printf/печатьф можно выводить %zu значений", MAXPRINTFPARAMS);
Вижу, вы правы... У нас сейчас везде `%zi`, поставьте пока его, для однородности, и заведите глобальную задачу по исправлению всех использований. Или я могу создать...

2021-06-02 15:05 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.h
> +#define MAXSTRINGL	128
Ладно, но все равно стоит переименовать.

2021-06-02 15:09 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.h
> +typedef enum NODE
`node_type` - это просто развернутая запись `node_t`, все еще сливается и путается с `node_something`. Отдельного `type` у нас еще нигде не было и получается он как раз из `node_get_type`, поэтому вроде подходит... Негромоздко и запоминается.

2021-06-02 15:11 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.h
> +	ND_NOT = 8052,			/**< "BITNOT" node */
Зачем вы их задаете? Если я допишу что-то в середину `enum` может произойти пересечение, это плохо для масштабируемости.

2021-06-02 15:14 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.c
> +	}
Нуу глобально стоит вообще удалить `instructions.h`, а всю конвертацию перенести сюда. Это интерфейс совместимости с виртуальной машиной, он как раз может и должен знать о внутреннем устройстве обоих типов.

2021-06-02 15:18 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.c
> +	}
Это внутренние типы, они произошли по сути из одного файла `defs.h`, думаю им можно знать друг о друге. Особенно с учетом того, что они в интерфейсе. Стоит расположить их таким образом, чтобы у одного был приоритет выше, чем у другого, и инициализировать промежуток второго, через первый (этот блок должен быть прокомментирован в обоих файлах как синхронизованный).

2021-06-02 15:24 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.c
> +	}
- Промежутками вполне возможно добиться желаемого:
  - Проверяете из какого промежутка код
  - Прибавляете соответствующую ему разницу
  - Несколько `if`-`else` сильно быстрее, `switch`-`case`, а `BEGIN`-`END` блоки обеспечат читаемость
- Константы начала и конца в любом случае будут видны и это в общем правильно (просто избыточный интерфейс, не внутренняя реализация)
-  Вырастет не сильно, не комментируйте `BEGIN`-`END` блоки и будет заметнее

2021-06-02 15:26 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_stmt.c
>  			return 1;
А зачем у этих констант значения не по порядку и что если я захочу новый тип добавить? Придется искать такие места в коде, что не очень очевидно и удобно.

2021-06-02 15:29 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +				node_set_type(&prs->nd, mode_is_float(type) ? ND_IDENTTOVALD : ND_IDENTTOVAL);
- Если `type_to_float` будет реализован на промежутках вы все это бесплатно получите
- Оптимизации должны будут потом весь этот код по выпиливать, так как он предопределен
- Что значит еще пару строк? Просто `type_to_float(T_IDENT_TO_VAL)` вместо `T_IDENT_TO_VAL`

P.s. Заодно проверки принадлежности станут быстрее.

2021-06-02 15:34 UTC, Victor-Y-Fadeev commented on libs/compiler/instructions.h
> +	IC__DOUBLE,			/**< "_DOUBLE" instruction code */
В смысле в интерпретаторе? Думаю там `_` только из-за пересечений со стандартными, а у вас есть префикс

2021-06-02 15:35 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.c
> +	}
Так, а вообще зачем вам эта функция? у вас одно использование и то для отладки...

2021-06-02 15:41 UTC, Victor-Y-Fadeev commented on libs/compiler/nodes.c
> +	}
Думаю непересекающиеся коды можно перенести в `codegen.h` или `type.h`, а остальные получать из типов узлов конвертацией, например создать функцию `mem_add_node`. Тогда при создании нового узла мы без увеличения `switch` получим новый код.

2021-06-03 12:16 UTC, bugdea1er commented on libs/compiler/nodes.c
> +#include "stdio.h"
Для size_t

2021-06-04 07:32 UTC, bugdea1er commented on libs/compiler/instructions.h
> +	IC__DOUBLE,			/**< "_DOUBLE" instruction code */
Оно не пересекалось со стандартными (регистр важен), и этот узел не для типа double, а для операции, которая дублирует значение. Согласен, что нужно переименовать, так как без подсматривания в код интерпретатора и не скажешь, что эта операция делает, но нужно переименовывать согласованно.
В DOUBLE нет смысла переименовывать, потому что тогда будет еще больше похоже на двойной тип

2021-06-04 11:50 UTC, bugdea1er commented on libs/compiler/tokens.h
> +	TOK_CHAR_CONST,					/**< Character Constant [C99 6.4.4.4] */
Не думаю, тогда TK_INT и подобные придется переименовать в TK_KW_INT для единообразия.
Тут всего три константы, их и не надо выделять особым образом

2021-06-04 12:02 UTC, bugdea1er commented on libs/compiler/tokens.h
> -	//kw_register,						/**< 'register'	keyword */
Я так понял, что не все из них планируются к реализации, давайте добавлять при необходимости

2021-06-04 12:10 UTC, bugdea1er commented on libs/compiler/nodes.h
> +node_t token_to_node(const token_t token);
Есть префиксы operation_ и token_, и функции работы с токенами уже существуют и имеют префикс token_, просто в другом месте

2021-06-07 16:01 UTC, Victor-Y-Fadeev requested changes
- Со `switch` в `operations.c` совсем ничего нельзя сделать?
- Сравнения с конкретными значениями нельзя заменить на проверку принадлежности промежутку `[BEGIN_CONVERTIBLE..END_CONVERTIBLE]`?
- Исправьте документацию в `operations.h`, у вас то операция, то оператор то еще что-нибудь
- Названия инструкций стоит сделать такими же как у операций, за исключением префикса
- Нет ли "потерянных" операций (`OP_CREATE_DIRECT` или `OP_EXIT_DIRECT`)?
- Верните `MAX_STRING_LENGTH` в `syntax.h`

2021-06-07 16:22 UTC, bugdea1er commented on libs/compiler/tokens.h
> +	TK_CHAR	= -200,					/**< 'char'		keyword */
Нужно, чтобы токены имели отрицательный код и влезло в таблицу из item_t. Можно сделать ITEM_MIN

2021-06-07 16:31 UTC, bugdea1er commented on libs/compiler/tokens.h
> +	TK_EOF		= -1,				/**< End of file */
Это токен, а не символ, ему тоже нужно быть в перечислении

2021-06-07 16:36 UTC, bugdea1er commented on libs/compiler/operations.h
> +	BEGIN_FINAL_OPERATION	= 7000,
Старое дерево плохо реагировало на маленькие коды типов узлов (видимо, константы принимала за узлы) и ругалось

2021-06-07 16:39 UTC, bugdea1er commented on libs/compiler/operations.h
> +	OP_AD_LOG_OR,									/**< 'ADLOGOR' node */
Если поставить в конец прямо перед END_OP_FINAL, то будут пересечения, потому что END_OP_FINAL определяется через перечисление инструкций. Учитывая, что BEGIN_OP_FINAL нужно какое-то значение, чтобы старое дерево не ругалось, проще оставить эти инструкции тут

2021-06-07 16:49 UTC, bugdea1er commented on libs/compiler/operations.h
> +	OP_SUB_R				= IC_MINUSR,			/**< '-f' node */
Minus - символ, subtraction - операция

2021-06-07 16:49 UTC, bugdea1er commented on libs/compiler/operations.h
> +	OP_NE_R					= IC_NOTEQR,			/**< '!=f' node */
eqeq = equal_equal - лексема, а операция уже просто на равенство

2021-06-07 16:51 UTC, bugdea1er commented on libs/compiler/operations.h
> +	OP_XOR					= IC_EXOR,				/**< '^' node */
XOR как-то чаще встречается для названия операции, еще и по длине совпадает с остальными

2021-06-07 16:53 UTC, bugdea1er commented on libs/compiler/operations.h
> +	OP_EXIT_DIRECT,			/**< Exit direct thread node */
Из-за того, что это statement, все равно прямая конвертация не нужна, тогда и не нужно тут коды синхронизировать

2021-06-07 16:54 UTC, bugdea1er commented on libs/compiler/operations.h
> +	OP_AOP_ASSIGN_AT_V		= IC_ANDASSATV,			/**< '&=@V' node */
Опечатка из-за автозамен

2021-06-07 17:38 UTC, bugdea1er commented on libs/compiler/operations.h
> +	OP_ADDR_TO_VAL_D,		/**< Address to double value node */
Для этих элементов можно было бы задать `обычная версия + DISPL_TO_FLOAT`, но идентификатор в константном выражении - нестандартное расширение С, в enum такое нельзя писать

2021-06-07 17:39 UTC, bugdea1er commented on libs/compiler/operations.c
> +}
Не стоит все же токены с операциями связывать

2021-06-07 17:40 UTC, bugdea1er commented on libs/compiler/operations.c
> +}
Такие сравнения только внутри используются, надо ли для одного случая?

2021-06-08 10:04 UTC, Victor-Y-Fadeev commented on libs/compiler/operations.h
> + *	@return	Corresponding operation type
```c
 *	@return	Binary operation
```

2021-06-08 10:04 UTC, Victor-Y-Fadeev commented on libs/compiler/operations.h
> + *	@return	Corresponding operation type
```c
 *	@return	Unary operation
```

2021-06-08 10:05 UTC, Victor-Y-Fadeev commented on libs/compiler/operations.h
> + *	@return	Corresponding operation type
```c
 *	@return	Function operation
```

2021-06-08 10:06 UTC, Victor-Y-Fadeev commented on libs/compiler/operations.h
> + *	Convert token to corresponding binary operation type
`type` - лишнее, так получаем конкретную операцию, а под типом можно понять, например, перечисление операций.

2021-06-08 10:06 UTC, Victor-Y-Fadeev commented on libs/compiler/operations.h
> + *	Convert token to corresponding unary operation type
`type` - лишнее, так получаем конкретную операцию, а под типом можно понять, например, перечисление операций.

2021-06-08 10:06 UTC, Victor-Y-Fadeev commented on libs/compiler/operations.h
> + *	Convert token to corresponding function operation type
`type` - лишнее, так получаем конкретную операцию, а под типом можно понять, например, перечисление операций.

2021-06-08 10:11 UTC, Victor-Y-Fadeev commented on libs/compiler/operations.h
> +	OP_AD_LOG_OR,										/**< 'ADLOGOR' node */
Может тогда оформим так:
```c
	BEGIN_OP_FINAL,

	...

	OP_AD_LOG_AND		= MAX_INSTRUCTION_CODE,		/**< 'ADLOGAND' node */
	OP_AD_LOG_OR,						/**< 'ADLOGOR' node */

	END_OP_FINAL,
```

2021-06-08 10:12 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.h
2 отступа.

2021-06-08 10:19 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_stmt.c
> +#define MAX_PRINTF_ARGS (size_t)20
Тогда уж лучше перед вызовом ошибки напишите.

2021-06-08 10:20 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_stmt.c
> +					parser_error(prs, too_many_printf_args, MAX_PRINTF_ARGS);
Так будет понятнее, если что-то в `errors.c` поменяется:
```c
parser_error(prs, too_many_printf_args, (size_t)MAX_PRINTF_ARGS);
```

2021-06-08 10:24 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +								: to_modetab(prs, mode_array, mode_character));
Еще по 3 `TAB`, на GitHub они в 2 раза больше, поэтому копирование не особо работает.

2021-06-08 11:01 UTC, bugdea1er commented on libs/compiler/operations.h
> +	OP_AD_LOG_OR,										/**< 'ADLOGOR' node */
C BEGIN_OP_FINAL все еще проблема старого дерева

2021-06-08 16:48 UTC, Victor-Y-Fadeev approved these changes

2021-06-08 16:54 UTC, merged