Вырезки из массивов и фикс llvmopt под новое дерево
andrey-terekhov/RuC pull request #127
Opened 2021-06-07 09:07 UTC by IvanArkhipov1999

2021-06-07 18:32 UTC, Victor-Y-Fadeev requested changes
Откатите все изменения в `.travis.yml` и `scripts/test.sh`:
```
$ git revert 882e9a938f6e0b6a1c4de503a0dd0fd8e2ffc3aa
$ git revert c9105319b77cb30aa8f86b2040620ea702310d6a
$ git revert 273773ef20ed0e0be948534e221d52e7f3ba9583
```

Чтобы возобновить тестирование LLVM - добавьте в `main.c`:
```c
workspace ws = ws_parse_args(argc, argv);
ws_add_flag(&ws, "-LLVM");
```

2021-06-08 09:27 UTC, Victor-Y-Fadeev requested changes
Когда полностью перейдем на новое дерево, функции `swap` и `order` станут принимать непосредственно переставляемые узлы и понадобится обновить реализацию. Также нужно будет перейти на `node_save`, `node_load` и полноценный стек для хранения.

2021-06-08 09:27 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
>  }
Это называется `resize`, а не `clear`.

2021-06-08 09:27 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +				// если вырезка не переставлена, то надо частично очистить стек и изменить глубину TSliceident
Перенесите внутрь тела.

2021-06-08 10:43 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +					to_code_operation_const_reg(info, LMULT, info->answer_const, hash_get(&info->arrays, displ, 2));
Когда мы получили значение первого индекса, для доступа к памяти надо умножить это значение на вторую границу. Это связано со стеком и устройством памяти в llvm

2021-06-08 11:41 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +		}
Я бы не стал менять инициализацию, так как тогда станет неочевидным значение некоторых сравнений. Например, `if (dimentions == cur_dimention)` означает, что сейчас идёт первая вырезка. А изменение инициализации `cur_dimention` вынудит в подобных местах добавлять 1, что отрицательно повлияет на понимание кода

2021-06-08 11:58 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +	size_t slice_stack_size;							/**< Размер стека в начале вырезки */
Не очень понимаю, как друг через друга можно вычислить `slice_depth` и `slice_stack_size`. Не все узлы в вырезке добавляются в стек (например, `TExprend` или `TSlice`). Причём количество таких узлов может быть разным в зависимости от вырезки. И что должна делать функция `stack_peek_depth`? Это getter для размера стека?

2021-06-09 12:28 UTC, Victor-Y-Fadeev requested changes

2021-06-09 12:28 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +	size_t slice_stack_size;							/**< Размер стека в начале вырезки */
```c
static inline size_t stack_peek_depth(information *const info)
{
	return info->stack[info->stack_size - 1].depth;
}

last_depth = stack_peek_depth(information *const info);
slice_depth = last_depth  - slice_stack_size;
slice_depth = slice_stack_size;		// Переименование
```

2021-06-10 09:17 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +	size_t slice_stack_size;							/**< Размер стека в начале вырезки */
`last_depth` не всегда равна `stack_peek_depth(information *const info)`, а только после добавления операции в стек. Потом идёт уменьшение `last_depth`, чтобы пропускать уже переставленные ноды. По сути это счётчик для пропуска переставленных нод. `slice_depth` нужен, чтобы указать глубину ноды вырезки `TSliceident`. Глубина `TSliceident` указывается до переставления нод в выражении, использующем вырезку, поэтому `last_depth = 1`. В связи с этим я не понимаю, почему `slice_depth = last_depth  - slice_stack_size`. Да даже если использовать не `last_depth`, а напрямую `stack_peek_depth(information *const info)`, то всё равно неверно, потому что наверху стека `TSliceident` с невычисленной пока глубиной

2021-06-14 14:11 UTC, Victor-Y-Fadeev approved these changes

2021-06-14 14:11 UTC, merged