Операции с double + устранение некоторых недоработок
andrey-terekhov/RuC pull request #137
Opened 2021-06-17 09:15 UTC by IvanArkhipov1999

Реализована работа с типом double (кроме преобразования типов). Из прошлых недоработок сделаны ++ и -- для вырезок и операция битового отрицания.

2021-06-17 11:26 UTC, bugdea1er reviewed
- Пробелы в конце строк, вылезаете за 120 символов и забытые const у аргументов
- Непонятно, зачем вводить еще одно перечисление для типов

В принципе, удобно иметь отдельный тип для типов, код будет приятнее читать. Но учитывая, что типы не только принадлежат перечислению, но и бывают индексами для таблицы modes, предлагаю вариант `typedef item_t type_t`

2021-06-17 11:26 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +typedef enum TYPES
А зачем? Есть уже перечисление mode_t, которое лежит в syntax.h, это перечисление чего-то нового не дает, ведь тут mode_integer всегда транслируется в I32, а mode_float - в DOUBLE.

Используйте mode_ вплоть до печати в коды llvm:
```
static void type_to_io(universal_io *const io, const type_t type)
{
	if (mode_is_int(type))
	{
		uni_printf(io, "i32");
	}
	else if (mode_is_float(type))
	{
		uni_printf(io, "double");
	}
	else if (mode_is_void(type))
	{
		uni_printf(io, "void");
	}
}
```

2021-06-17 11:26 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +static double to_double(const int64_t fst, const int64_t snd)
В файле parser_expr.h лежит функция `node_get_double`, возможно, лучше перенести ее туда, где будет видно всем и пользоваться ей,

2021-06-17 13:45 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +typedef enum TYPES
Функции mode_is в ветке llvm объявлены в parser.h. Это нехорошо, но я так понимаю, после мерджа с веткой рефакторинга они будут в синтаксисе.

2021-06-17 13:51 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +static double to_double(const int64_t fst, const int64_t snd)
[Ссылка на issue в gitlab](https://gitlab.softcom.su/ruc/ruc/-/issues/143)

2021-06-20 21:32 UTC, 6easy9 requested changes
Небольшие недочеты в оформлении

2021-06-20 21:32 UTC, 6easy9 commented on libs/compiler/llvmgen.c
> +#include <string.h>
Стандартные библиотеки подключаются перед пользовательскими

2021-06-20 21:32 UTC, 6easy9 commented on libs/compiler/llvmgen.c
>  #include "llvmopt.h"
.h файл с идентичным для .c файла называнием подключается самым первым

2021-06-20 21:32 UTC, 6easy9 commented on libs/compiler/llvmgen.c
> +typedef item_t type_t;
Зачем?

2021-06-20 21:32 UTC, 6easy9 commented on libs/compiler/llvmopt.c
> +						mode_get(info->sx, node_get_arg(&child_to_swap, 1) + 1) == mode_float)))
Знак логической операции, ',' и прочие разделители переносятся на следующую строку. Следует проверить по всему коду

2021-06-21 08:37 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
>  #include "llvmopt.h"
Это `llvmopt.h`, а не `llvmgen.h`, так что он на своём месте

2021-06-21 08:44 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +typedef item_t type_t;
Тут я сошлюсь на [замечание Ильи](https://github.com/andrey-terekhov/RuC/pull/137#pullrequestreview-686106373). Насколько я понял, Виктор сказал, что типы должны быть `item_t` (мне так Илья объяснил). А чтобы в кодогенераторе обзывать типы не item_t, а чем-то более понятным по смыслу, Илья и предложил переименовать в `type_t`

2021-06-21 08:50 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +typedef item_t type_t;
Ну да, в переменной типа `type_t` всегда понятно, что находится, в отличие от почти универсального `item_t`

2021-06-22 18:25 UTC, 6easy9 requested changes
Следует убрать тип type_t

2021-06-24 02:36 UTC, 6easy9 approved these changes
В принципе, претензий нет

2021-06-24 09:12 UTC, Victor-Y-Fadeev commented
- Функции `is_something` должны теперь возвращать `bool`
- Опять переносите параметры на новую строчку без запятой
- Потеряли `const` в параметрах функций
- Переносите на следующую строку в том числе и по смыслу, а не только когда не помещается (например не стоит разрывать `fst` и `snd`)
- Зачем добавили в глобальную структуру `sx` и не пользуетесь?

2021-06-24 09:57 UTC, bugdea1er approved these changes

2021-06-24 10:02 UTC, merged