Перенос и переименования таблиц и функций modes
andrey-terekhov/RuC pull request #139
Opened 2021-06-18 19:46 UTC by bugdea1er

- Функции mode_is перенесены в syntax
- Переименования mode в type

В некоторых местах то, что ранее называлось type, переименовано в kind

2021-06-20 21:43 UTC, 6easy9 requested changes
Проверить порядок подключения файлов, убрать лишние. Для чего переименование типа type_t?

2021-06-20 21:43 UTC, 6easy9 commented on libs/compiler/codegen.c
>  				expression(vm, nd, 0);
Исправить сортировку подключенных файлов, нарушен алфавитный порядок

2021-06-20 21:43 UTC, 6easy9 commented on libs/compiler/syntax.c
> +static inline item_t get_static(syntax *const sx, const type_t type)
Для чего переименование типа?

2021-06-20 21:43 UTC, 6easy9 commented on libs/compiler/syntax.h
> +typedef item_t type_t;
Зачем?

2021-06-21 09:34 UTC, bugdea1er commented on libs/compiler/syntax.h
> +typedef item_t type_t;
Ссылка на обсуждение в другом запросе
https://github.com/andrey-terekhov/RuC/pull/137#discussion_r655187315

2021-06-22 18:32 UTC, 6easy9 approved these changes
Претензий нет.

2021-06-22 18:50 UTC, merged