Linker
andrey-terekhov/RuC pull request #140
Opened 2021-06-20 09:11 UTC by Egor-Anikin

На проверку файлы linker.c и lincer.h

2021-06-22 19:35 UTC, 6easy9 requested changes

2021-06-22 19:35 UTC, 6easy9 commented on libs/macro/linker.c
> +	}
Для этой задачи есть функции vector_increase или vector_resize

2021-06-22 19:35 UTC, 6easy9 commented on libs/macro/linker.c
> +	if(linker_is_correct(lk) && index < lk->sources && vector_get(&lk->included, index) == 0)
Пробел

2021-06-22 19:35 UTC, 6easy9 commented on libs/macro/linker.c
> +			return input;
Сделать блок else и оставить return в конце

2021-06-22 19:35 UTC, 6easy9 commented on libs/macro/linker.c
> +			return input;
Аналогично 94

2021-06-22 19:35 UTC, 6easy9 commented on libs/macro/linker.c
> +
Добавить отступ

2021-06-22 19:35 UTC, 6easy9 commented on libs/macro/linker.c
> +
Добавить отступ

2021-06-22 19:35 UTC, 6easy9 commented on libs/macro/linker.c
> +
Добавить отступ

2021-06-22 19:35 UTC, 6easy9 commented on libs/macro/linker.c
> +
Добавить отступ

2021-06-22 19:35 UTC, 6easy9 commented on libs/macro/macrogenerator.c
> +int macro_form_io(workspace *const ws, universal_io *const output)
Служебные функции должны быть static

2021-06-22 19:35 UTC, 6easy9 commented on libs/macro/parser.c
> +}
Отсутствует отступ

2021-06-24 08:36 UTC, Egor-Anikin commented on libs/macro/linker.c
> +	}
В этом случаи нет гарантии что вектор будет проинициализирован нулями.

2021-06-28 09:27 UTC, 6easy9 requested changes
Инициализацию лучше сделать через существующую функцию. 
Почему не собирается? Надо исправить.
В остальном к linker нет претензий

2021-06-28 09:27 UTC, 6easy9 commented on libs/macro/linker.c
> +	}
В тех функциях инициализация нулями сделана

2021-06-30 02:02 UTC, 6easy9 commented
Замечаний пока что нет

2021-06-30 02:02 UTC, 6easy9 approved these changes

2021-07-03 08:51 UTC, 6easy9 requested changes
К реализации вопросов нет, нужно добавить недостающие функции (документацию и шапку описания)
Исправить неточности

2021-07-03 08:51 UTC, 6easy9 commented on libs/macro/error.c
> +
Добавить разделитель (двойной отступ перед и после)

2021-07-03 08:51 UTC, 6easy9 commented on libs/macro/error.c
> +void get_message_error(const int num, char *const msg)
Служебные функции должны быть static

2021-07-03 08:51 UTC, 6easy9 commented on libs/macro/macro.c
> +/*
Думаю, следует переименовать в macrogenerator, поскольку, в диаграмме используется именно это название

2021-07-03 08:51 UTC, 6easy9 commented on libs/macro/error.h
> +
Следует добавить документацию остальных функций, описанных в диаграмме. Двойное отступ между блоками, одинарный между функциями в блоке)

2021-07-03 08:51 UTC, 6easy9 commented on libs/macro/error.c
> +}
Следует добавить шапки всех функций, описанных в диаграмме, без реализации, соблюдая все отступы.

2021-07-03 08:51 UTC, 6easy9 commented on libs/macro/parser.h
> +
Нужно добавить документацию parser_clear

2021-07-03 08:51 UTC, 6easy9 commented on libs/macro/parser.h
> + *	Check that linker structure is correct
Вместо linker parser

2021-07-03 08:51 UTC, 6easy9 commented on libs/macro/parser.h
> +	universal_io *out;				/**< Ourput io structure */
Опечатка

2021-07-03 08:51 UTC, 6easy9 commented on libs/macro/parser.c
> +}
Добавить parser_clear, соблюдая отступы

2021-07-03 08:51 UTC, 6easy9 commented on libs/macro/parser.c
> +	prs.lk = lk;
Порядок:
Lk
Stg

In
Out

Line

Is_recovery_disabled

2021-07-03 08:51 UTC, 6easy9 commented on libs/macro/parser.c
> +
Добавить parser_error, соблюдая отсупы

2021-07-03 21:03 UTC, Egor-Anikin commented on libs/macro/macro.c
> +/*
Виктор просил переименовать в macro

2021-07-03 22:02 UTC, 6easy9 commented
Замечаний нет

2021-07-03 22:02 UTC, 6easy9 approved these changes

2021-07-05 14:30 UTC, bugdea1er requested changes
Только мелкие замечания по оформлению

2021-07-05 14:30 UTC, bugdea1er commented on libs/macro/linker.h
> + *	Open new incude file
И здесь тоже мб лучше header, как и в названии функции

2021-07-05 14:30 UTC, bugdea1er commented on libs/macro/linker.h
> + *	Find file through dirs in workspace
Лучше без сокращений в документации, место есть

2021-07-05 14:30 UTC, bugdea1er commented on libs/macro/linker.c
> +		}
Лишний отступ в конце строки

2021-07-05 14:30 UTC, bugdea1er commented on libs/macro/linker.c
> +	vector_clear(&lk->included);
Лучше `return vector_clear(&lk->included);`

2021-07-05 15:03 UTC, bugdea1er approved these changes
Замечаний больше нет

2021-07-05 16:36 UTC, merged