Рефакторинг половины кодогенератора
andrey-terekhov/RuC pull request #141
Opened 2021-06-22 20:03 UTC by bugdea1er

Тут переписана половина кодогенератора, которая отвечает за генерацию объявлений, операторов и инициализацию.
- Переписана генерация объявлений, теперь объявление массива не использует fallthrough по дереву
- Генерация операторов разнесена на мелкие функции, set_next не используется
- Выражения пока не переписывались, для них пока что был сделан переходник, потому что иначе им не передать константные ноды. Генератор выражений планируется на переписывания в рамках https://gitlab.softcom.su/ruc/ruc/-/issues/89
- Проведены переименования: теперь функции содержат в названии действие (по стайлгайду), структура имеет более понятное название
- Узлы окончания теперь игнорируются, а чтение происходит по известному числу потомков, поэтому узлы окончания можно будет убрать

Названия emit и codegenerator открыты для обсуждения, но функциям нужно действие в названии, а название структуры - хоть примерно отражать ее суть. Emit используется и gcc, и в clang, и даже в компилятор swift заглянул, там тоже, имеет вполне короткое написание, но при этом понятно, что оно делает

2021-06-24 02:56 UTC, 6easy9 requested changes
Претензий пока что нет, только нужно комментарий дописать, как я понял, что-то пропало.

2021-06-24 02:56 UTC, 6easy9 commented on libs/compiler/codegen.c
> +		// Первый раз встретился переход на еще не описанную метку или нет
Или нет чего?

2021-06-28 08:53 UTC, 6easy9 commented
Претензий нет

2021-06-28 08:59 UTC, 6easy9 approved these changes

2021-06-29 22:58 UTC, Victor-Y-Fadeev requested changes
Верните старое название структуры, читать невозможно, у меня изменение в каждой строчке и ничего содержательного. Лучше потом отдельным запросом или вообще забыть.

Глобально у вас проблемы с префиксами. Много общих префиксов, а вы их в конец пихаете, нивелируя помощь авто-подстановки. Либо выкинете их, либо поставьте в середину, можно сокращать до `decl`, `stmt` и `expr`.

Также по функциям, очень желательно не переносить уже существующие функции на новые места изменяя их при этом, делайте что-то одно, либо перенос, либо изменение (так удобнее читать). Запросы с переносом функций без изменений сильно проще принимать.

2021-06-29 22:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
>  }
Зачем? Это просто `vector_add(&enc->memory, 0)` (см. документацию). Вы же сделали двойной вызов, `vector_size` не `inline`!

2021-06-29 22:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +
Лишний отступ.

2021-06-29 22:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> + *	Export codes for virtual machine
`of`

2021-06-29 22:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> + *	Clear Code generator structure
Либо везде с большой, либо как в обычном предложении. Вы в инициализации уже написали с маленькой.

2021-06-29 22:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +/** Print table */
Если начали расписывать, то уж расписывайте полностью.

2021-06-29 22:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +static void emit_block(encoder *const enc, const node *const nd);
Почему их вдруг стало 3 вместо одной?

2021-06-29 22:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +		int was_operation = 1;
И почему вернули `int`?

2021-06-29 22:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	const node root = node_get_root(&sx->tree);
Отступ.

2021-06-29 22:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	const size_t items = node_get_amount(&root);
Это называется `amount`.

2021-06-29 22:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +		const node item = node_get_child(&root, i);
А неопределенные узлы мы называем `nd`. Должно быть однородно, если не знаете что в нем называйте по умолчанию.

2021-06-29 22:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	int ret = enc.was_error || enc_export(io, &enc);
Перенесите в самый конец, перед очисткой.

2021-06-30 09:15 UTC, bugdea1er commented on libs/compiler/codegen.c
> +static void emit_block(encoder *const enc, const node *const nd);
Сократил до двух - операторы и объявления расписаны на мелкие функции, которые в свою очередь вызывают и операторы, и объявления

2021-07-02 23:58 UTC, Victor-Y-Fadeev requested changes
- Указывайте условия явно!
- Создавайте переменные по месту использования
- Почему `compress_ident` посередине `statement` функций, а не вначале (вместе с функциями ввода/вывода)?

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	{
- Проверяйте лучше явно, все код вызовется тот же
- `stmt` можно опустить

```c
if (node_get_amount(nd) > 2)
{
	const node nd_else = node_get_child(nd, 2);
	...
}
```

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
>  	}
- `inition != initialization`, или можно оставить сокращение `init`
- Не приводите к `bool`, задайте явный признак:
```c
const bool has_init = node_get_arg(nd, 0) != 0;
```

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	const bool has_condition = (bool)node_get_arg(nd, 1);
Не приводите к `bool`, задайте явно.

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	const node nd_statement = node_get_child(nd, child_index + has_increment);
- Не приводите к `bool`, задайте явно
- C типом `bool` значения не складывают:
```c
child_index += has_increment ? 1 : 0;
const node nd_statement = node_get_child(nd, child_index);
```

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +		while (addr)
`addr` не `bool`, указывайте явно (признак конца станет понятнее и его будет легче отследить, если что-то поменяется).

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	(void)nd;
- И зачем тогда передаете узел?
- Разве потом что-то измениться?
- Может лучше тогда объединить такие функции в одну?

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	if (node_get_amount(nd))
Больше нуля! Задавайте условие, это не функции в духе `is_something`.

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +}
- Возможно их стоит объединить...
- Думаю такие функции точно `inline`

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +static void emit_printf_statement(virtual *const vm, const node *const nd)
`inline`

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	const node nd_decl_id = node_get_child(nd, bounds);
Создано не по месту использования!

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	mem_add(vm, proc_get(vm, (size_t)node_get_arg(&nd_decl_id, 4)));
Почему `process` тогда не оформили? Или хотя бы не подписали...

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	mem_add(vm, node_get_arg(&nd_decl_id, 6));
Подписи пропали...

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	const size_t num_proc = (size_t)node_get_arg(&nd_decl_end, 0);
А разве в шапке структуры эта информация не дублируется?

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	if (vm->addr_case)
Не ноль, вы же внизу присваиваете именно его. И кстати временами у вас строго больше, а тут просто не равно по сути!

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	if (vm->addr_case)
Не ноль... Или больше нуля?

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	for (size_t i = 0; i < amount; i++)
А последний не всегда будет `TEnd`?

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	emit_statement(vm, &nd_then_stmt);
`nd_then`

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	size_t child_index = 0;
Вот только он не `index`, а именно `statement`, так как предназначен для нахождения его индекса.

2021-07-02 23:58 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
>  }
Где инкрементация счетчика `max_threads`?

2021-07-03 00:46 UTC, bugdea1er commented on libs/compiler/codegen.c
> +	for (size_t i = 0; i < amount; i++)
Будет, но TEnd игнорируется, и с таким кодом можно будет просто незаметно убрать TEnd из компилятора, и никто не заметит

2021-07-03 00:47 UTC, bugdea1er commented on libs/compiler/codegen.c
> +	size_t child_index = 0;
Он используется для вычисления всех индексов, все потомки получаются с его помощью

2021-07-03 00:51 UTC, bugdea1er commented on libs/compiler/codegen.c
> +	(void)nd;
Зачем в объединять в одну? Если не считать (void)nd, то 2 из 3 строк различаются. При этом с помощью тернарного оператора не получится описать, потому что он вернет rvalue, то есть присваивать нельзя будет

2021-07-06 11:17 UTC, Victor-Y-Fadeev reviewed
- Уберите неиспользуемые параметры
- Добавьте комментарии там, где удалили переменные , я отмечал где, хотя бы так:
```c
mem_add(vm, proc_get(vm, (size_t)node_get_arg(&nd_decl_id, 4)));	// process
```

2021-07-06 11:17 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	vm->max_threads++;
Перенесите в конец функции, а не в начало.

2021-07-06 11:17 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	(void)nd;
Удалите `nd`, если не собираетесь его использовать в будущем.

2021-07-06 11:17 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	(void)nd;
Удалите `nd`, если не собираетесь его использовать в будущем.

2021-07-06 11:57 UTC, Victor-Y-Fadeev approved these changes

2021-07-06 11:57 UTC, merged