Перевод lvmopt на новое дерево и объявление структур
andrey-terekhov/RuC pull request #143
Opened 2021-06-24 12:47 UTC by IvanArkhipov1999

Сделан перевод llvmopt на версию 2.0.1. Также реализовано объявление структур, поля которых являются переменными типа int.

2021-06-24 14:59 UTC, bugdea1er requested changes

2021-06-24 14:59 UTC, bugdea1er commented on libs/compiler/llvmopt.c
> +
Лишний tab

2021-06-24 14:59 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +    	&& assignment_type != OP_ASSIGN_AT_R && assignment_type != OP_ASSIGN_AT_R_V)
Пробелы вместо tab

2021-06-24 14:59 UTC, bugdea1er commented on libs/compiler/llvmopt.c
> +static inline void struct_declaration(information *const info, size_t mode_ref)
Почему функция, которая пишет в выходные коды, находится в llvmopt, а не в генерации?
Если нужно заранее объявить все структуры, до кода программы, мб лучше печатать таблицу types особым образом?

2021-06-24 14:59 UTC, bugdea1er commented on libs/compiler/llvmopt.c
> +				uni_printf(info->io, "%si32", i == 0 ? "" : ", ");
Здесь тоже давайте пользоваться функцией печати типов, и печать разделяющей запятой лучше в отдельную строку вынести, чтобы удобнее читать было

2021-06-24 14:59 UTC, bugdea1er commented on libs/compiler/llvmopt.c
> +	const size_t n = (size_t)mode_get(info->sx, mode_ref + 2);
Лучше называть понятнее, например, `fields`, `members` или что-нибудь в таком духе

2021-06-24 14:59 UTC, bugdea1er commented on libs/compiler/llvmopt.c
> +#include <string.h>
Зачем порядок подключения снова поменяли? Сначала одноименный .h-файл, затем стандартные библиотеки, затем заголовки из проекта

2021-06-24 14:59 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +static bool is_double(const item_t operation)
Давайте такие функции перенесем в `operations.h`

2021-06-24 14:59 UTC, bugdea1er commented on libs/compiler/llvmgen.c
>  		return 1;
Отступ перед `return`

2021-06-24 14:59 UTC, bugdea1er commented on libs/compiler/llvmgen.c
>  						uni_printf(info->io, " %%var.%" PRIitem " = alloca double, align 4\n", displ);
Здесь тоже можно использовать ту же функцию печати типов, это единственное, что отличает объявление целых от вещественных. Тогда для скалярных типов все одинаково будет

2021-06-24 14:59 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +						uni_printf(info->io, " %%struct.%" PRIitem " = alloca %%struct_opt.%" PRIitem ", align 4\n"
Этот код тоже лучше вписать в `type_to_io`

2021-06-24 14:59 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +							, elem_type, elem_type);
Это же объявление экземпляра структуры, здесь точно не должно быть displ вместо одного из elem_type?

2021-06-24 15:02 UTC, bugdea1er requested changes
Давайте чаще использовать type_to_io и перенесем большие switch в `operations.h`

2021-06-25 08:52 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +static inline void struct_declaration(information *const info, size_t mode_ref)
Почему раньше не смущала печать строк в llvmopt?) Вообще, llvmopt создавался не только для перестановки узлов, а для печати перед непосредственно генерацией. Например, для тех же строк. Теперь ещё для структур понадобилось. Поясните про таблицу types, не очень понял

2021-06-25 09:02 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +				uni_printf(info->io, "%si32", i == 0 ? "" : ", ");
Да, было бы хорошо, вот только type_to_io находится в llvmgen. Дублировать не вариант, нужно перенести и сделать общей. Есть предложения, куда? Можно в llvmopt переместить для внешнего использования, интерфейс прописать в llvmopt.h. Что думаете?

2021-06-25 09:08 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +static bool is_double(const item_t operation)
Это планирую сделать в следующей pull request. Я составлю список подобных функций и выложу для обсуждения. Ну а пока будет идти обсуждение, текущий pull request разросся бы до больших размеров, поэтому и решил это перенести на следующий раз

2021-06-25 09:17 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
>  						uni_printf(info->io, " %%var.%" PRIitem " = alloca double, align 4\n", displ);
Не придумал, как красиво написать общее условие для скалярных типов. `elem_type < 0` мне кажется плохим вариантом из-за своей неочевидности, а `elem_type == mode_integer || elem_type == mode_float` какой-то громоздкий. Буду рад услышать ваши предложения!

2021-06-25 09:18 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +						uni_printf(info->io, " %%struct.%" PRIitem " = alloca %%struct_opt.%" PRIitem ", align 4\n"
Эм, а как? Я просто не представляю

2021-06-26 10:48 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +						uni_printf(info->io, " %%struct.%" PRIitem " = alloca %%struct_opt.%" PRIitem ", align 4\n"
Тут от типа зависит только имя переменной

```
if (elem_type == mode_integer || elem_type == mode_float)
{
	uni_printf(info->io, " %%var.");
}
else if (mode_is_struct(info->sx, elem_type))
{
	uni_printf(info->io, " %%struct.");
}

uni_printf(info->io, "%" PRIitem " = alloca ", displ);
type_to_io(info->io, elem_type);
uni_printf(info->io, ", align 4\n");
```

А в печати типов будет 
```
else if (mode_is_struct(type))
{
	uni_printf(io, "struct_opt.%" PRIitem, type);
}
```

2021-06-26 11:08 UTC, bugdea1er commented on libs/compiler/llvmgen.c
>  						uni_printf(info->io, " %%var.%" PRIitem " = alloca double, align 4\n", displ);
Сделаю функцию type_is_scalar

2021-06-28 10:16 UTC, bugdea1er approved these changes

2021-07-06 11:55 UTC, Victor-Y-Fadeev requested changes

2021-07-06 11:55 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +					node_swap(&child_to_swap1, &child_to_swap2);
- Пропущены `const`
- Цифры в названиях, тем более слитно мы не используем без необходимости (в документации `node_swap` у этих переменных есть нормальные имена)
```c
const node fst = node_get_child(nd, i - j);
const node snd = node_get_child(nd, i - j - 1);
node_swap(&fst, &snd);
```

2021-07-06 11:55 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +					node_swap(&child_to_swap1, &child_to_swap2);
```c
const node fst = node_get_child(nd, i - j);
const node snd = node_get_child(nd, i - j - 1);
node_swap(&fst, &snd);
```

2021-07-06 11:55 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +				nd_info.depth = 1;
Зачем поменяли на длинную запись?
```c
node_info nd_info = { &child, 1 };
```

2021-07-06 11:55 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +							node tmp = child;
Здесь должно быть `node_copy`, а у вас прямой доступ к полям!

2021-07-06 11:55 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +								node_set_next(&tmp);
Уверены что `node_set_next`? Обход в глубину умеет перескакивать, обратно по дереву, безопаснее будет использовать:
```c
tmp = node_get_child(&tmp, 0);
```

2021-07-06 11:55 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +							has_error |= transposition(&nd_info, &log_info1);
- Зачем вы ее вытащили из условного оператора (у вас нет использований снаружи)?
- Почему решили инициализировать по отдельности?

2021-07-06 11:55 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						node parent1 = node_get_parent(nd_info.ref_node);
Просто `parent`, у вас нет использований после (перезапишите).

2021-07-06 11:55 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						has_error |= transposition(second, &log_info1);
Верните как было, зачем это?

2021-07-06 11:55 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +							has_error |= transposition(second, &log_info2);
Не создавайте такие переменные снаружи, зачем?

2021-07-06 11:55 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						node parent2 = node_get_parent(second->ref_node);
Перезапишите существующую переменную.

2021-07-06 11:55 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			//	, надо подумать над этим потом (может общую функцию сделать?)
Запятые мы переносим только в коде, комментарии же - это текст и в нем работают обычные правила орфографии и пунктуации.

2021-07-06 11:55 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				: node_get_arg(nd, 1);
Условные выражения расписываются так:
```c
const item_t type = node_get_arg(nd, 1) > 0
			? mode_get(info->sx, (size_t)node_get_arg(nd, 1) + 1)
			: node_get_arg(nd, 1);
```

2021-07-06 11:55 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	for (size_t i = 0; i < modes_size; i++)
Слитно.

2021-07-06 11:55 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			const size_t fields_number = (size_t)mode_get(info->sx, i + 2);
Просто `fields`.

2021-07-06 12:52 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +				nd_info.depth = 1;
На windows server 2016 выдаётся следующее: `warning C4221: nonstandard extension used: 'ref_node': cannot be initialized using address of automatic variable 'child'`

2021-07-06 13:47 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +								node_set_next(&tmp);
Мне нужно посчитать ноды `TCall1` и `TCall2`, а если там есть аргументы, то такое не сработает. Ну вот например в таком дереве просто по потомкам не пройдёшься:
```
          tc 82) TCall1 2
            tc 84) TIdenttoval 4
              tc 86) TExprend
            tc 87) TIdenttoval 3
              tc 89) TExprend
            tc 90) TCall2 2
```
А если там аргументы ещё сложнее (типа вырезки из массива)? Поэтому я и решил сделать так.
P.S. Вообще, это тема будет подниматься в последующих запросах, когда будет реализовываться полноценный вызов функций с аргументами. Сейчас в этом запросе сделан вызов функции без аргументов, так что такое сработало бы, но с заделом на будущее оставил так.

2021-07-06 14:34 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +							has_error |= transposition(&nd_info, &log_info1);
Она используется после условного оператора, а вот переиспользовать -- это хорошая идея

2021-07-06 16:30 UTC, bugdea1er commented on libs/compiler/llvmopt.c
> +								node_set_next(&tmp);
Почему нельзя получить потомка узла TCall1 под номером `node_get_amount - 1`?

2021-07-07 08:39 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +								node_set_next(&tmp);
Как потомок под номером `node_get_amount - 1` поможет вычислить количество узлов между TCall1 и TCall2? Про вложенные вызовы замечание хорошее, решение фиксится, например, подсчётом узлов TCall1. Или можно отдельную функцию сделать для подсчёта узлов вызова функции, а при вложенных вызовах рекурсивно вызывать её.

2021-07-07 08:55 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +						has_error |= transposition(second, &log_info1);
Как было работает неправильно после рефакторинга, потребовалось сделать так

2021-07-07 08:58 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +						node parent2 = node_get_parent(second->ref_node);
Перезаписать в смысле `parent = node_get_parent(second->ref_node);`? Просто меня приучали для таких вещей использовать `node_copy`, но тут его никак не использовать

2021-07-08 20:44 UTC, Victor-Y-Fadeev requested changes

2021-07-08 20:44 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +				nd_info.depth = 1;
Допишите  `/wd4221` после ` /wd4204` в 19 строку корневого `CMakeLists.txt`.

2021-07-08 20:44 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						has_error |= transposition(second, &log_info_fst);
Итого должно быть так, у вас все равно было копирование, а так будет понятнее:
```c
node parent = node_get_parent(nd_info.ref_node);
if (node_get_type(&parent) == OP_ADDR_TO_VAL)
{
	node_info log_info = { &parent, 1 };
	has_error |= transposition(&nd_info, &log_info);
	node_copy(&nd_info, &log_info);
}

// перестановка со вторым операндом
has_error |= transposition(second, &nd_info);
```

2021-07-08 20:44 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						has_error |= transposition(first, &log_info_snd);
Аналогично предыдущему варианту.

2021-07-12 20:36 UTC, Victor-Y-Fadeev commented on CMakeLists.txt
> +	add_compile_options(-Werror=return-type -Wall -Wextra -Wno-implicit-fallthrough -Wno-unused-const-variable -std=c11
А вот это вот зачем?

2021-07-12 20:46 UTC, Victor-Y-Fadeev approved these changes

2021-07-12 20:50 UTC, merged