Инициализация таблицы идентификаторов
andrey-terekhov/RuC pull request #148
Opened 2021-07-07 15:25 UTC by bugdea1er

https://gitlab.softcom.su/ruc/ruc/-/issues/154

- Добавлен тип builtin_t
- Добавлена начальная инициализация таблицы идентификаторов
- Разбор встроенных функций производится как разбор пользовательской функции
- На этапе кодогенерации для встроенных функций подменяется инструкция

2021-07-07 18:37 UTC, 6easy9 requested changes
Поменять builtin_t built на builtin_t func

2021-07-07 18:37 UTC, 6easy9 commented on libs/compiler/syntax.c
> + *	args = list of characters each for one argument
Думаю, стоит порядок единообразный сделать: v, i, f, s, V, I, F, S, m, либо: v, V, i, I, f, F, s, S, m

2021-07-07 18:37 UTC, 6easy9 commented on libs/compiler/syntax.c
> +		switch (args[i])
Здесь тоже порядок сделать как в комментарии

2021-07-07 18:37 UTC, 6easy9 commented on libs/compiler/operations.h
> + *	@param	builtin	Function id
Стоит изменить название на func

2021-07-13 04:17 UTC, 6easy9 commented
Пока без замечаний

2021-07-13 04:17 UTC, 6easy9 approved these changes

2021-07-15 12:00 UTC, Victor-Y-Fadeev requested changes

2021-07-15 12:00 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	//node_copy(nd, &nd_next);
Это зачем?

2021-07-15 12:05 UTC, bugdea1er commented on libs/compiler/codes.c
>  		case OP_EXIT_DIRECT:
CREATE_DIRECT у нас оформлены как statement, ему соответствует EXIT_DIRECT;
EXIT - это функция, а [тут](https://gitlab.softcom.su/ruc/ruc/-/wikis/Описание-РуCи#пользовательские-функции-и-потоки) ошибка в описании

2021-07-15 12:05 UTC, bugdea1er commented on libs/compiler/parser_stmt.c
> +	const token_t end_token = (type == THREAD) ? TK_EXIT_DIRECT : TK_R_BRACE;
Ответил выше

2021-07-15 12:06 UTC, bugdea1er commented on libs/compiler/syntax.c
> +	repr_add_keyword(reprtab, U"upb", U"кол_во", TK_UPB);
Потому что она принимает аргумент типа массива, тип элемента которого не обозначен заранее. Это не может быть функцией в С, приходится его разбирать как оператор

2021-07-15 12:09 UTC, bugdea1er commented on libs/compiler/syntax.c
> +static item_t type_new_function(syntax *const sx, const item_t return_type, const char *const args)
Эта функция не может использоваться на этапе исполнения (то есть во время работы транслятора) из-за своей семантики. Многомерные массивы в стандартной библиотеке не появляются, поэтому смысла их предусматривать нет
Название вообще хотел бы type_function (как конструктор), но пока что так. В следующем реквесте константы перечисления types будут переименованы по стайлгайду, type_function освободится и станет названием жтой функции

2021-07-15 12:10 UTC, bugdea1er commented on libs/compiler/codegen.c
> -		case OP_CREATE:
Это две разные функции, одна из которых ушла в builtin_add, а другая - нет

2021-07-15 12:18 UTC, bugdea1er commented on libs/compiler/syntax.c
> +				local_modetab[3 + i] = (item_t)type_add(sx, (item_t[]){ type_pointer, (item_t)ref }, 2);
Да, давайте в следующем запросе сменим возвращаемый тип

2021-07-15 12:40 UTC, bugdea1er commented on libs/compiler/syntax.c
> +	}
Если не записывать первую букву отдельно, то сразу появляются ошибки

2021-07-15 18:45 UTC, Victor-Y-Fadeev approved these changes

2021-07-15 18:45 UTC, merged