Перевод llvmopt на стандартный стек
andrey-terekhov/RuC pull request #149
Opened 2021-07-14 12:16 UTC by IvanArkhipov1999

Теперь стек в llvmopt основан на стандартном стеке, а не на самодельном. По ходу реализации были ещё обнаружены ошибки в обработке ошибок работы со стеком в llvmopt. И исправлены.

2021-07-14 12:46 UTC, bugdea1er requested changes
1. У вас два поля типа `stack`, к которым обращаетесь всегда одновременно. Давайте сделаем из них одну структуру 
```c
struct { stack nodes; stack depths; }
```
и пропишем к ней необходимый интерфейс создания, и очистки памяти примерно как тут: https://github.com/andrey-terekhov/RuC/blob/9c003832889c0e770e38830957d14d28cfcb737b/libs/compiler/parser.h#L54

2. Стоит подумать над тем, чтобы node_info хранил не ссылку на ноду, а саму ноду. Довольно часто переменные node и node_info создаются парно, то есть такое изменение не намного больше памяти съест, но можно будет интерфейс функции `stack_pop_info` сократить до 
```c
static inline node_info stack_pop_info(information *const info)
```

3. Когда сделаете интерфейс для структуры стеков, уберите из названия `stack`. Достаточно будет `infos_push` или чего-то в таком духе (разумеется, зависит от того, как назовете структуру стека)

2021-07-14 12:46 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +#include "codes.h"
Зачем, если и без него компилируется?

2021-07-14 12:46 UTC, bugdea1er commented on libs/compiler/llvmopt.c
> +	return has_error;
Просто 
```c
return stack_push(&info->nodes, node_save(nd->ref_node))
	|| stack_push(&info->depths, nd->depth);
```

2021-07-14 12:46 UTC, bugdea1er commented on libs/compiler/llvmopt.c
> +		return operand;
Лучше не создавать локальную переменную, если есть возможность
```c
return (node_info){ NULL, (size_t) - 1 };
```
И по стайлгайду нужны пробелы внутри фигурных скобок

2021-07-14 12:46 UTC, bugdea1er commented on libs/compiler/llvmopt.c
> +	node_info operand = {memory, (size_t)operand_depth};
Здесь тоже пробелы внутри скобок нужны

2021-07-15 08:19 UTC, 6easy9 commented
Замечаний пока что нет

2021-07-16 10:48 UTC, bugdea1er requested changes

2021-07-16 10:48 UTC, bugdea1er commented on libs/compiler/llvmopt.c
> +	node ref_node;									/**< Узел */
Это теперь не ссылка на узел, давайте переименуем

2021-07-16 10:48 UTC, bugdea1er commented on libs/compiler/llvmopt.c
> +				node_info nd_info =  {child, 1};
Два пробела вместо одного, и пробелы внутри скобок

2021-07-16 10:53 UTC, bugdea1er approved these changes

2021-07-20 09:22 UTC, Victor-Y-Fadeev requested changes
- Удалите лишние структуры
- Создайте инициализатор и деинициализатор для глобальной структуры
- Используйте `has_error` по назначению (чтобы сократить количество условных операторов и размер кода, а не наоборот)
- Также нам нужно обсудить работу transposition, стоит переписать его, чтобы гарантировать сохранность исходных узлов, это упростит понимание кода!

2021-07-20 09:22 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +				node_info nd_info = { child, 1 };
Это больше не нужно.

2021-07-20 09:22 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						stack_info_push(info, &nd_info);
```c
stack_push(&info->nodes, (item_t)node_save(&child));
stack_push(&info->depths, 1);
```

2021-07-20 09:22 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						}
Зачем вы присваиваете значение в `has_error` когда собираетесь выходить? Это локальная переменная, она удалиться. И вообще мы создали ее, чтобы код был покороче, без таких `if`:
```c
item_t operand_depth = stack_pop(&info->depths);
has_error |= operand_depth == ITEM_MAX;
```

2021-07-20 09:22 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						node parent = node_get_parent(&nd_info.cur_node);
Зачем вообще так делать?
```c
node parent = node_get_parent(&child);
```

2021-07-20 09:22 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						has_error |= transposition(&operand, &nd_info);
```c
node operand = node_load(&info->sx->tree, (size_t)stack_pop(&info->nodes));
has_error |= transposition(&operand, operand_depth, &child, 1);
```

2021-07-20 09:22 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						has_error |= stack_info_push(info, &operand);
Либо везде проверяйте, либо оставьте как есть. Вряд ли `push` можно сломать...
```c
stack_push(&info->nodes, (item_t)node_save(&operand));
stack_push(&info->depths, operand_depth);
```

И вот тут важный вопрос, что в `operand` после `transposition`? Нужно ли его вообще снимать со стека или достаточно `peek`? проблема в том что вы делаете что-то неявное и непонятное в `transposition`, не гарантируя сохранность узлов, это нужно обсудить и совместно переписать его.

2021-07-20 09:22 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						has_error |= stack_info_push(info, &first);
Актуальны все те же самые комментарии, что и наверху.

2021-07-20 09:35 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +
Обращение к `nodes` и `depths` всегда происходит одновременно. Поэтому и хотелось создать структуру из двух стеков и прописать ей интерфейс работы как с одним стеком. Собственно, [вот](https://github.com/andrey-terekhov/RuC/pull/149#pullrequestreview-706207825).

2021-07-20 09:41 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +	}
Окей...
![Снимок экрана от 2021-07-20 12-37-10](https://user-images.githubusercontent.com/19683401/126300219-e1ffd67a-1e5c-4ca2-b2c5-3f577bcd24ae.png)

2021-07-20 09:45 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +	}
`info` нужен, чтобы не было конфликтов с названиями функций для стандартного стека. Конечно, `resize` для стандартного стека нет, но как-то странно, если остальные названия остальных функций в `llvmopt` будут иметь `info`, а `resize` не будет

2021-07-20 10:00 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
>  					info->slice_depth = 0;
Это единственное место, где ваше предложение целесообразно. В остальных местах придётся придётся 2 раза вызывать `stack_push` и `stack_pop`. Мне кажется, лучше всё-таки выделить такие пары вызовов в отдельные функции вместе с проверкой ошибок (как сейчас и сделано). При вызове двух функций есть вероятность забыть написать вызов и совершить ошибку, а вот вызов одной функции `stack_info_push` и `stack_info_pop` не позволит совершить такую ошибку.

2021-07-20 10:24 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +
`node_info` тоже нужна, так как работа с `cur_node` и `depth` происходит часто одновременно. Да и мне хотелось мыслить, что у меня имеется стек структур с прописанным интерфейсом

2021-07-20 10:29 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
>  }
Может стоит инициализировать структуру в `optimize_for_llvm`, чтобы было как в `llvmgen`?

2021-07-20 10:39 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +						}
Не, так не пойдёт, нужно сразу выходить. Иначе дальше будет перестановка с некорректной нодой, что приводит к timeout-ам. Но использование `has_error` у меня тут и правда странное.

2021-07-20 10:42 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +						node parent = node_get_parent(&nd_info.cur_node);
Я так делал скорее для читабельности, чтобы было понятно, что смотрим родителя ноды операции, но как-то не сильно увеличивается читабельность.

2021-07-20 11:57 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +						has_error |= stack_info_push(info, &operand);
`transposition` переставляет узлы, но оставляет ссылки в дереве неизменными, причем из-за перестановки ноды, на которые ссылаются ссылки, меняются. Приведу пример. Пусть имеет в дереве следующее выражение:
```
                        tc 137) TIdenttoval 3                              <-- first
                          tc 139) TIdenttoval 4                            <-- second
                            tc 141) +                                      <-- nd_info
```
Теперь вызываем `has_error |= transposition(&second, &nd_info);`. Получится следующее:
```
                        tc 137) TIdenttoval 3                              <-- first
                          tc 139) +                                        <-- second
                            tc 141) TIdenttoval 4                          <-- nd_info
```
`transposition` всегда так работала.

2021-07-20 12:13 UTC, IvanArkhipov1999 reviewed
Получилось как-то много вопросов, попробую подытожить мои вопросы и замечания:

- По поводу лишних структур. Обращение к `nodes` и `depths` всегда происходит одновременно. Поэтому и хотелось создать структуру из двух стеков и прописать ей интерфейс работы как с одним стеком. Собственно, [вот](https://github.com/andrey-terekhov/RuC/pull/149#pullrequestreview-706207825). `node_info` тоже нужна, так как работа с `cur_node` и `depth` происходит часто одновременно. Да и мне хотелось мыслить, что у меня имеется стек структур с прописанным интерфейсом. Мне кажется, лучше всё-таки выделить пары вызовов `stack_push` и `stack_pop` в отдельные функции вместе с проверкой ошибок (как сейчас и сделано). При вызове двух функций есть вероятность забыть написать вызов и совершить ошибку, а вот вызов одной функции `stack_info_push` и `stack_info_pop` не позволит совершить такую ошибку.

- Может стоит инициализировать структуру `info` в `optimize_for_llvm`, чтобы было как в [llvmgen](https://github.com/andrey-terekhov/RuC/blob/llvm/libs/compiler/llvmgen.c#L2037)?

- Работу transposition описал [здесь](https://github.com/andrey-terekhov/RuC/pull/149#discussion_r673055841). И есть ли смысл сейчас тратить время на обсуждение этой функции, когда на подходе новое дерево от Ильи, где перестановка узлов будет не нужна?

2021-07-20 12:37 UTC, Victor-Y-Fadeev commented
От структур стоит отказаться, так как они усложняют чтение (ненужные абстракции + увеличение количества нефункционального кода). Туда же входит и интерфейс, единственная нужная вам функция - это `stack_resize`. У вас всего 2 поля, оно того не стоит + можно будет снимать и класть значения ближе к месту использования, а вот чтоб ошибиться нужно постараться, так как проверить это очень просто (сумма операций снятия и возврата должна совпадать для обоих стеков).

Насчет `timeout`, вы забыли проверки `node_is_correct` в `transposition`, поэтому и не работает, если везде писать `if-return` это будет вообще невозможно читать.

Про `optimize_for_llvm` у меня скорее вопрос почему это до сих пор не сделано, инициализировать и очищать память лучше в одном месте, чем в 10.

По поводу `transposition`, вы уверен что она будет больше не нужна, логика ее работы не прозрачна, что взывает сложности в понимании остального кода, поэтому если она сохраниться, нужно будет переделать ее чтобы указатели не переставлялись.

2021-07-22 11:26 UTC, Victor-Y-Fadeev requested changes

2021-07-22 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
>  					info->slice_depth = 0;
Зачем вы записываете `SIZE_MAX`, вы выйдите из цикла `for` сразу же как измениться `has_error`.
Поэтому здесь достаточно этого, не усложняйте:
```c
has_error |= stack_pop(&info->depths) == ITEM_MAX;
stack_push(&info->depths, info->slice_depth);
info->slice_depth = 0;
```

2021-07-22 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						has_error |= stack_push(&info->depths, 1);
Не думаю что здесь вообще нужна проверка... И вы забыли приведение к `item_t`.

2021-07-22 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						}
Вам эта проверка не нужна, так как `stack_pop` в случае ошибки вернет `ITEM_MAX` который сломает ноду при попытке восстановления и ошибка перехватится в `transposition`. Здесь достаточно написать:
```c
item_t operand_depth = stack_pop(&info->depths);
has_error |= operand_depth == ITEM_MAX;
```

P.s. Приведение типа делайте в вызове `transposition`.
P.p.s. В принципе если стеки всегда равны проверка здесь не нужна, достаточно будет проверки из `transposition`.

2021-07-22 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						has_error |= stack_push(&info->depths, operand_depth);
Опять эти проверки не нужны. И опять пропустили приведение к `item_t`.

2021-07-22 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						operand_depth++;
Создавайте переменные по месту использования:
```c
node operand = node_load(&info->sx->tree, (size_t)stack_pop(&info->nodes));
has_error |= transposition(&operand, operand_depth, &child, 1);
operand_depth++;
```

P.s. Также если хочется подчеркнуть тип `node`, то это делается **префиксом** `nd`.

2021-07-22 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +static int transposition(node *const expr_node, const size_t expr_depth, node *const cur_node, const size_t cur_depth)
Уберите постфикс `node`.

2021-07-22 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +		|| expr_depth == SIZE_MAX || cur_depth == SIZE_MAX)
Проверка `depth` не нужна.

2021-07-22 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +
Лишний отступ.

2021-07-22 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						has_error |= stack_push(&info->depths, first_depth);
Опять эти проверки не нужны. И опять пропустили приведение к `item_t`.

2021-07-22 11:26 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						first_depth += second_depth;
Применяем все те же комментарии, что и наверху.

2021-07-22 13:19 UTC, Victor-Y-Fadeev requested changes

2021-07-22 13:19 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						const item_t index = stack_pop(&info->nodes);
Зачем, вам эта переменная не нужна, снимите значение по месту использования.

2021-07-22 13:19 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						has_error |= first_depth == ITEM_MAX;
Лишние переменные, берите значение по месту использования.
И зачем 2 проверки ошибок? Должно быть:
```c
item_t second_depth = stack_pop(&info->depths);
item_t first_depth = stack_pop(&info->depths);
has_error |= first_depth == ITEM_MAX || second_depth == ITEM_MAX;
// OR
item_t second_depth = stack_pop(&info->depths);
item_t first_depth = stack_pop(&info->depths);
has_error |= first_depth == ITEM_MAX;
```

P.s. Второй вариант возможен так как, если ошибка была, то обязательно повториться при следующем снятии.

2021-07-22 13:19 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						node second_node = node_load(&info->sx->tree, (size_t)second_index);
Я только что просил не использовать `_node` и вот опять...

2021-07-22 13:19 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						node first_node = node_load(&info->sx->tree, (size_t)first_index);
`_node` не должно быть!

2021-07-22 13:19 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +static int transposition(node *const expr, const size_t expr_depth, node *const cur)
При таком раскладе нужно поменять параметры, так как узлы должны быть рядом:
```c
static int transposition(node *const current, node *const expr, const size_t expr_depth)
```

2021-07-22 13:42 UTC, Victor-Y-Fadeev approved these changes

2021-07-22 13:44 UTC, merged