Перестроение дерева выражений
andrey-terekhov/RuC pull request #152
Opened 2021-07-19 11:18 UTC by bugdea1er

https://gitlab.softcom.su/ruc/ruc/-/issues/89 и https://gitlab.softcom.su/ruc/ruc/-/issues/91

- Вид дерева выражений изменен на предложенный в [#89](https://gitlab.softcom.su/ruc/ruc/-/issues/89)
- Выдача семантических ошибок теперь происходит отдельной функцией semantics_error, которая принимает в качестве аргумента положение в коде, чтобы точнее указывать на ошибку
- Функционал парсинга отделен от функционала проверок семантики и построения дерева
- was_error и io перенесены в syntax
- nd перенесен в syntax, но это временное решение (он будет перенесен в структуру AST, когда она будет создана)
- Добавлены все пропущенные ранее семантические проверки в выражения

2021-07-19 16:07 UTC, 6easy9 requested changes
Нужно продумать единый префикс для функций в библиотеке AST. Возможно, следует поменять название библиотеки

2021-07-21 03:38 UTC, 6easy9 approved these changes

2021-07-21 11:02 UTC, Victor-Y-Fadeev requested changes
`builder.h`, `builder.c` и `parser_expr.c` проверю позже. Глобально:
- `=` в `codes.c` у аргументов это плохо
- В `lexer.c` вы не очистили память, такие ошибки недопустимы!
- Cтруктуры мы передаем по указателю и не приписываем `_t`
- `expression_list` - это совсем плохо, особенно с учетом того, что вы ее копируете, это долго! С этим точно нужно что-то думать и менять, как есть не пойдет!
- `location_t` - мне не очень понятно для чего вы ее используете, сохраненная позиция `io` вам не сильно поможет с символом в строке

2021-07-21 11:26 UTC, bugdea1er commented on libs/compiler/builder.h
> +	expression expressions[128];
Я б с радостью сделал это с помощью 4х векторов, но ведь это использование динамической памяти, которое запрещено у нас в проекте.
Такие списки выражений могут быть вложенными, так что выделить один раз на всю программу не пойдет

2021-07-22 22:18 UTC, bugdea1er commented on libs/compiler/tokens.h
> -
Зачем, если они уже не нужны?

2021-07-22 22:18 UTC, bugdea1er commented on libs/compiler/codes.c
>  			break;
Внизу инструкция, а не узел

2021-07-22 22:18 UTC, bugdea1er commented on libs/compiler/syntax.h
> +
Надо будет перенести в будущий интерфейс ошибок

2021-07-22 22:20 UTC, bugdea1er commented on libs/compiler/lexer.c
> -	lxr->num = (int)length;
Длина теперь в векторе лежит

2021-07-24 21:14 UTC, Victor-Y-Fadeev requested changes
1. Из 44 комментариев, вы проигнорировали и не исправили 19! Это вообще не дело, будьте внимательнее и пользуйтесь поиском по всем файлам для устранения глобальных замечаний.
2. Удалите тип `expression`, он вам вообще не нужен! Достаточно обычного `node`. Подсказка, чтобы сломать `node` достаточно:
```c
node nd_broken = node_load(NULL, SIZE_MAX);
```
3. Что происходит с отступами и блоками, у вас в 3 файлах одна и та же болезнь, а именно двойной отступ после `extern` и всего один после блока функций. Также вы копируете структуры, вместо использования указателей.
4. Откуда взялось `is_valid`, когда у нас везде `is_correct`, должно быть однородно.

2021-07-24 21:14 UTC, Victor-Y-Fadeev commented on libs/compiler/expression.c
> +   return (location){ (size_t)node_get_arg(&expr.nd, 2), (size_t)node_get_arg(&expr.nd, 3) };
Думаю нужно возвращать последние два аргумента, а не 2 и 3, что если количество аргументов измениться или будет другим.

2021-07-24 21:14 UTC, Victor-Y-Fadeev commented on libs/compiler/expression.c
> +   return node_get_arg(&expr.nd, 1) == LVALUE;
Почему именно `1`?

2021-07-24 21:14 UTC, Victor-Y-Fadeev commented on libs/compiler/expression.c
> +}
Такие функции называются `is_correct`...

2021-07-24 21:14 UTC, Victor-Y-Fadeev commented on libs/compiler/expression.c
> +expression expression_create(const node expr)
Нельзя принимать не по указателю.

2021-07-26 17:22 UTC, bugdea1er commented on libs/compiler/codes.c
> +					sprintf(buffer, "CALL");
Эти штуки относятся не к узлам, а к инструкциям
<img width="282" alt="image" src="https://user-images.githubusercontent.com/19926617/127031756-b3c57cef-f82e-4e89-bd4c-84f7f844fbf7.png">
P.S. Я давно говорил, что надо бы разнести печать дерева и печать файла, чтобы таких вопросов не возникало

2021-07-26 17:24 UTC, bugdea1er commented on libs/compiler/expression.c
> +   return (location){ (size_t)node_get_arg(&expr.nd, 2), (size_t)node_get_arg(&expr.nd, 3) };
Положение в коде всегда ставится на место аргументов с индексами 2 и 3, все остальное - после них

2021-07-26 17:24 UTC, bugdea1er commented on libs/compiler/expression.c
> +   return node_get_arg(&expr.nd, 1) == LVALUE;
Там эта информация и записана

2021-07-27 19:42 UTC, Victor-Y-Fadeev requested changes
- Библиотеку выражений нужно удалить
- У вас список нод никак не связан с выражениями, удалите из названия
- Аргументы местоположения сделайте последними

...

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.h
> + *	@param	inits			List of initializers
Лучше просто `list`.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.h
> +							, const unary_t op_kind, const location op_loc);
Один отступ...

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.h
> +							 , const binary_t op_kind, const location op_loc);
Один отступ...

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.h
> +							  , const node *const nd_right, const location op_loc);
Один отступ...

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.h
> +								, const location l_loc, const location r_loc);
Один отступ...

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +}
Стоит сделать их `inline`.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +	in_set_position(sx->io, prev_loc);
Точно стоит поменять их местами, так как у вас разные "уровни вложенности" для них.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +}
В конец файла.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +	memcpy(&temp, &value, sizeof(double));
Вы в курсе что это не так работает? А на win32 вообще упадет.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +	for (size_t i = 0, length = vector_size(value); i < length; i++)
Отступ и заведите снаружи.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +								, const location l_loc, const location r_loc)
Уже писал.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +static void semantics_error(syntax *const sx, const location loc, error_t num, ...)
`semantic_error`

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +	node_add_arg(&nd, (item_t)loc.end);			// Конечная позиция идентификатора
**Я уже просил сделать их последними двумя аргументами для всех узлов!** Эти аргументы вспомогательные и им не место в середине списка, кодогенераторам о них во время разбора тоже не стоит задумываться. Особенно если потом добавится еще один какой-нибудь.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +						   , const location l_loc, const location r_loc)
Один TAB.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +							 , const location op_loc, const location id_loc)
Один TAB.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +							 , const binary_t op_kind, const location op_loc)
Один TAB.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +							  , const node *const nd_right, const location op_loc)
Один TAB.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +								, const location l_loc, const location r_loc)
Один TAB.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +	const size_t actual_args = args == NULL ? 0 : expression_list_size(args);
В таких случаях лучше на сравнивать на неравенство, так код ошибки будет в конце.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +	size_t ref_arg_type = (size_t)operand_type + 3;
Почему не `const`?

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +			// fallthrough;
Он не так оформляется, либо как выглядел бы код, либо как человеческий текст.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +		}
`break` должен быть снаружи.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +		&& (!expression_is_lvalue(nd_left) || (type_is_floating(right_type) && type_is_integer(left_type))))
Поменяйте условия местами, лучше будет смотреться.

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +		// Несовпадение типов может быть только в случае, когда слева floating, а справа integer
"вещественный" и "целочисленный"...

2021-07-27 19:42 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +				break;
`break` должен быть снаружи, проверьте и исправьте везде.

2021-07-27 21:42 UTC, bugdea1er commented on libs/compiler/builder.h
> + *	@param	nd_callee			Callee expression
А чем callee не нравится? 
Вызываемое выражение

2021-07-27 21:43 UTC, bugdea1er commented on libs/compiler/builder.h
> + *	@param	nd_base			First operand of member expression
Второй операнд - идентификатор

2021-07-27 21:47 UTC, bugdea1er commented on libs/compiler/builder.c
> +	node_add_arg(&nd, (item_t)loc.end);			// Конечная позиция идентификатора
Так наоборот, чтобы не задумываться о том, где что лежит, нужно сначала ставить общие для всех узлов аргументы, а потом - частные случаи
Тогда для любого узла тип будет лежать в аргументе с индексом 0, категория - 1, начало - 2 и конец - 3
Вместо этого вы предлагаете каждый раз в функции получения положения смотреть на то, какой вид узла пришёл? Это куча лишних операций и совсем непонятно, зачем это нужно

2021-07-27 21:48 UTC, bugdea1er commented on libs/compiler/builder.c
> +			// fallthrough;
Вполне выглядит как код, это ж ключевое слово из c2a

2021-07-27 21:49 UTC, bugdea1er commented on libs/compiler/builder.c
> +		&& (!expression_is_lvalue(nd_left) || (type_is_floating(right_type) && type_is_integer(left_type))))
Но ведь проверить, является ли оператор присваивающим, проще, и лучше это делать в первую очередь?

2021-07-27 21:53 UTC, bugdea1er commented on libs/compiler/builder.h
> + *	@param	is_arrow		Set if operator is arrow
is_arrow - какой оператор был между первым операндом и вторым
Указатель это или нет, уже решается внутри

2021-07-27 21:53 UTC, bugdea1er commented on libs/compiler/builder.h
> + *	@param	name			Second operand of member expression
Почему вторым операндом не может быть идентификатор? Просто передается он не узлом, а по имени

2021-07-27 21:55 UTC, bugdea1er commented on libs/compiler/builder.h
> + *	@param	nd_array		Second operand of upb expression
Вот как раз снаружи мы передаём что было первым, а что - вторым, а задача строителя уже проверить, правда ли это массив и номер размерности

2021-07-27 21:56 UTC, bugdea1er commented on libs/compiler/builder.c
> +	node_add_arg(&nd, (item_t)loc.end);			// Конечная позиция идентификатора
Собственно, для того, чтобы любому читателю дерева не надо было задумываться о том, что где лежит, и предлагался интерфейс для чтения дерева

2021-07-27 22:09 UTC, bugdea1er commented on libs/compiler/expression_list.h
> +int expression_list_clear(expression_list *exprs);
Без void в объявлении предупреждение
<img width="442" alt="image" src="https://user-images.githubusercontent.com/19926617/127233954-1e046c33-8e35-4734-a143-235cc6c7c33d.png">

2021-07-27 22:13 UTC, bugdea1er commented on libs/compiler/expression_list.c
> +	return (expression_list){ .nodes = vector_create(12) };
А надо ли ее в header, если она используется только в одной функции?

2021-07-27 22:14 UTC, bugdea1er commented on libs/compiler/expression_list.c
> +	return (expression_list){ .nodes = vector_create(12) };
В функции вряд ли будет больше 12 параметров, большие структуры обычно не списком инициализируют, а через присваивания в поля

2021-07-27 22:23 UTC, bugdea1er commented on libs/compiler/expression.h
> +location expression_get_location(const node *const nd_expr);
Они также будут использоваться и при чтении дерева в кодогенераторе, а подключать строителя в кодген как-то странно

2021-07-27 22:31 UTC, bugdea1er commented on libs/compiler/builder.h
> +node node_broken(void);
А когда нужно будет вернуть невалдиный statement, отдельную функцию `build_broken_statement()` сделаем?

2021-07-27 22:34 UTC, bugdea1er commented on libs/compiler/builder.h
> + *	@param	name			Identifier name
Здесь уже задел на будущее: хочется вынести половину syntax в отдельную структуру identifiers_table, для которой уже нельзя будет говорить `Index of record in representations table`, потому что таблица representations будет спрятана

2021-07-27 22:40 UTC, bugdea1er commented on libs/compiler/builder.c
> +	in_set_position(sx->io, prev_loc);
Тогда лучше сначала поставить позицию, а потом объявлять `va_list args;`

2021-07-28 16:48 UTC, Victor-Y-Fadeev commented on libs/compiler/expression.h
> +location expression_get_location(const node *const nd_expr);
Перенесите тогда в `syntax.h` пока и вы же собирались создавать разборщика, а 3 функции на слишком специфический файл малова-то.

2021-07-28 16:49 UTC, Victor-Y-Fadeev commented on libs/compiler/expression_list.h
> +int expression_list_clear(expression_list *exprs);
У нас уже есть функции без параметров без `void` и никаких проблем, если исправлять то везде и не сейчас.

2021-07-28 16:52 UTC, Victor-Y-Fadeev commented on libs/compiler/expression_list.c
> +	return (expression_list){ .nodes = vector_create(12) };
- Да надо, чтобы при желании ее было удобно увеличить, а не бегать по всему файлу.
- Эмм, а раньше вы 128 размер задавали, странновато, сделайте хотя бы 16 (будет степень двойки для красоты)

2021-07-28 16:53 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.h
> +node node_broken(void);
1. У вас сейчас такая потребность есть?
2. Когда возникнет -> переименуем в `build_broken_node`

2021-07-28 16:54 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.h
> + *	@param	name			Identifier name
Делать нечитаемую документацию на будущее плохая затея. Документация должна соответствовать текущей действительности, а не тому как будет когда-то. Когда будете переделывать `syntax`, тогда и поправите.

2021-07-28 16:57 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.h
> + *	@param	nd_callee			Callee expression
Тем что вообще не понятно, что вы хотите этим сказать:
- Это само выражение начинающееся на `CALL`?
- Это то что идет после него?
- Это то что будет вызвано?

Должно быть однозначнее.

2021-07-28 17:00 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.h
> + *	@param	is_arrow		Set if operator is arrow
Тогда почему `arrow`? Указатель - это `pointer`, а `arrow` - это вот такая стрелка `->`. Если вы про нее, то добавьте ее символ в кавычках перед `arrow`.

2021-07-28 17:01 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.h
> + *	@param	nd_base			First operand of member expression
Тогда почему они так далеко друг от друга в параметрах?

2021-07-28 17:02 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.h
> + *	@param	name			Second operand of member expression
Это не отменяет факта некорректной документации, названия и расположения. Они должны быть рядом и похожи друг на друга названиями, а у вас и названия никак не связаны и типы разные.

2021-07-28 17:04 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.h
> + *	@param	nd_array		Second operand of upb expression
Я между прочим ровно это и сказал, "снаружи должен быть обработан только порядок, а содержимое внутри". Переименуйте в `nd_fst` и `nd_snd`.

2021-07-28 17:06 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +	in_set_position(sx->io, prev_loc);
Работа с `va_list` должна быть внешней, так как ошибка в ней критическая. Должно быть четко видно что параметры обработаны правильно, так как их использование в принципе не самая лучшая затея, но по другому никак.

2021-07-28 17:10 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +	node_add_arg(&nd, (item_t)loc.end);			// Конечная позиция идентификатора
Собственно в интерфейсе вам надо просто спросить количество параметров и взять два последних. У вас есть узлы не хранящие позицию и не имеющие первых двух полей, поэтому вначале должны быть данные непосредственно про узел и в конце вспомогательная информация. Если количество вспомогательной информации измениться вам придется все кодогенераторы править! Используйте `node_get_argc` в своем интерфейсе, вам не нужно знать тип узла, чтобы взять два последних аргумента.

2021-07-28 17:34 UTC, bugdea1er commented on libs/compiler/builder.h
> + *	@param	name			Second operand of member expression
А что вы от меня хотите? По определению два операнда имеют разные виды
<img width="850" alt="image" src="https://user-images.githubusercontent.com/19926617/127369685-5cddbb12-d0c6-4c41-8e3d-8d22c61de004.png">

2021-07-29 07:26 UTC, Victor-Y-Fadeev requested changes
Осталось чуть-чуть... Кстати, что такое `LHS` и `RHS`? Может стоит переименовать?

2021-07-29 07:26 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.h
> +#include "operations.h"
`#include` по середине файла не должно быть!

2021-07-29 07:26 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.h
> +}
А вот эти параметры вроде не вспомогательные, а обязательные, поэтому их стоит оставить как были.

2021-07-29 07:26 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +extern location expression_get_location(const node *const nd);
Такие штуки, так же как и декларации должны быть в начале файла.

2021-07-29 07:26 UTC, Victor-Y-Fadeev commented on libs/utils/node_vector.h
> +
Один отступ после `extern "C" {`, **ОДИН**! Я уже раз 10 написал об этом.

2021-07-29 07:26 UTC, Victor-Y-Fadeev commented on libs/utils/node_vector.h
> +EXPORTED int node_vector_clear(node_vector *const vec);
Зачем вы дописали `EXPORTED`? Он здесь не нужен.

2021-07-29 07:26 UTC, Victor-Y-Fadeev commented on libs/utils/node_vector.c
> +}
`inline` так работать не будет, вы должны написать эти функции в header, а здесь только `export` поставить (смотрите `stack.h`). Блок `export`-функций имеет по 2 отступа с каждой стороны, идет после констант.

2021-07-29 07:26 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.h
> + *	@param	nd_fn			Called function
`nd_func`.

2021-07-29 07:26 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
>  		}
Либо `node_copy`, либо:
```c
return is_binary
	? build_binary_expression(prs->sx, LHS, &RHS, token_to_binary(op_token), op_loc)
	: build_ternary_expression(prs->sx, LHS, &middle, &RHS, op_loc);
```

2021-07-29 08:21 UTC, bugdea1er commented on libs/compiler/syntax.h
> +}
Я не понимаю, а что такое обязательные параметры, а что такое вспомогательные?

2021-07-29 11:45 UTC, Victor-Y-Fadeev approved these changes

2021-07-29 11:45 UTC, merged