Интерфейс для работы с файлами
andrey-terekhov/RuC pull request #153
Opened 2021-07-20 22:04 UTC by bugdea1er

https://gitlab.softcom.su/ruc/ruc/-/issues/95

2021-07-24 21:48 UTC, Victor-Y-Fadeev requested changes
И как виртуальная машина отнеслась к указателям? Как их вообще обрабатывать в ней?

2021-07-24 21:48 UTC, Victor-Y-Fadeev commented on libs/compiler/errors.c
> +			sprintf(msg, "эта функция не поддерживается в RuC-VM");
Не стоит использовать сокращения, тем более английские, в сообщениях: `"... не поддерживается виртуальной машиной РуСи"`.

2021-07-24 21:48 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.c
> +		if (strcmp(flag, "-LLVM") == 0)
А если `MIPS`?

2021-07-24 21:48 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		}
А вот эту ошибку хочется словить из кодогенератора, там она стандартная и функция у нас будет не одна. Тогда не понадобиться распознавать платформу. Нужно только читаемо вывести имя функции в ошибке, указывать место не обязательно.

2021-07-24 21:48 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +	builtin_add(sx, U"fputc", U"фписать", type_function(sx, TYPE_CHARACTER, "iP"));
Надо бы как-то по другому назвать... Может `"фчитать_символ"` и `"фписать_символ"`?

2021-07-24 21:48 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> + *		P -> FILE*
Почему именно `P`? Откуда это?

2021-07-26 15:47 UTC, bugdea1er commented on libs/compiler/syntax.c
> + *		P -> FILE*
Честно говоря, уже и не помню, откуда взялась P
F уже занято, и хотелось бы оставить его для floating типов

2021-07-27 13:52 UTC, Victor-Y-Fadeev requested changes

2021-07-27 13:52 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.c
> +#include <string.h>
Удалить.

2021-07-27 13:52 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +				error(NULL, wrong_func_for_vm);
Очень странно получить ошибку вида:
```
ruc: ошибка: эта функция не поддерживается виртуальной машиной РуСи
```

Какая функция... Сделайте лучше стандартную (по крайней мере до исправления):
```c
system_error(node_unexpected, operation);
```

2021-07-28 00:23 UTC, Victor-Y-Fadeev approved these changes

2021-07-28 00:25 UTC, Victor-Y-Fadeev commented on libs/compiler/errors.c
> +			break;
Откатите.

2021-07-28 00:25 UTC, Victor-Y-Fadeev commented on libs/compiler/errors.h
> +	wrong_func_for_vm,
Откатите.

2021-07-28 00:35 UTC, merged