Develop
andrey-terekhov/RuC pull request #154
Opened 2021-07-22 09:55 UTC by Ri7ay

2021-07-22 10:52 UTC, Victor-Y-Fadeev requested changes
У вас не проходят тесты, пока сборка не будет проходить я не смогу ее принять. Отправляйте на ревью рабочий код! Также не должно быть предупреждений компилятора.

По поводу функциональности - не добавлено ни одного теста подтверждающего работу `typedef`. Добавьте базовые тесты на переименование (в `./tests/executable/typedef`):
- Стандартных типов
- Структур:
  - Использование без ключевого слова
  - Задание другого имени
- Повторное переименование типа (относительно нового имени)
- Создание массива из элементов переименованного типа

2021-07-22 10:52 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +			item_t type = parse_type_specifier(prs, parent);
Нету `const`.

2021-07-22 10:52 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +			to_identab(prs, repr, 1000, type);
Магическое число, что это значит?

2021-07-23 08:59 UTC, Ri7ay commented on libs/compiler/parser_decl.c
> +			to_identab(prs, repr, 1000, type);
Для входа в этот if, по аналогии с struct
```
else if (kind >= 1000)
{
	// Это описание типа, а (type-1000) – это номер инициирующей процедуры
	ident_set_displ(sx, last_id, kind);
}
```
```
if (prs->token == TK_L_BRACE)
{
	const item_t type = parse_struct_declaration_list(prs, parent);
	const size_t id = to_identab(prs, repr, 1000, type);
	ident_set_displ(prs->sx, id, 1000 + prs->flag_array_in_struct);
	prs->was_type_def = true;

	return ident_get_type(prs->sx, id);
}
```

2021-07-24 11:12 UTC, bugdea1er requested changes
У вас не отлавливаются ошибки в определении типа, поэтому я и просил тесты на ошибки

2021-07-24 11:12 UTC, bugdea1er commented on libs/compiler/parser_decl.c
> +			const item_t type = parse_type_specifier(prs, parent);
1. Вы не проверяете, что разбор спецификатора типа прошел успешно. Там может быть ошибка, нужно проверить, что все прошло правильно (т.е. `!type_is_undefined(type))`, а в случае ошибки - восстановиться (делается это с помощью `token_skip_until()`)

2021-07-24 11:12 UTC, bugdea1er commented on libs/compiler/parser_decl.c
> +			const size_t repr = prs->lxr->repr;
2. Вы не проверяете, что после спецификатора типа стоит идентификатор, но при этом используете поле `lxr->repr`. Опять же, там может быть ошибка, вместо идентификатора может стоять что угодно, нужно проверить и восстановиться в случае ошибки.

2021-07-24 11:12 UTC, bugdea1er commented on libs/compiler/parser_decl.c
> +			prs->was_type_def = true;
3. Вы не требуете после объявления `;`. Определение типа является полноценным объявлением, после которого должна идти `;`.  Флаг `was_type_def` используется для случаев, когда спецификатор типа может быть сам по себе объявлением, например, структура или перечисление не обязаны объявлять представителей этого типа в той же строке (но при этом могут!). Возможно, не стоит разбирать объявление типа как спецификатор типа, чтобы запретить дальнейшие объявления в этой же строке.

2021-07-24 11:57 UTC, Victor-Y-Fadeev approved these changes

2021-07-26 20:12 UTC, bugdea1er requested changes

2021-07-26 20:12 UTC, bugdea1er commented on libs/compiler/parser_decl.c
> +				token_skip_until(prs, TK_COMMA);
До `;` лучше восстанавливаться, `TK_SEMICOLON`

2021-07-26 20:12 UTC, bugdea1er commented on libs/compiler/parser_decl.c
> +					parser_error(prs, expected_semi_after_stmt);
`expected_semi_after_decl`

2021-07-26 20:12 UTC, bugdea1er commented on libs/compiler/parser_decl.c
> +				token_skip_until(prs, TK_COMMA);
1. Восстановиться тоже до `TK_SEMICOLON`
2. Надо какую-нибудь ошибку кинуть, типа `typedef requires a name`

2021-07-27 19:43 UTC, merged