Вызов функций
andrey-terekhov/RuC pull request #155
Opened 2021-07-22 14:39 UTC by IvanArkhipov1999

Исправлены ошибки вызова функций без параметров, реализован вызов функций с параметрами. Пока что аргументом функции может быть только арифметическое выражение.

2021-07-22 19:28 UTC, 6easy9 requested changes

2021-07-22 19:28 UTC, 6easy9 commented on libs/compiler/llvmgen.c
> +				// ACONST
Перенести на следующею строку

2021-07-22 19:28 UTC, 6easy9 commented on libs/compiler/llvmgen.c
> +				// ACONST
Перенести ниже

2021-07-23 11:52 UTC, bugdea1er requested changes
Путаете аргументы и параметры
Аргументы - выражения в вызове функции
Параметры - идентификаторы в описании функции

2021-07-23 11:52 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +			item_t parameters_value_type[128];
Это должно называться аргументами

2021-07-23 12:10 UTC, bugdea1er approved these changes

2021-07-23 23:16 UTC, 6easy9 approved these changes

2021-07-24 11:55 UTC, merged