Инициализация одномерных массивов
andrey-terekhov/RuC pull request #161
Opened 2021-07-28 10:45 UTC by IvanArkhipov1999

Пока реализовано без инициализации массива строкой. Смотреть только llvmopt и llvmgen, остальное было смёржено из master.

2021-07-28 18:44 UTC, bugdea1er requested changes

2021-07-28 18:44 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +				const bool is_borders = node_get_type(nd) != OP_DECL_ID;
`has_bounds`, наверное, лучше будет тут смотреться

2021-07-28 18:44 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +				const item_t all = node_get_arg(&id, 3);	// 0 если нет инициализации
Если тут только два значения могут быть, то лучше тип `bool`, иначе распишите комментарий подробнее

2021-07-28 18:44 UTC, bugdea1er commented on libs/compiler/llvmopt.c
> +			, info->arr_init_type == mode_integer ? "i32" : "double");
Используйте функцию для проверки типа

2021-07-29 07:54 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +			, info->arr_init_type == mode_integer ? "i32" : "double");
Хорошо бы перенести функции mode_is из парсера куда-нибудь. А то `#include "parser.h"` странно смотрится в llvmopt и llvmgen.

2021-07-29 08:10 UTC, bugdea1er approved these changes

2021-07-30 14:15 UTC, 6easy9 requested changes
Откуда изменения в папке utils?

2021-07-30 14:15 UTC, 6easy9 commented on libs/compiler/llvmopt.c
> +			break;
Нужен tab

2021-07-30 14:15 UTC, 6easy9 commented on libs/utils/hash.c
> +static size_t get_index(const hash *const hs, const item_t key)
Почему изменения в utils?

2021-08-02 08:23 UTC, IvanArkhipov1999 commented on libs/utils/hash.c
> +static size_t get_index(const hash *const hs, const item_t key)
Там была ошибка, Виктор её исправил, я подтянул изменения из master.

2021-08-02 09:17 UTC, 6easy9 approved these changes

2021-08-02 13:19 UTC, merged