Интерфейс чтения типов
andrey-terekhov/RuC pull request #163
Opened 2021-07-31 14:01 UTC by bugdea1er

https://gitlab.softcom.su/ruc/ruc/-/issues/174

- Реализован интерфейс чтения типов
- Новый интерфейс используется в builder.c

2021-08-02 09:31 UTC, 6easy9 requested changes
В syntax.h следует подключить библиотеку item.h, отключить ее из c-файла и отключить стандартные библиотеки, которые подключаются в item.h.
Комментарии относятся ко всем функциям.

2021-08-02 09:31 UTC, 6easy9 commented on libs/compiler/syntax.h
> + *	Get parameter type by its index
Обычно пишем просто "by index"

2021-08-02 09:31 UTC, 6easy9 commented on libs/compiler/syntax.h
> + *	@return	Structure name, @c SIZE_MAX on failure
Разве не корректнее вместе member использовать field?

2021-08-02 09:31 UTC, 6easy9 commented on libs/compiler/syntax.h
> + *	@param	structure	Structure type
Можно заменить structure и function на type - будет более очевидно

2021-08-03 00:36 UTC, bugdea1er commented on libs/compiler/syntax.h
> + *	@return	Structure name, @c SIZE_MAX on failure
field скорее про битовые поля говорят. Вот определение структуры из документации С (6.2.5.20):
<img width="749" alt="image" src="https://user-images.githubusercontent.com/19926617/127939998-f1594349-7648-4213-9557-35385e61ce0c.png">

2021-08-04 03:29 UTC, 6easy9 approved these changes

2021-08-06 10:09 UTC, merged