Add Enum
andrey-terekhov/RuC pull request #168
Opened 2021-08-11 14:52 UTC by Ri7ay

2021-08-11 15:17 UTC, 6easy9 reviewed
Исправить проблемы с оформлением

2021-08-11 15:17 UTC, 6easy9 commented on libs/compiler/parser_decl.c
> +			break;
Должен быть на строку ниже скобки с тем же количеством отступов, что и скобка

2021-08-11 15:17 UTC, 6easy9 commented on libs/compiler/parser_decl.c
> +static bool check_int_initializer(const item_t type, const item_t expr_type) {
Скобка не на месте

2021-08-11 15:17 UTC, 6easy9 commented on libs/compiler/parser_expr.c
> +	return stack_pop(&prs->anonymous);
Отступ

2021-08-11 15:17 UTC, 6easy9 commented on libs/compiler/parser_expr.c
> +	const operand_t type = prs->last_type;
Отступ

2021-08-11 15:17 UTC, 6easy9 commented on libs/compiler/parser_expr.c
> +	to_value(prs);
Отступ

2021-08-11 15:17 UTC, 6easy9 commented on tests/executable/enum/test.c
> +enum name {
Перенести скобки, добавить перенос строки в конец файла

2021-08-11 15:20 UTC, 6easy9 requested changes

2021-08-11 15:20 UTC, 6easy9 commented on tests/executable/enum/test.c
> +	t, a = 10, b
Расписать на несколько строк

2021-08-15 14:00 UTC, 6easy9 requested changes

2021-08-15 14:00 UTC, 6easy9 commented on libs/compiler/parser_decl.c
> +		++field_value;
++ справа и вообще стоит перенести на строки 454 и 458

2021-08-17 04:44 UTC, 6easy9 requested changes

2021-08-18 04:24 UTC, 6easy9 requested changes
1) перегруппировать функции. В одной группе должны быть функции, выполняющие схожие действия
2) добавить const в описании функций ко всем аргументам, которые не изменяются

2021-08-18 04:24 UTC, 6easy9 commented on libs/compiler/parser_decl.c
> +static void parse_enum_field_initializer(parser *const prs, node *const parent, const item_t type, const item_t num);
Пререгруппировать, группы разделить отступом в виде пустой строки.

2021-08-18 04:24 UTC, 6easy9 commented on tests/executable/enum/test.c
> +}
Нужна пустая строка в конце файла

2021-08-18 13:36 UTC, Victor-Y-Fadeev requested changes

2021-08-18 13:36 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +	item_t local_modetab[100];
- Зачем так много?
- Почему создали здесь?

2021-08-18 13:36 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +	return type_add(prs->sx, local_modetab, 3);
Фокус:
```c
return type_add(prs->sx, (item_t []){ TYPE_ENUM, 0, 0 }, 3);
```

2021-08-18 13:36 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +static void parse_enum_field_initializer(parser *const prs, node *const parent, const item_t type, const item_t num)
Давайте по однороднее, в `parse_init_enum_field_declarator` вы назвали переменную `number`, а здесь `num`.
Выберите что-то одно и используйте в обоих случаях.

2021-08-18 13:36 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +static void parse_enum_field_initializer(parser *const prs, node *const parent, const item_t type, const item_t num);
Плодить декларации без необходимости крайне плохое решение, удалить!

У вас неправильный порядок функций, если вы расположите их таким образом, все ваши проблемы уйдут:
```c
static void parse_enum_field_initializer(parser *const prs, node *const parent, const item_t type, const item_t num);
static void parse_init_enum_field_declarator(parser *const prs, node *const parent, item_t type, item_t number);
static item_t parse_enum_declaration_list(parser *const prs, node *const parent);
static void parse_enum_specifier(parser *const prs, node *const parent);

static item_t parse_type_specifier(parser *const prs, node *const parent);
```

P.s. Если же у вас окажется необходимость дергать те функции, что ниже `parse_type_specifier`, то расположите весь свой блок внизу, а наверх всего одну декларацию для `parse_enum_specifier`.

2021-08-19 15:28 UTC, Ri7ay commented on libs/compiler/errors.c
> +			sprintf(msg, "в перечисление должен идти идентификатор поля");
```
Сейчас так можно сделать, эта ошибка для 
enum 
{ 
    a 
    b
};
```

2021-08-21 10:32 UTC, Victor-Y-Fadeev requested changes

2021-08-21 10:32 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> -
Верните сточку.

2021-08-21 10:32 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +static bool check_int_initializer(const item_t type, const item_t expr_type)
Это не интерфейсная функция, должна быть до разделителя.

2021-08-21 10:32 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +											  : (item_t)prs->array_dimensions - 1);
Верните как было.

2021-08-21 10:32 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.h
> -
Верните строчку.

2021-08-21 10:47 UTC, Victor-Y-Fadeev approved these changes

2021-08-30 19:37 UTC, bugdea1er requested changes
Новый тип `const int` вводится зря, ограничивать присваивание в константу перечисления нужно проще - оно не lvalue, то есть после разбора идентификатора в стек пойдёт value вместо variable. Константа, объявленная как `enum`, должна иметь тип `enum`, чтобы следить за необходимыми преобразованиями типов

2021-08-30 19:37 UTC, bugdea1er commented on libs/compiler/parser.h
> +
Зачем?

2021-08-30 19:37 UTC, bugdea1er commented on libs/compiler/parser_decl.c
> +			return TYPE_INTEGER;
При объявлении переменной типа enum ей нужно давать тип не `int`, а `enum`, и навешивать на арифметические выражения `integer conversions [C99 6.3.1.1]`. Пример использования этой тонкости - оператор `switch` умеет не требовать `default`, если в условии оператора переменная типа `enum`, и были покрыты все случаи
Другой пример - конвертация из `enum` в `int` допустима, но вот про конвертацию из одного `enum` в другой надо сообщать, хотя бы предупреждением

2021-08-30 19:37 UTC, bugdea1er commented on libs/compiler/parser_decl.c
> +	repr_set_reference(prs->sx, prs->lxr->repr, (item_t)old_id);;
Лишняя `;`

2021-08-30 19:37 UTC, bugdea1er commented on libs/compiler/parser_decl.c
> +	prs->last_id = 0;
Зачем? Она все равно устанавливается после этого, до установки значение не используется

2021-08-30 19:37 UTC, bugdea1er commented on libs/compiler/parser_decl.c
> +		prs->last_id = old_id;
Зачем?

2021-08-30 19:37 UTC, bugdea1er commented on libs/compiler/parser_decl.c
> +		parser_error(prs, empty_struct);
Заведите отльную ошибку про `enum`

2021-08-30 19:37 UTC, bugdea1er commented on libs/compiler/parser_decl.c
> +	return type_add(prs->sx, (item_t []){ TYPE_ENUM, 0, 0 }, 3);
Зачем так много 0 в таблице? Я не вижу, чтобы потом это заполнялось, да и информации в таблице типов про перечисление явно не хватает, хотелось бы как минимум константы уметь получать

2021-08-30 19:37 UTC, bugdea1er commented on libs/compiler/parser_decl.c
> +			if (prs->token == TK_INT_CONST)
Хотелось бы уметь константные выражения принимать

2021-08-30 19:37 UTC, bugdea1er commented on libs/compiler/parser_decl.c
> +				token_consume(prs);
Для таких случаев сразу в условие ставьте `token_try_consume`

2021-08-30 19:37 UTC, bugdea1er commented on libs/compiler/parser_decl.c
> +static bool check_int_initializer(const item_t type, const item_t expr_type)
Если хочется вынести это в отдельную функцию, тогда лучше завести функцию, чтобы все случаи проверяла
Пример [тут](https://github.com/bugdea1er/RuC/blob/bede46b78b670debc626f756cc2fc55d731924ce/libs/compiler/builder.c#L418)

2021-08-30 19:37 UTC, bugdea1er commented on libs/compiler/parser_expr.c
> +							   : parse_constant_in_enum(prs, prs->operand_displ);
Вместо `parse_constant_in_enum` лучше распишите тут через `if` случаи, когда в дерево добавляется узел идентификатора, а когда константы. Для объявления поля будет использоваться функция константного выражения

2021-09-01 10:43 UTC, 6easy9 approved these changes

2021-09-07 17:40 UTC, bugdea1er requested changes

2021-09-07 17:40 UTC, bugdea1er commented on libs/compiler/parser_expr.c
> +	if (type == TYPE_ENUM)
`type_is_enum`

2021-09-07 17:40 UTC, bugdea1er commented on libs/compiler/errors.h
> +	wait_l_parren,
`paren`

2021-09-07 17:40 UTC, bugdea1er commented on libs/compiler/parser.h
> + *	@return	Number of parsed enum field expression
Теперь же пара возвращается, а не число

2021-09-07 18:14 UTC, bugdea1er approved these changes

2021-09-08 14:33 UTC, Victor-Y-Fadeev requested changes

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +			field_value = type_with_num.second;
Единственное использование! Зачем вам вообще `pair`?

Проверьте прямо в `parse_enum_field_expression` и верните `ITEM_MAX`, все равно `++` от него сделать не получится.

И сюда бы отступ.

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.h
> +
Вам она не нужна.

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.h
> +pair parse_enum_field_expression(parser *const prs, node *const parent);
Верните `ITEM_MAX` если не константа, все равно его не получится инкрементировать.

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +	item_t type = TYPE_ENUM;
Зачем она вам? Вы ее нигде не меняете, подставьте сразу `TYPE_ENUM`.

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +	local_modetab[2] = (item_t)fields * 2;
```
local_modetab[2] = (item_t)(local_md - 3);
local_modetab[1] = local_modetab[1] / 2;
```

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +	item_t local_modetab[100];
Это можно перенести сюда:
```
local_modetab[0] = TYPE_ENUM;
```

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +	size_t fields = 0;
Это не нужно.

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +		++fields;
Не нужна, удалить и отступ поставьте.

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +				  const size_t field_repr)
- Если нужна в другой библиотеке, то делаем интерфейс!
- Назовите `check_enum_initializer`
- Отступы не по сайлгайду, никаких пробелов, `TAB` должен быть один и переносим мы вместе с запятой:
```c
bool check_enum_initializer(const syntax *const sx
	, const item_t type, const item_t expr_type, const size_t field_repr)
```

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +	if (!(type_is_enum(sx, type) && type_is_enum_field(expr_type)))
Лишнее усложнение, лучше так (и работать будет быстрее):
```c
if (!type_is_enum(sx, type) || !type_is_enum_field(expr_type))
```

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +	for (item_t i = 0; i < fields; ++i)
Мs везде пишем `i++`.

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +	return false;
Отступ.

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +					 !check_int_initializer(prs->sx, type, expr_type) && type != expr_type)
Переносим вместе с операцией и ставим один `TAB`:
```c
else if (!check_enum_initializer(prs->sx, type, expr_type, prs->lxr->repr)
	&& !check_int_initializer(prs->sx, type, expr_type) && type != expr_type)
```

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +
Мы не используем `extern` для обычных функций, совсем!

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		default:
Отступ.

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +								node_get_arg(&prs->nd, 0)));
Уже писал про правила переноса:
```c
node_set_arg(&parent, 0, operator_application(prs, token
	, node_get_arg(&parent, 0), node_get_arg(&prs->nd, 0)));
````

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
>  	if (token == TK_PIPE_PIPE || token == TK_AMP_AMP)
Отступ.

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +	item_t type = ident_get_type(prs->sx, (size_t)id);
Перенесите к `if` и сделайте `const`

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		type = operands_push(prs, VALUE, TYPE_ENUM);
В переменную писать незачем.

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		type = operands_push(prs, VARIABLE, ident_get_type(prs->sx, (size_t)id));
В переменную писать незачем.

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
>  	return (size_t)id;
Отступ.

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
>  		item_t result_mode = right_mode;
Поставьте до `if`, а то контекст далеко.

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		if (type_is_enum(prs->sx, left_mode))
Отступ.

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +				  && left_mode != right_mode)
Отступ и пробелы после `TAB`.

2021-09-08 14:33 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +	pair type_with_num = {node_get_type(&prs->nd), node_get_arg(&prs->nd, 0)};
Она вам тут не нужна и, на будущее, надо ставить пробелы внутри таких фигурных скобок. Проверьте прямо здесь на `OP_CONST`.

2021-09-08 16:09 UTC, Victor-Y-Fadeev requested changes

2021-09-08 16:09 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +	size_t local_md = 3;
Отступ.

2021-09-08 16:09 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +								const size_t field_repr)
Не исправили и не перенесли в интерфейс!

2021-09-08 16:09 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +					 && !check_int_initializer(prs->sx, type, expr_type) && type != expr_type)
Не исправили!

2021-09-08 16:09 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> -
Здесь должно быть 2 отступа.

2021-09-08 16:09 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		default:
Не исправили!

2021-09-08 16:09 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +													  , node_get_arg(&parent, 0), node_get_arg(&prs->nd, 0)));
У вас все съехало, как так получилось?

2021-09-08 16:09 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +			if (!check_enum_initializer(prs->sx, left_mode, right_mode, prs->lxr->repr) && left_mode != right_mode)
Отступ забыли.

2021-09-08 16:09 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +}
Забыли удалить узел...
```c
item_t parse_enum_field_expression(parser *const prs, node *const parent)
{
	node_copy(&prs->nd, parent);
	parse_assignment_expression_internal(prs);

	item_t value = node_get_arg(&prs->nd, 0);
	if (node_get_type(&prs->nd) != OP_CONST)
	{
		parser_error(prs, eq_not_const_int_for_enum_field);
		value = ITEM_MAX;
	}

	node_remove(&prs->nd);
	return value;
}
```

2021-09-08 23:47 UTC, Victor-Y-Fadeev requested changes

2021-09-08 23:47 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +	size_t local_md = 3;
Не туда поставили, нужно перед `local_md`, а не после...

2021-09-08 23:47 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		node_set_arg(&parent, 0, operator_application(prs, token, node_get_arg(&parent, 0), node_get_arg(&prs->nd, 0)));
121 символ, слишком длинная.

2021-09-08 23:47 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +		prs->nd = parent;
Отступ и используйте `node_copy`.

2021-09-08 23:47 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +
А этот лишний.

2021-09-08 23:47 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +	node_remove(&prs->nd);
Это блок и стоит сначала тип читать + `value` вместо `num`:
```c
const item_t type = node_get_type(&prs->nd);
const item_t value = node_get_arg(&prs->nd, 0);
node_remove(&prs->nd);
```

2021-09-09 11:04 UTC, Victor-Y-Fadeev requested changes

2021-09-09 11:04 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.h
> +		, const item_t type, const item_t expr_type, const size_t field_repr);
Один `TAB`.

2021-09-09 11:04 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.h
> + *	@return			@c 1 on true, @c 0 on false
Не исправили.

2021-09-09 11:04 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +bool check_enum_initializer(const syntax *const sx
Должен быть перенесен в интерфейс, так как объявлен в header. Функция должна быть внизу файла, после разделителя.

2021-09-09 12:03 UTC, Victor-Y-Fadeev requested changes

2021-09-09 12:03 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +					&& !check_int_initializer(prs->sx, type, expr_type) && type != expr_type)
Должен быть один `TAB`.

2021-09-09 12:06 UTC, Victor-Y-Fadeev approved these changes

2021-09-09 12:15 UTC, merged