Переход на новое дерево
andrey-terekhov/RuC pull request #169
Opened 2021-08-13 09:05 UTC by IvanArkhipov1999

Кодогенератор llvm переписан на новое дерево. Мною изменены только файлы кодогенератора и файлы ошибок (убрал некоторые ошибки, так как они больше не могут возникнуть). Остальное залито из ветки parser основного репозитория.

Сразу опишу ситуацию с тестами на Windows Server 2016. Там происходит Segmentation error [в llvmopt.c при вызове функции to_double](https://github.com/IvanArkhipov1999/RuC/blob/parser/libs/compiler/llvmopt.c#L119). Полагаю, что причиной является вызов memcpy в самой to_double. Почему так происходит и что делать, я без понятия, на старом дереве такого не было. Причём в llvmgen.c такая же [функция to_double](https://github.com/IvanArkhipov1999/RuC/blob/parser/libs/compiler/llvmgen.c#L577) не вызывает Segmentation error. Я могу убрать вызов to_double в llvmopt.c, тогда тесты будут проходить без ошибок, но не будет работать инициализация одномерных массивов типа double.

2021-08-13 11:23 UTC, IvanArkhipov1999 reviewed
Жду от @bugdea1er решение конфликтов, после этого внедряю использование `node_get_arg_double`

2021-08-16 12:11 UTC, bugdea1er commented on libs/compiler/llvmopt.c
>  			case OP_STRING:
Добавьте в syntax.h функцию `size_t string_size(const syntax *const sx)` следующего вида:
```c
size_t string_get(const syntax *const sx)
{
	return strings_size(&sx->string_literals);
}
```

Тогда печатать строки можно будет следующим образом:
В самом начале функции кодогенерации добавьте:
```c
const size_t strings_amount = string_size(info->sx);
for (size_t i = 0; i < strings_amount; i++)
{
    // Объявление глобальной переменной строки
}
```
Тогда поле номера строки из info тоже уйдет

2021-08-16 22:21 UTC, bugdea1er requested changes
- Не используйте `type_get`
- Для получения символа строки используйте `[]`
- и прочие замечания

2021-08-16 22:21 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +		type = type_get(info->sx, (size_t)type + 1);
Есть функция `type_array_get_element_type`
Использований `type_get` быть не должно

2021-08-16 22:21 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +	if (dim < 1 || dim > 5)
Магические числа? Вообще не понятно, откуда это взялось

2021-08-16 22:21 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +		return;
Тут, наверное, должна быть какая-то ошибка, типа "слишком большая размерность массива"

2021-08-16 22:21 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +		, (type_is_floating(type) ? 8 : 4) * hash_get_by_index(&info->arrays, index, 1)
Возможно, тут стоит использовать функцию type_size, чтобы потом было проще вводить другие типы

2021-08-16 22:21 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +			if (func_type != TYPE_VOID)
Пользуйтесь функциями type_is_

2021-08-16 22:21 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +	item_t displ = 0, memory_reg = 0;
Не объявляйте переменные в одной строке

2021-08-16 22:21 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +	info->answer_value_type = type != ALOGIC ? operation_type : TYPE_INTEGER;
Предложение: не называть вид значения type, так как в контексте с типами выражений это смотрится не очень. Можно назвать это `kind`

2021-08-16 22:21 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +	const item_t operation = node_get_arg(nd, 2);
Здесь только бинарный оператор, поэтому лучше объявлять `binary_t`
Аналогично и в случае с унарными операторами

2021-08-16 22:21 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +			for (string_length = 0; *(string + string_length) != 0; string_length++)
Это что-то странное, почему нельзя `string[string_length]`?

2021-08-16 22:21 UTC, bugdea1er commented on libs/compiler/llvmgen.c
>  static void structs_declaration(information *const info)
Этой функции уже не должно быть, в новом дереве есть узел объявления типа
Заведите функцию генерации объявления типа и вызывайте ее при появлении узла

2021-08-16 22:21 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> -}
Потерялся \n в конце файла

2021-08-16 22:21 UTC, bugdea1er commented on libs/compiler/llvmopt.c
>  				info->was_printf = 1;
Для стековых функций вы прямо в кодогенераторе сохраняете флаг и объявляете уже после кода программы.
С printf можно так же делать?

2021-08-17 08:49 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +	if (dim < 1 || dim > 5)
Я пока обрабатываю пока только простые конструкциии с массивами, из-за этого для каких-то случаев может оказаться, что размерность некорректная. Самое страшное, если она отрицательная, тогда дальше будет бесконечный цикл. Вот чтобы такого не было, я и вставил проверку. А числа и правда надо как-то обозвать, плохо выглядит

2021-08-17 08:50 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +		return;
Хм, название "слишком большая размерность массива" не совсем корректно отражает суть, я подумаю, что тут лучше выводить

2021-08-17 11:41 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
>  static void structs_declaration(information *const info)
Не выйдет. Тип может быть объявлен внутри функции, а мне в llvm нужно объявить тип структуры до вызовов всех функций (как со строками)

2021-08-17 13:06 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +		return;
Подумал. Это всё находится в функциях типа to_code. А для вызова ошибки нужно передать ноду. А передавать ноду в функцию типа to_code не хочется. Поэтому оставил так.

2021-08-17 14:25 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +	if (dim < 1 || dim > 5)
Откуда может взяться отрицательная размерность?

2021-08-17 14:27 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +		return;
Ошибку все равно нужно вывести, если код не генерируете. Возможно, стоит в другом месте заранее проверить размерность, возможно, стоит в функцию передать положение массива в исходном коде, но хоть что-то должно быть.

2021-08-17 14:29 UTC, bugdea1er commented on libs/compiler/llvmgen.c
>  static void structs_declaration(information *const info)
Тогда зачем было сделано [это](https://gitlab.softcom.su/ruc/ruc/-/issues/150)?

2021-08-18 04:39 UTC, 6easy9 requested changes

2021-08-18 04:39 UTC, 6easy9 commented on libs/compiler/llvmgen.c
>  												@c value[0]	 - флаг статичности
Много отступов, достаточно одного

2021-08-18 08:35 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
>  static void structs_declaration(information *const info)
Когда я писал этот issue, предполагалось, что я в llvmopt буду эти узлы обрабатывать. А теперь нет llvmopt

2021-08-18 08:37 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +	if (dim < 1 || dim > 5)
Если `hash_get_amount_by_index` вернёт 0

2021-08-18 09:14 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +	info->answer_value_type = type != ALOGIC ? operation_type : TYPE_INTEGER;
Тогда и в документации поправить 
`answer_t answer_kind;				/**< Тип ответа */`
на
`answer_t answer_kind;				/**< Вид ответа */`

2021-08-18 09:53 UTC, bugdea1er approved these changes

2021-08-18 11:57 UTC, Victor-Y-Fadeev requested changes
- У всех функций `is_something`/`was_something` должен быть тип `bool`
- Что-то у вас с типизацией при печати, перепроверьте все:
  - Указано что `item_t`, а печатаете `size_t` и наоборот
  - Для печати `size_t` используйте `%zu`, a не `%zi`
- Обобщите переменные, если вы используете только одну из них, например `displ` и `memory_reg`, заодно лишние проверки уйдут
- Самый важный вопрос, может ли вызваться `OP_CALL` внутри `OP_CALL`? Если нет, то следующим запросом, можно будет перевести аргументы на вектор. И и можно ли это проверить/гарантировать?

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			, info->answer_kind == AMEM ? 1 : 0);
Масло масляное...
```c
	, info->answer_kind == AMEM)
```

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	if (node_get_type(nd) == OP_IDENTIFIER)
```c
bool is_array = node_get_type(nd) != OP_IDENTIFIER;
if (!is_array)
```

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	to_code_store_reg(info, info->register_num, is_array ? memory_reg : displ, operation_type, is_array, 0);
`false`, а не `0`.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				to_code_load(info, info->register_num, displ, type, 0);
`false`, а не `0`.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +					to_code_load(info, info->register_num, info->register_num - 1, type, 1);
`true`, а не `1`.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				to_code_load(info, info->register_num, info->register_num - 1, type, 1);
`true`, а не `1`.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				to_code_store_const_i32(info, value_int, info->register_num - 1, 1);
`true`, а не `1`.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +					to_code_store_const_i32(info, num, info->request_reg, 0);
`false`, а не `0`.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				to_code_store_const_double(info, info->answer_const_double, info->register_num - 1, 1);
`true`, а не `1`.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +					to_code_store_const_double(info, num, info->request_reg, 0);
`false`, а не `0`.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  				is_addr_to_val = 1;
`true`, а не `1`.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	item_t displ = 0, memory_reg = 0;
Нехорошо, не стоит писать на одной строчке... Тааак, а зачем вам вообще их две? Вы всегда используете только одну из них! Сделайте общую переменную `displ`.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			uni_printf(info->sx->io, " @func%zi(", type_ref);
Не `%zi`, a `PRIitem`.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				"([%zi x i8], [%zi x i8]* @.str%zi, i32 0, i32 0)"
Не `%zi`, a `%zu` (везде).

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +					uni_printf(info->sx->io, " @func%zi(", ident_get_type(info->sx, ref_ident));
Не `%zi`, a `PRIitem`.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			uni_printf(info->sx->io, "%%struct_opt.%zi = type { ", i);
Не `%zi`, a `%zu`.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			, index, length + 1);
- Не `PRIitem`, a `%zu`
- Не `%zi`, a `%zu`

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +		else if (type_is_integer(operation_type))
```c
else if (type_is_integer(operation_type))	// ACONST
```

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	else if (type_is_integer(operation_type))
```c
else if (type_is_integer(operation_type))	// ACONST && =
```

P.s. `&&=` вообще у нас бывает (в си такого нет)?

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	item_t memory_reg = 0;
Зачем 2 переменные? Используйте одну - `displ`, заодно и проверки лишние уйдут.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  			item_t args_type[128];
Магические числа, заведите константу:
```c
#define MAX_PRINTF_ARGS 128
```

P.s. Отдельную от максимального количества аргументов функции.
P.p.s. Не забудьте с `N` сравнить.
P.p.p.s. А вообще можно будет потом вектора под это дело использовать, им как раз можно размер сразу `N` задать, только делать их надо будет глобальными, а не локальными, чтобы память все время не освобождать (только в следующем запросе).

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  				expression(info, nd);
Может ли здесь снова вызваться `OP_CALL`? Это важно, потому что если нет, можно будет полностью отказаться от массивов со значениями и перейти на вектора, но уже следующим запросом.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +					if (hash_get_by_index(&info->arrays, index, IS_STATIC) && !all)
Отступ.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  				for (size_t i = 0; i < parameters; i++)
Отступ.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +					if (info->was_memcpy)
Отступ.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +					if (info->was_printf)
Отступ.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +						"(i8* nocapture writeonly, i8* nocapture readonly, i32, i32, i1)\n");
`TAB` потеряли.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	const size_t types_size = vector_size(&info->sx->types);
Тогда уж просто `types`, раз внизу `fields`.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +		if (type_is_structure(info->sx, i) && i != 2)
Что бы это значило... Почему именно `2`? Здесь либо требуется константа (локальная) либо разъяснение.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	const size_t strings_number = strings_amount(info->sx);
Просто `amount` тогда уж.

2021-08-18 11:57 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	for (size_t index = 0; index < strings_number; index++)
Используйте `i` вместо `index`, он тут смысловой нагрузки не несет.

2021-08-18 13:28 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +	if (dim < DIMENSION_LOW_BORDER || dim > DIMENSION_HIGH_BORDER)
[Похожий вопрос](https://github.com/andrey-terekhov/RuC/pull/169#discussion_r690424315)

2021-08-18 13:52 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +				if ((item_t)DIMENSION_LOW_BORDER - 2 < cur_dimension && cur_dimension < (item_t)DIMENSION_HIGH_BORDER)
[Аналогично](https://github.com/andrey-terekhov/RuC/pull/169#discussion_r691109101)

2021-08-18 13:54 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
>  			item_t arguments_value_type[128];
Разве мы не отказались в своё время от `define` в пользу `const size_t`?

2021-08-18 21:31 UTC, Victor-Y-Fadeev requested changes

2021-08-18 21:31 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	if (dim < DIMENSION_LOW_BORDER || dim > DIMENSION_HIGH_BORDER)
Нуу, скажем так, `size_t` беззнаковый тип и меньше нуля не бывает, если вычесть единицу будет `SIZE_MAX`. И второе, это в какой момент у вас вообще здесь появляется ошибка? Некорректный индекс это не локальная проблема и ее обработка при каждом чтении затрудняет понимание кода.

2021-08-19 07:39 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
>  			item_t arguments_value_type[128];
Понял, почему не `const size_t`

2021-08-19 09:14 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +	else if (type_is_integer(operation_type))
У меня комментарий не корректный. Имеется в виду, что обрабатывается случай, когда справа константа и операцией является равенство

2021-08-19 09:23 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
>  				expression(info, nd);
Думаю, в RuC возможен вызов функции от результата вызова функции

2021-08-19 09:54 UTC, IvanArkhipov1999 reviewed
[Ответ к этому](https://github.com/andrey-terekhov/RuC/pull/169#discussion_r691618394). Некорректный индекс появляется из-за того, что не все случаи с массивами реализованы. Например, если имеется структура с массивами, то для этих массивов не создаётся запись, а при вырезке идёт ссылка на не существующую в хеш-таблице запись. Вот чтобы не рассматривать подобные случаи, я и проверяю тут корректность размерности.

2021-08-19 10:09 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +		if (type_is_structure(info->sx, i) && i != 2)
У таблицы типов первые элементы зарезервированы, теперь я это в коде понятно реализовал

2021-08-19 11:32 UTC, Victor-Y-Fadeev requested changes
В общем стоит удалить `DIMENSION_LOW_BORDER`, а `cur_dimension` сделать `size_t`.

2021-08-19 11:32 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	if (dim < DIMENSION_LOW_BORDER || dim > DIMENSION_HIGH_BORDER)
По поводу `size_t`, можно сделать так:
```c
if (dim == 0 || dim > DIMENSION_HIGH_BORDER)
```

Если у вас `0`, то `dim == SIZE_MAX`, если `1`, то `0`

2021-08-19 11:32 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	if (dim < DIMENSION_LOW_BORDER || dim > DIMENSION_HIGH_BORDER)
Попроще:
```c
if (dim == 0 || dim > DIMENSION_HIGH_BORDER)
```

2021-08-19 11:32 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				item_t cur_dimension = hash_get_amount(&info->arrays, displ) - 2;
Почему `item_t`? Сделайте `size_t`, это решит большинство проблем.

2021-08-19 11:32 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +const size_t DIMENSION_HIGH_BORDER = 5;
- Кстати, они все `static const`
- `DIMENSION_LOW_BORDER` - думаю можно удалить, если переведете `cur_dimension` на `size_t`
- А `DIMENSION_HIGH_BORDER` стоит переименовать в `MAX_DIMENSIONS`

2021-08-19 11:32 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				if ((item_t)DIMENSION_LOW_BORDER - 2 < cur_dimension && cur_dimension < (item_t)DIMENSION_HIGH_BORDER)
Если `cur_dimension` сделать `size_t`, то получится:
```c
if (cur_dimension != 0 && cur_dimension < MAX_DIMENSIONS)
```

Итого такие случаи:
- Возврат `0` -> `cur_dimension == SIZE_MAX -1`
- Возврат `1` -> `cur_dimension == SIZE_MAX`
- Возврат `2` -> `cur_dimension == 0`

Таким образом, можно будет сделать:
```c
static const size_t MAX_DIMENSIONS = SIZE_MAX - 1;
```
А еще лучше вычитаемую вами `2` в [566 строке](https://github.com/IvanArkhipov1999/RuC/blob/dfb9ee0d05a678062bef8896402783e35be23a19/libs/compiler/llvmgen.c#L566) сделать константой, тогда будет:
```c
static const size_t OP_SLICE_DIMENSION = 2;
static const size_t MAX_DIMENSIONS = SIZE_MAX - OP_SLICE_DIMENSION;
```

P.s. Последнее актуально, только если ограничение размерности `5` взято с потолка.
P.p.s. Не `SIZE_MAX - OP_SLICE_DIMENSION + 1` из-за [601 строки](https://github.com/IvanArkhipov1999/RuC/blob/dfb9ee0d05a678062bef8896402783e35be23a19/libs/compiler/llvmgen.c#L601).

2021-08-19 11:32 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				if ((item_t)DIMENSION_LOW_BORDER - 2 < cur_dimension && cur_dimension <(item_t)DIMENSION_HIGH_BORDER)
Если `cur_dimension` сделать `size_t`, то получится:
```c
if (cur_dimension != 0 && cur_dimension < MAX_DIMENSIONS)
```

2021-08-19 11:32 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			if ((item_t)DIMENSION_LOW_BORDER - 2 < cur_dimension && cur_dimension < (item_t)DIMENSION_HIGH_BORDER)
Если `cur_dimension` сделать `size_t`, то получится:
```c
if (cur_dimension != 0 && cur_dimension < MAX_DIMENSIONS)
```

2021-08-19 11:32 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			item_t cur_dimension = hash_get_amount(&info->arrays, displ) - 2;
`size_t`

2021-08-19 11:32 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  static void to_code_slice(information *const info, const item_t displ, const item_t cur_dimension
`cur_dimension` нужно сделать `size_t`.

2021-08-19 11:32 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  	const item_t dimensions = hash_get_amount(&info->arrays, displ) - 1;
`size_t`

2021-08-19 11:32 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  		for (item_t i = dimensions - cur_dimension; i <= dimensions; i++)
- И убрать приведения типа `(size_t)i`
- Все `for` переделать в:
```c
for (size_t i = dimensions - cur_dimension; i <= dimensions; i++)
```

2021-08-19 11:34 UTC, Victor-Y-Fadeev requested changes

2021-08-19 11:34 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +					uni_printf(info->sx->io, " %%%" PRIitem ", ", i);
Не `PRIitem`, а `%zu`.

2021-08-19 12:23 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +				if ((item_t)DIMENSION_LOW_BORDER - 2 < cur_dimension && cur_dimension <(item_t)DIMENSION_HIGH_BORDER)
На `static const size_t MAX_DIMENSIONS = SIZE_MAX - OP_SLICE_DIMENSION;` компилятор ругается:
```
error: initializer element is not constant
 static const size_t MAX_DIMENSIONS = SIZE_MAX - OP_SLICE_DIMENSION;
```
Поэтому написал вместо `OP_SLICE_DIMENSION` 2

2021-08-19 12:52 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +static const size_t DIMENSION_LOW_BORDER = 1;
Удалить

2021-08-19 12:52 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +static const size_t MAX_DIMENSIONS = SIZE_MAX - 2;
Суть `OP_SLICE_DIMENSION` была только в такой инициализации:
```c
static const size_t MAX_DIMENSIONS = SIZE_MAX - OP_SLICE_DIMENSION;
```
Поэтому удалите ее, тем более все равно не стали использовать.

Кстати, добавьте:
```c
static const size_t MAX_DIMENSIONS = SIZE_MAX - 2;	// Из-за OP_SLICE
```

2021-08-19 12:52 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				if (cur_dimension < MAX_DIMENSIONS)
А проверка на ноль не нужна?

2021-08-19 12:52 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			if (cur_dimension < MAX_DIMENSIONS)
А проверка на ноль не нужна?

2021-08-19 13:01 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +				if (cur_dimension < MAX_DIMENSIONS)
Тут проверка на ноль не нужна, потому что до этого был `cur_dimension--`, и `cur_dimension` мог стать нулём

2021-08-19 13:02 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +			if (cur_dimension < MAX_DIMENSIONS)
А здесь проверка на ноль не нужна, потому что рассматривается размерность 1, и `cur_dimension` в этом случае как раз ноль

2021-08-19 13:10 UTC, Victor-Y-Fadeev approved these changes

2021-08-19 13:22 UTC, merged