Кодогенератор mips на новом дереве
andrey-terekhov/RuC pull request #184
Opened 2021-08-26 15:44 UTC by IvanArkhipov1999

Начата реализация кодогенератора mips на новом дереве. Сделаны печати кода до и после основной кодогенерации, а также обработка функций без параметров.

2021-08-29 15:30 UTC, 6easy9 requested changes
Цикл while (true) выглядит очень нетипично для всего кода проекта. Наверное, стоит его переосмыслить

2021-08-29 15:30 UTC, 6easy9 commented on libs/compiler/mipsgen.c
> +typedef enum REGISTERS
Может стоит более понятным названия дать?

2021-08-29 15:30 UTC, 6easy9 commented on libs/compiler/mipsgen.c
> +		switch (node_get_type(&root))
Можно заменить на if else

2021-08-29 15:30 UTC, 6easy9 commented on libs/compiler/mipsgen.c
> +
Нужен перенос строки

2021-08-30 19:48 UTC, bugdea1er requested changes

2021-08-30 19:48 UTC, bugdea1er commented on libs/compiler/mipsgen.c
> +const item_t LOW_DYN_BORDER = 268500992;		// Это 0x10010000 -- нижняя граница динамической памяти
А почему бы не написать тогда 
```c
const item_t LOW_DYN_BORDER = 0x10010000;
```

2021-08-30 19:48 UTC, bugdea1er commented on libs/compiler/mipsgen.c
> +	S0,							/**< saved registers; values are preserved across function
Этот комментарий относится не к одной константе, ее надо на отдельную строку выше и оформлять как комментарий `//`

2021-08-30 19:48 UTC, bugdea1er commented on libs/compiler/mipsgen.c
> +typedef enum ISTRUCTIONS
Опечатка

2021-08-30 19:48 UTC, bugdea1er commented on libs/compiler/mipsgen.c
> +	ZERO,						/**< always has the value 0 */
Всем константам нужен какой-нибудь префикс

2021-08-30 19:48 UTC, bugdea1er commented on libs/compiler/mipsgen.c
> +} registers_t;
Название должно быть в единственном числе

2021-08-30 19:48 UTC, bugdea1er commented on libs/compiler/mipsgen.c
> +static void to_code_2R_I(universal_io *const io, const instructions_t instruction,
Запятую на следующую строку

2021-08-30 19:48 UTC, bugdea1er commented on libs/compiler/mipsgen.c
> +	const registers_t reg1, const registers_t reg2, const item_t num)
Вроде такое называют `imm`, наверное, `num` стоит переименовать

2021-08-30 19:48 UTC, bugdea1er commented on libs/compiler/mipsgen.c
> +				const item_t func_displ = ident_get_displ(info->sx, ref_ident);
Не используйте номер функции, берите сразу `id`
Для подсчета номеров функций приходится в парсере отдельную табличку держать, а смысла в этом нет

2021-08-30 19:48 UTC, bugdea1er commented on libs/compiler/mipsgen.c
> +					const size_t type = (size_t)node_get_arg(&root, 0);
И снова не `type`, а `id`

2021-08-30 19:48 UTC, bugdea1er commented on libs/compiler/mipsgen.c
> +static void precodegen(syntax *const sx)
Этим двум функциям явно нужны более понятные названия про то, что они печатают

2021-08-30 19:48 UTC, bugdea1er commented on src/main.c
> +	ws_add_flag(&ws, "-mips");
Тоже лучше большими буквами, MIPS - тоже аббревиатура

2021-08-31 07:24 UTC, IvanArkhipov1999 commented on libs/compiler/mipsgen.c
> +		switch (node_get_type(&root))
В switch будет ещё добавляться обработка других узлов, просто сейчас только написана обработка одного узла и то не полностью

2021-08-31 07:42 UTC, IvanArkhipov1999 commented on libs/compiler/mipsgen.c
> +typedef enum REGISTERS
Имеется в виду названия костант в `enum REGISTERS`? Я их называл в соответствии с названиями регистров из документации по архитектуре mips

2021-08-31 08:32 UTC, IvanArkhipov1999 commented on libs/compiler/mipsgen.c
> +static void precodegen(syntax *const sx)
Эти две функции реализуют печати до и после основной кодогенерации. В них содержатся разлиные директивы и вспомогательные команды. Сложно их объединить одним названием, так как каждые директива и набор команд выполняют какую-нибудь свою функцию. В дальнейшем я подробнее распишу комментариями, что есть что и что значит.

2021-08-31 08:34 UTC, IvanArkhipov1999 commented on libs/compiler/mipsgen.c
> +} registers_t;
На MacOS происходит ошибка:
```
/Users/runner/work/RuC/RuC/libs/compiler/mipsgen.c:79:3: error: typedef redefinition with different types ('enum REGISTERS' vs 'int64_t' (aka 'long long'))
} register_t;
  ^
/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/i386/types.h:87:33: note: previous definition is here
typedef int64_t                 register_t;
                                ^
1 error generated.
```

2021-08-31 16:52 UTC, bugdea1er approved these changes

2021-09-01 10:44 UTC, 6easy9 approved these changes

2021-09-03 10:19 UTC, Victor-Y-Fadeev requested changes
Вот совсем не пойдет!!! Вы удалили часть отвечающую за LLVM, вместо того чтобы добавить новую для MIPS. Я не могу такое принять, вы должны завести для MIPS отельные функции и файлы, а не ломать имеющиеся.

2021-09-15 22:21 UTC, Victor-Y-Fadeev requested changes
Выровняйте комментарии.

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +									which a function should return control */
- При переносе строки надо отступ добавлять в таком случае, так как вложенность
- И, думаю, лучше оформить так:
```c
/**< Return address which control should be returned */
```

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +} mips_register_t;
`mips` можно опустить, так как видимость только по этому файлу.

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +typedef enum INSTRUCTIONS
`INSTRUCTION`

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +	INSTR_J,						/**< To branch within the current 256 MB-aligned region */
Префикс инструкций у нас `IC`, возможно стоит добавить к нему суффикс `MIPS`:
```c
typedef enum INSTRUCTION
{
	IC_MIPS_MOVE,	/**< MIPS Pseudo-Instruction. Move the contents of one register to another */
	IC_MIPS_LI,	/**< MIPS Pseudo-Instruction. Load a constant into a register */
	IC_MIPS_ADDI,	/**< To add a constant to a 32-bit integer. If overflow occurs, then trap */
	IC_MIPS_SW,	/**< To store a word to memory */
	IC_MIPS_LW,	/**< To load a word from memory as a signed value */
	IC_MIPS_JR,	/**< To execute a branch to an instruction address in a register */
	IC_MIPS_JAL,	/**< To execute a procedure call within the current 256MB-aligned region */
	IC_MIPS_J,	/**< To branch within the current 256 MB-aligned region */
} instruction_t;
```

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +typedef enum LABELS
`LABEL`

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +} mips_instruction_t;
`mips` - не нужен.

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +} mips_label_t;
`mips` - не нужен.

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +	L_FUNCEND,					/**< Тип метки -- выход из функции */
Выровняйте комментарии к остальным типам по этим, у вас там лишние отступы. Удобнее читать когда все на одном уровне.

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +
2 отступа.

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +static void to_code_2R(universal_io *const io, const mips_instruction_t instruction, const mips_register_t reg1, const mips_register_t reg2)
Лучше писать `fst` и `snd`.

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +	, const mips_register_t reg1, const mips_register_t reg2, const item_t imm)
- `fst` и `snd`
- Что такое `imm`? Откуда название?

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +	, const mips_register_t reg1, const item_t imm, const mips_register_t reg2)
- `fst` и `snd`
- Вопрос про `imm`

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +	, const mips_register_t reg1, const item_t imm)
Зачем `reg1`? Здесь другого нет.

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +	, const mips_register_t reg1)
Зачем `reg1`? Здесь другого нет.

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +	, const mips_label_t label, const item_t label_num)
`label_num` - по моему не самое удачное имя, может это `value` или `address`?

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +static void to_code_label(universal_io *const io, const mips_label_t label, const item_t label_num)
`label_num` - по моему не самое удачное имя, может это `value` или `address`?

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +				// Восстановление стека после работы функции
Отступ.

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +
А вот этот вроде не нужен.

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +static void precodegen(syntax *const sx)
`pregen`

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +static void postcodegen(information *const info)
`postgen`

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +	precodegen(info.sx);
Просто `sx` или лучше целиком `info`.

2021-09-15 22:21 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +	return ret;
Отступ.

2021-09-20 07:44 UTC, IvanArkhipov1999 commented on libs/compiler/mipsgen.c
> +									which a function should return control */
Я брал текст прямо из документации, поэтому хочется его сохранить в таком виде, как там написано.

2021-09-20 07:51 UTC, IvanArkhipov1999 commented on libs/compiler/mipsgen.c
> +} mips_instruction_t;
Имя `instruction_t` конфликтует с перечислением в `operations.h`

2021-09-20 08:20 UTC, IvanArkhipov1999 commented on libs/compiler/mipsgen.c
> +} mips_register_t;
На `register_t` ругается macOS:
```
/Users/runner/work/RuC/RuC/libs/compiler/mipsgen.c:80:3: error: typedef redefinition with different types ('enum REGISTER' vs 'int64_t' (aka 'long long'))
} register_t;
  ^
/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/i386/types.h:87:33: note: previous definition is here
typedef int64_t                 register_t;
                                ^
1 error generated.
make[2]: *** [libs/compiler/CMakeFiles/compiler.dir/mipsgen.c.o] Error 1
make[1]: *** [libs/compiler/CMakeFiles/compiler.dir/all] Error 2
make: *** [all] Error 2
```

2021-09-20 08:31 UTC, IvanArkhipov1999 commented on libs/compiler/mipsgen.c
> +	, const mips_register_t reg1, const mips_register_t reg2, const item_t imm)
`imm` -- это сокращение от immediate, взял из документации

MIPS® Architecture for Programmers 
Volume II-A: The MIPS32® Instruction 
Set Manual:

![Снимок экрана от 2021-09-20 11-29-07](https://user-images.githubusercontent.com/19683401/133974928-d36f7df5-d249-4e46-a6ce-678ad7d3c06e.png)

2021-09-20 08:41 UTC, IvanArkhipov1999 commented on libs/compiler/mipsgen.c
> +	, const mips_label_t label, const item_t label_num)
Хм, `label_num` означает номер метки, вроде имя отражает смысл параметра. `value` у меня ассоциируется с каким-нибудь значением, а `address` с физическим адресом, что не очень подходит к номеру метки.

2021-09-30 13:46 UTC, Victor-Y-Fadeev approved these changes

2021-09-30 13:46 UTC, merged