Реализован интерфейс синтаксического дерева
andrey-terekhov/RuC pull request #185
Opened 2021-08-30 09:15 UTC by bugdea1er

- Реализован интерфейс синтаксического дерева. В нем пока не хватает интерфейса для чтения типов и операторов case/default/switch, будут добавлены позже.
- Узел строки превращен в узел литерала
- Типы узлов разделены на три группы выражений, операторов и объявлений. Это позволяет не использовать default и не рассчитывать на то, что узлы выражений и операторов будут равноправными в дереве. Пример функции генерации операторов:
```c
static void emit_statement(information *const info, const node *const nd)
{
	switch (statement_get_class(nd))
	{
		case STMT_DECL:
			emit_declaration(info, nd);
			return;

		case STMT_LABEL:
			emit_labeled_statement(info, nd);
			return;

		case STMT_CASE:
			// TODO: case statement emission
			// emit_case_statement(info, nd);
			return;

		case STMT_DEFAULT:
			// TODO: default statement emission
			// emit_default_statement(info, nd);
			return;

		case STMT_COMPOUND:
			emit_compound_statement(info, nd);
			return;

		case STMT_EXPR:
			emit_expression(info, nd);
			return;

		case STMT_NULL:
			return;

		case STMT_IF:
			emit_if_statement(info, nd);
			return;

		case STMT_SWITCH:
			// TODO: switch statement emission
			// emit_switch_statement(info, nd);
			return;

		case STMT_WHILE:
			emit_while_statement(info, nd);
			return;

		case STMT_DO:
			emit_do_statement(info, nd);
			return;

		case STMT_FOR:
			emit_for_statement(info, nd);
			return;

		case STMT_GOTO:
			to_code_unconditional_branch(info, (item_t)goto_stmt_get_label(nd));
			return;

		case STMT_CONTINUE:
			to_code_unconditional_branch(info, info->label_continue);
			return;

		case STMT_BREAK:
			to_code_unconditional_branch(info, info->label_break);
			return;

		case STMT_RETURN:
			emit_return_statement(info, nd);
			return;

		case STMT_PRINTF:
			emit_printf_statement(info, nd);
			return;
	}
}
```

Честно не знаю, что делать с функцией сломанного узла. Она используется в интерфейсе дерева, и логичнее, если она там будет, но тогда она должна по-другому называться, так как префикса `build` там быть не должно. При этом это теперь не только выражение, но и любая конструкция языка.

2021-09-01 10:52 UTC, 6easy9 approved these changes

2021-09-03 09:58 UTC, Victor-Y-Fadeev requested changes

2021-09-03 09:58 UTC, Victor-Y-Fadeev commented on libs/compiler/AST.c
> +		case OP_IF:			return STMT_IF;
Съехало.

2021-09-03 09:58 UTC, Victor-Y-Fadeev commented on libs/compiler/AST.c
> +		case OP_FOR:		return STMT_FOR;
Съехало.

2021-09-03 09:58 UTC, Victor-Y-Fadeev commented on libs/compiler/AST.c
> +		default:			return STMT_EXPR;
Может вы лучше везде запишите как всегда, с переносом строки? Из-за неравномерной левой части и близкого расположения тяжело читать.

2021-09-03 09:58 UTC, Victor-Y-Fadeev commented on libs/compiler/AST.h
> +	DECL_FUNC,			/**< Function definition */
Почему `definition`, а не `declaration`?

2021-09-03 09:58 UTC, Victor-Y-Fadeev commented on libs/compiler/AST.h
> +	return node_is_correct(nd) && node_get_type(nd) == ITEM_MAX ? node_get_amount(nd) : SIZE_MAX;
Поменяйте условия местами, работать станет быстрее.

2021-09-03 09:58 UTC, Victor-Y-Fadeev commented on libs/compiler/AST.h
> +	return node_is_correct(nd) && node_get_type(nd) == ITEM_MAX ? node_get_child(nd, index) : node_broken();
Поменяйте условия местами, работать станет быстрее.

2021-09-03 11:56 UTC, Victor-Y-Fadeev approved these changes

2021-09-03 11:56 UTC, merged