Мелкие исправления и доработки
andrey-terekhov/RuC pull request #186
Opened 2021-09-01 09:36 UTC by IvanArkhipov1999

Реализованы следующие пункты:

- Генерация return без выражения
- Преобразование типов при передаче аргументов в функцию
- Операторы отношения для double
- Убрать свёртку констант из кодогенератора
- Вызов функции abs

С этого pull request начинает работать WOK на llvm.

2021-09-01 11:03 UTC, 6easy9 requested changes
В документации к функциям всегда писали check that, а не check if

2021-09-01 15:06 UTC, 6easy9 approved these changes

2021-09-03 10:14 UTC, Victor-Y-Fadeev requested changes

2021-09-03 10:14 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	bool was_fabs;							/**< Истина, если был вызов fabs*/
Пробелы потеряли в комментариях.

2021-09-03 10:14 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +		else if (left_kind == ANULL && right_kind == AREG)
Лишний `TAB`.

2021-09-03 10:14 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
>  				if (info->answer_kind == AREG)
Отступ.

2021-09-15 17:35 UTC, Victor-Y-Fadeev approved these changes

2021-09-15 17:35 UTC, merged