Печать типов и дерева
andrey-terekhov/RuC pull request #191
Opened 2021-09-16 22:53 UTC by bugdea1er

https://gitlab.softcom.su/ruc/ruc/-/issues/187

2021-09-20 07:29 UTC, 6easy9 approved these changes
Замечаний к коду нет, есть только к огромным switch

2021-09-20 13:30 UTC, Victor-Y-Fadeev requested changes
Зачем вы везде напихали разделителей? У нас для этого используются суффиксы (вторые) и двойные отступы между группами приватных функций.

Раз уж делаем как в Clang, то давайте и имена с оформление оттуда возьмем.

Внезапно у вас всегда происходит `indent + 1` в вызове `write_expression` или `write_statement`, стоит занести это внутрь этих функций, а единственный узел `STMT_EXPR` обработать до `switch`. Тогда можно будет спокойно запихнуть `indent` в `writer`.

2021-09-20 13:30 UTC, Victor-Y-Fadeev commented on libs/compiler/writer.c
> +	write(wrt, "EXPR_LITERAL");
Так то `with value` стоит написать сюда...

2021-09-20 13:30 UTC, Victor-Y-Fadeev commented on libs/compiler/writer.c
> +	write(wrt, "EXPR_MEMBER selecting");
Может пора вместо `write_indent` завести `write_line`? Тогда было бы:
```c
write_line(wrt, "EXPR_MEMBER selecting");
```

2021-09-20 13:30 UTC, Victor-Y-Fadeev commented on libs/compiler/writer.c
> +	uni_printf(wrt->io, " declaring function named \'%s\' with id %zu of type '", spelling, ident);
Может просто `declare`? Вы откуда эти фразы берете? Из Clang или сами?

2021-09-20 13:30 UTC, Victor-Y-Fadeev commented on libs/compiler/writer.c
> +	(void)nd;
Почему? Зачем этот параметр?

2021-09-20 13:30 UTC, Victor-Y-Fadeev commented on libs/compiler/writer.c
> +	(void)nd;
Зачем?

2021-09-20 13:30 UTC, Victor-Y-Fadeev commented on libs/compiler/writer.c
> +	(void)nd;
Зачем? И вы всегда без отступа писали.

2021-09-20 13:30 UTC, Victor-Y-Fadeev commented on libs/compiler/writer.c
> +	(void)nd;
Уже говорил...

2021-09-20 13:30 UTC, Victor-Y-Fadeev commented on libs/compiler/writer.c
> +	uni_printf(wrt->io, " id=%zu\n", id);
Почему слитно, так везде?

2021-09-20 13:30 UTC, Victor-Y-Fadeev commented on libs/compiler/writer.c
> +	uni_printf(wrt->io, " id=%zu\n", id);
Тот же вопрос, что и к `printid`.

2021-09-20 13:30 UTC, Victor-Y-Fadeev commented on libs/compiler/writer.c
> +	write(wrt, "Translation unit\n");
Не уверен, что Clang так делает.

2021-09-20 13:30 UTC, Victor-Y-Fadeev commented on libs/compiler/writer.c
> +	//wrt_clear(&wrt);
Зачем?

2021-09-20 13:30 UTC, Victor-Y-Fadeev commented on libs/compiler/writer.c
> +		index += sprintf(&buffer[index], " (");
По моему должно быть `" (*)("`, потому что если звездочка припишется справа будет не очень...

P.s. Не забудьте поправить документацию в `syntax`/`buildin` для `'T'` параметра на `void*(*)(void*)`...

2021-09-20 13:30 UTC, Victor-Y-Fadeev commented on libs/compiler/writer.c
> +	return 0;
Отступ.

2021-09-20 14:28 UTC, bugdea1er commented on libs/compiler/writer.h
> +int write_type_spelling(const syntax *const sx, const item_t type, char *const buffer);
Потому что все printf-like функции возвращают int, конвертировать лишний раз туда и обратно не хочется

2021-09-20 14:33 UTC, bugdea1er commented on libs/compiler/writer.c
> +//===----------------------------------------------------------------------===//
Оно не помещается в ограничение в 120 символов

2021-09-20 14:34 UTC, bugdea1er commented on libs/compiler/writer.c
> +	   write(wrt, " ─ lvalue");
Тут хочется печатать тире, а не дефис. Какой символ использовать для тире?

2021-09-20 14:38 UTC, bugdea1er commented on libs/compiler/writer.c
> +	write(wrt, "EXPR_IDENTIFIER");
Зачем названия из clang брать? Дерево печатается для разработчиков (нас), а не для пользователя. Логично и печатать то, что дереве есть: встретили `EXPR_IDENTIFIER` – печатаем `EXPR_IDENTIFIER`

2021-09-20 14:41 UTC, bugdea1er commented on libs/compiler/writer.c
> +	uni_printf(wrt->io, " declaring function named \'%s\' with id %zu of type '", spelling, ident);
Узел, объявляющий функцию под именем "…" => Node declaring function named "…"

2021-09-20 14:42 UTC, bugdea1er commented on libs/compiler/writer.c
> +	(void)nd;
Везде прописал `(void)nd`, так как очень скоро планируем в каждый узел добавить положение из исходного файла

2021-09-20 14:44 UTC, bugdea1er commented on libs/compiler/writer.c
> +	write(wrt, "Translation unit\n");
У нас корень не имеет тип, так что не запишешь объявление единицы трансляции в список объявлений, как это делается в clang. При этом обозначить этот узел надо, и для его чтения у нас даже есть интерфейс

2021-09-20 14:46 UTC, bugdea1er commented on libs/compiler/writer.c
> +		index += sprintf(&buffer[index], " (");
Это печать типа функции, а не указателя на функцию. Указателей на функции у нас пока нет, и мы так и не обсудили, нужны ли эти конвертации языку
На данный момент для `'T'` параметра тип именно `void* (void*)`

2021-09-20 14:48 UTC, bugdea1er commented on libs/compiler/writer.c
> +	write_location(wrt, expression_get_location(nd));
Положение узла у нас хранится последними аргументами, вполне логично печатать это в конце

2021-09-30 09:51 UTC, Victor-Y-Fadeev approved these changes

2021-09-30 09:51 UTC, merged