Add Enum in parser
andrey-terekhov/RuC pull request #192
Opened 2021-09-19 13:22 UTC by Ri7ay

2021-09-20 07:16 UTC, 6easy9 requested changes
Замечания в комментариях

2021-09-20 07:16 UTC, 6easy9 commented on libs/compiler/builder.c
> +	if (type_is_integer(left_type) || type_is_integer(right_type)
Стоит добавить в состав return

2021-09-20 07:16 UTC, 6easy9 commented on libs/compiler/parser_decl.c
> +
Лишний перенос строки

2021-09-20 07:16 UTC, 6easy9 commented on libs/compiler/parser_decl.c
> +            token_consume(prs);
Исправить на табы

2021-09-20 11:57 UTC, 6easy9 approved these changes

2021-09-20 13:45 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +		? TYPE_INTEGER : TYPE_FLOATING;
```c
return (type_is_integer(left_type) || type_is_enum_field(left_type))
	&& (type_is_integer(right_type) || type_is_enum_field(right_type)) 
		? TYPE_INTEGER
		: TYPE_FLOATING;
```

2021-09-20 13:45 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +	, const item_t expected_type, const item_t actual_type)
Влезает в одну строчку.

2021-09-20 13:45 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
> +	, const item_t actual_type)
Влезает в одну строчку.

2021-09-20 13:45 UTC, Victor-Y-Fadeev commented on libs/compiler/builder.c
2 отступа.

2021-09-21 21:40 UTC, bugdea1er requested changes

2021-09-21 21:40 UTC, bugdea1er commented on libs/compiler/builder.c
> +        node_add_arg(&nd, -type);                               	// Тип значения литерала
Все эти операции с типами не должны быть снаружи, семантический анализатор про устройство системы типов знать вообще не должен, все через интерфейсные функции исполняется

2021-09-21 21:40 UTC, bugdea1er commented on libs/compiler/builder.c
> +        nd = node_create(sx, OP_LITERAL);
Построение узла литерала есть уже в отдельной функции, тут стоит просто ее вызвать

2021-09-21 21:40 UTC, bugdea1er commented on libs/compiler/builder.c
> +	}
Это тоже должно быть куда-то спрятано. Анализатор получает готовый тип с помощью `expression_get_type`.

2021-09-21 21:40 UTC, bugdea1er commented on libs/compiler/builder.c
> +				|| (!type_is_integer(right_type) && !type_is_enum_const(right_type)))
Константа перечисления - тоже целочисленный тип, поэтому тут должно хватать проверки `type_is_integer`, стоит добавить в нее проверку `type_is_enum_const`

2021-09-21 21:40 UTC, bugdea1er commented on libs/compiler/errors.c
> +			break;
Кажется, эти ошибки больше не нужны

2021-09-21 21:40 UTC, bugdea1er commented on libs/compiler/parser_expr.c
> +}
- Договаривались, что тут будет использоваться функция `parse_constant_expression`. В ее код нужно добавить проверку на то, что вернулся узел литерала (и кидать ошибку иначе), а дальнейшие операции (проверка типов и удаления узлов) будут происходить уже в parser_decl при вызове этой самой `parse_constant_expression`

2021-09-21 21:40 UTC, bugdea1er commented on libs/compiler/syntax.c
> +}
Здесь не хватает проверок:
- Что поле добавляется именно в тип `enum`
- Что этот тип еще в процессе объявления, то есть что в таблице нет ничего, что было бы записано позже `enum`

2021-09-21 21:40 UTC, bugdea1er commented on libs/compiler/builder.c
> +}
У этих функций единственное использование в `check_assignment_operands`. Лучше это записать туда в отдельные `if` для читаемости

2021-09-30 12:18 UTC, bugdea1er approved these changes

2021-09-30 12:23 UTC, merged