Очень много мелких изменений
andrey-terekhov/RuC pull request #228
Opened 2021-11-12 15:55 UTC by IvanArkhipov1999

Какие именно изменения, можно посмотреть по коммитам

2021-11-12 19:09 UTC, bugdea1er requested changes

2021-11-12 19:09 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +	uni_printf(info->sx->io, "%s, align 4\n", is_local ? "" : " zeroinitializer");
На обсуждении решили, что инициализировать нужно все

2021-11-12 19:09 UTC, bugdea1er commented on libs/compiler/llvmgen.c
>  		const item_t id = expression_identifier_get_id(&identifier);
id должен быть `size_t`

2021-11-12 19:09 UTC, bugdea1er commented on libs/compiler/llvmgen.c
>  	const item_t id = expression_identifier_get_id(&base);
И снова `size_t`

2021-11-12 19:09 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +	bool is_array = expression_get_class(&operand) == EXPR_SUBSCRIPT || expression_get_class(&operand) == EXPR_UNARY;
Как-то странно, что `is_array == true` при `EXPR_UNARY`

2021-11-12 19:09 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +		info->answer_kind = ANULL;
Это разве не всегда должно вместе идти? Мб лучше `store_null` будет устанавливать ответ в `ANULL`?

2021-11-12 19:09 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +		const item_t is_local = ident_is_local(info->sx, (size_t)id);
Почему опять `id` не того типа?

2021-11-15 09:25 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +	uni_printf(info->sx->io, "%s, align 4\n", is_local ? "" : " zeroinitializer");
Инициализация массивов по умолчанию -- довольно нетривиальная задача, учитывая то, что нужно различать инициализацию статических и динамических массивов. Поэтому она будет реализована в отдельном запросе

2021-11-15 11:29 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +		info->answer_kind = ANULL;
[Создал issue](https://gitlab.softcom.su/ruc/ruc/-/issues/218)

2021-11-15 12:29 UTC, bugdea1er approved these changes

2021-11-19 14:26 UTC, merged