Инициализация многомерных локальных массивов
andrey-terekhov/RuC pull request #234
Opened 2021-11-29 09:03 UTC by IvanArkhipov1999

Реализована инициализация многомерных локальных массивов. И чуть подправлены тернарные операторы, в прошлом запросе не заметили неиспользующиеся переменные:)

2021-11-29 09:08 UTC, 6easy9 approved these changes

2021-11-29 12:17 UTC, bugdea1er requested changes

2021-11-29 12:17 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +
Это что-то очень страшное
Всегда можно прочитать из nd, это константный указатель
Реализовано сейчас только для одномерных массивов, так что в этом, кажется, нет смысла

2021-11-29 12:17 UTC, bugdea1er commented on libs/compiler/llvmgen.c
>  	}
Есть предложение ставить assert прямо в кодогенератор, чтобы тесты, которые используют нереализованное, точно не прошли

2021-11-29 12:17 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +		const item_t is_local = ident_is_local(info->sx, (size_t)id);
Это должно быть `bool`

2021-11-29 12:17 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +	, const size_t cur_dimension, const item_t prev_slice, const bool is_local)
Лимит символов - 120 на строку

2021-11-29 12:17 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +	const size_t N = expression_list_get_size(nd);
Вместо `N` лучше `length`, `size` или что-нибудь такое

2021-11-29 12:17 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +		if (cur_dimension == 0)
Непонятно, функция называется `emit_one_dimension_initialization`, она же только одномерные случаи должна обрабатывать?

2021-12-07 12:05 UTC, bugdea1er approved these changes

2021-12-07 12:09 UTC, merged