Выделение char в отдельный тип
andrey-terekhov/RuC pull request #246
Opened 2021-12-20 16:48 UTC by IvanArkhipov1999

2021-12-20 16:53 UTC, 6easy9 approved these changes

2021-12-20 19:17 UTC, bugdea1er requested changes

2021-12-20 19:17 UTC, bugdea1er commented on libs/compiler/llvmgen.c
>  }
Это вообще не нужно, в арифметических операциях гарантируется, что оба подвыражения будут иметь один и тот же тип
Можно просто смотреть на тип левого операнда

2021-12-20 19:17 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +	, const item_t fst, const item_t snd, const type_t type)
И снова `type_t` там, где должен быть `item_t`
- `item_t` для типов выражений (например, `int[][]`)
- `type_t` для вида типа (например, массив)

2021-12-20 19:17 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +	, const item_t fst, const item_t snd, const type_t type)
Аналогично

2021-12-20 19:17 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +	, const bool is_array, const bool is_local, const type_t type)
И опять

2021-12-21 12:03 UTC, bugdea1er approved these changes

2021-12-21 13:11 UTC, merged