Новая вырезка, инициализация строкой и подправленные тесты
andrey-terekhov/RuC pull request #254
Opened 2021-12-29 19:03 UTC by IvanArkhipov1999

Вырезка работает для любого количества измерений (динамические массивы надо отдельно ещё проверить).
Реализована инициализация одномерного массива строкой.
Исправлена пара тестов.

2021-12-30 10:55 UTC, bugdea1er requested changes

2021-12-30 10:55 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> + *	Emit initialization of lvalue
Описание испортилось

2021-12-30 10:55 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> + *	Emit initialization of lvalue
И снова

2021-12-30 10:55 UTC, bugdea1er commented on libs/compiler/llvmgen.c
>  	}
Опять же вопрос, а если там не вырезка была? Там могло быть косвенное обращение `*`

2021-12-30 10:55 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +	}
Тут еще надо подумать над динамическими проверками длин инициализируемого массива и инициализатора, статически такие проверки не делаются

2022-01-27 17:14 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
>  	}
Я правильно понял, что имеется в виду следующее?
```
int a[5][3];
*a[2] = 1;
```

2022-01-27 17:29 UTC, bugdea1er commented on libs/compiler/llvmgen.c
>  	}
Вот не особо осмысленный пример, но он тоже должен работать:
’’’c
int a[5];
(*(&a))[3];
’’’

2022-01-27 17:34 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +	}
А можно тоже пример, в голову пока не приходит что-то подходящее

2022-01-27 18:37 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +	}
Такую конструкцию запрещает С, но у нас такое должно работать
```c
int a[n] = { 0, 1, 2 };
```

2022-02-01 13:03 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +	}
Очень спорная конструкция, мне кажется, это требует обсуждения

2022-02-01 13:04 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
>  	}
Предлагаю пока отложить такой случай, но добавить на это тест

2022-02-02 11:12 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +	}
https://gitlab.softcom.su/ruc/ruc/-/issues/248

2022-02-02 11:16 UTC, bugdea1er approved these changes

2022-02-02 11:17 UTC, merged