[#269] C++ compilation improvements
andrey-terekhov/RuC pull request #270
Opened 2022-01-29 14:35 UTC by maximmenshikov

This patch series addresses several problems when interoperating with C++.
1. error_t clashes with std::error_t.
2. Avoid GNU extensions (designated initializers) in headers.
3. Variable name "operator" clashes with C++'s "operator" keyword.

2022-01-29 19:44 UTC, bugdea1er requested changes

2022-01-29 19:44 UTC, bugdea1er commented on libs/compiler/instructions.h
> +instruction_t unary_to_instruction(const unary_t op);
Имя параметра в документации не изменено

2022-01-29 19:44 UTC, bugdea1er commented on libs/compiler/operations.h
> +bool operation_is_assignment(const binary_t op);
Имя параметра в документации не изменено

2022-01-29 19:44 UTC, bugdea1er commented on libs/compiler/writer.c
>   *	@param	operator	Operator
Имя параметра в документации не изменено

2022-01-29 19:44 UTC, bugdea1er commented on libs/compiler/writer.c
>   *	@param	operator	Operator
Имя параметра в документации не изменено

2022-01-31 08:11 UTC, IvanArkhipov1999 reviewed
Функции работы с токенами, мне кажется, лучше оставить inline. И я переадресовал запрос в ветку feature, она у нас накопительная, чтобы master часто не трогать

2022-01-31 13:12 UTC, maximmenshikov commented
> Функции работы с токенами, мне кажется, лучше оставить inline. И я переадресовал запрос в ветку feature, она у нас накопительная, чтобы master часто не трогать

Для внешне доступной функции inline не особо применим, к сожалению, а раскрывать реализацию в заголовочном файле не стоит.
Оверхед от отсутствия инлайнинга вряд ли будет различим.

2022-01-31 13:46 UTC, IvanArkhipov1999 approved these changes

2022-01-31 14:31 UTC, merged