Слияние с feature
andrey-terekhov/RuC pull request #277
Opened 2022-02-02 13:41 UTC by IvanArkhipov1999

Слияние с веткой feature и небольшие доработки

2022-02-02 14:04 UTC, bugdea1er requested changes

2022-02-02 14:04 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> + *	Emit initialization of lvalue
Опять что-то не то с описанием

2022-02-02 14:04 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> + *	Emit one dimension subscript expression
И тут

2022-02-03 11:20 UTC, IvanArkhipov1999 commented
Ветка сломана, создаёт новая ветка

2022-02-03 11:20 UTC, closed without merging