[#312] Fix header parsing issues in C++ context
andrey-terekhov/RuC pull request #313
Opened 2022-04-17 10:40 UTC by maximmenshikov

This patch series adds/fixes the following:
 - Compilation of headers on Mac in C++ context, which was failing due to redefined char32_t.
 - ruccpp library is added to ensure that C++ compilation will not be broken.

2022-04-18 15:29 UTC, Victor-Y-Fadeev requested changes
Не уверен что стоит менять `_MSC_VER` на `_WIN32`, так как у нас нигде не гарантируется и не проверяется собираемость чем-то отличным от MSVC. В виртуальной машине так это вообще невозможно без трудозатрат, из-за отсутствия стандартных pthreads под Windows

2022-04-18 15:29 UTC, Victor-Y-Fadeev commented on CMakeLists.txt
> +	set(CMAKE_CXX_STANDARD 20)
У нас вроде как выставлен 11 стандарт и не `CXX`, а `C`

2022-04-18 15:29 UTC, Victor-Y-Fadeev commented on libs/compiler/AST.c
2 отступа.

2022-04-18 15:29 UTC, Victor-Y-Fadeev commented on libs/cpp-wrap/CMakeLists.txt
> +						  	preprocessor)
Съехало вообще все, запишите без переносов.

2022-04-18 15:29 UTC, Victor-Y-Fadeev commented on libs/cpp-wrap/CMakeLists.txt
> +if (RUC_CPPWRAP_CHECK_PREPROCESSOR)
- У нас `if` без отступа
- Если хотите передать из консоли, думаю стоит дописать `DEFINED`
- Вы используете эту константу в исходниках, она будет не видна, если не пробросить через `add_compile_definitions`

2022-04-18 15:29 UTC, Victor-Y-Fadeev commented on libs/cpp-wrap/CMakeLists.txt
> +endif ()
- Нет переноса строки
- Нет отступа

2022-04-18 15:29 UTC, Victor-Y-Fadeev commented on libs/cpp-wrap/wrap.cpp
> +/* compiler headers */
Нет лицензии

2022-04-18 15:29 UTC, Victor-Y-Fadeev commented on libs/cpp-wrap/wrap.cpp
> +/* preprocessor headers */
Возможно их стоит поменять местами

2022-04-18 15:29 UTC, Victor-Y-Fadeev commented on libs/cpp-wrap/wrap.cpp
> +#include "utils.h"
Нет левого отступа

2022-04-18 15:29 UTC, Victor-Y-Fadeev commented on libs/utils/node_vector.c
> +
2 отступа

2022-04-18 15:29 UTC, Victor-Y-Fadeev commented on libs/utils/node_vector.c
> +}
Нет переноса строки

2022-04-18 15:29 UTC, Victor-Y-Fadeev commented on libs/utils/utf8.h
> +#endif
Нет левых отступов

2022-04-18 15:49 UTC, maximmenshikov commented on libs/cpp-wrap/CMakeLists.txt
> +						  	preprocessor)
It is not a bug, it is a feature.

2022-04-18 15:51 UTC, maximmenshikov commented on libs/cpp-wrap/CMakeLists.txt
> +if (RUC_CPPWRAP_CHECK_PREPROCESSOR)
1. OK
2. It is basically intended to be OFF or ON. But in fact it wouldn't work at all and I don't want to have it working as of now.
3. Surely I know this, but I don't care as well about this point - preprocessor is not working properly as of now.

2022-04-18 15:57 UTC, maximmenshikov commented on libs/utils/utf8.h
> +#endif
This looks unhandled in the coding standard.

2022-04-18 15:57 UTC, maximmenshikov commented on libs/utils/node_vector.c
> +}
Unhandled in the coding standard

2022-04-18 16:02 UTC, maximmenshikov commented on CMakeLists.txt
> +	set(CMAKE_CXX_STANDARD 20)
This is not for RuC itself, but for external MSVC users who try it from C++ context. There are several issues with the headers which are worth to be fixed, but enabling C++20 mode is the simplest way to circumvent issue for now.
I generally suggest to fix such issues on demand as it is a large amount of work to be done.

2022-04-18 16:08 UTC, maximmenshikov commented on libs/cpp-wrap/wrap.cpp
> +#include "utils.h"
> Не уверен что стоит менять `_MSC_VER` на `_WIN32`, так как у нас нигде не гарантируется и не проверяется собираемость чем-то отличным от MSVC. В виртуальной машине так это вообще невозможно без трудозатрат, из-за отсутствия стандартных pthreads под Windows

It doesn't matter whether RuC supports non-MSVC builds or not. _WIN32 check is a safer alternative compared to _MSC_VER.

Adding MinGW to CI in future feels reasonable BTW.

2022-04-18 16:17 UTC, maximmenshikov commented on libs/cpp-wrap/CMakeLists.txt
> +if (RUC_CPPWRAP_CHECK_PREPROCESSOR)
BTW, I strongly advice against using ``add_compile_definitions``. Use ``target_compile_definitions``. That's a common problem in the project.

2022-04-19 08:57 UTC, Victor-Y-Fadeev approved these changes

2022-04-19 08:57 UTC, merged