Added inline expression
andrey-terekhov/RuC pull request #322
Opened 2022-08-05 18:41 UTC by Mexanobar

- Added OP_INLINE node in AST.c;
- Added EXPR_INLINE node in AST.h;
- Created build_print_expression() and build_printid_expression() in builder.c;
- Rebuilded emit_printid_expression() and emit_print_expression() and added inline expression handler in codegen.c;
- Added inline, printid and print expressions handlers in llvmgen;
- Added OP_INLINE in operations.h;
- Added string_add_by_char() in syntax.h and syntax.c;
- Added inline expression handler in writer.c;

2022-08-13 10:18 UTC, bugdea1er commented on libs/compiler/codegen.c
>  }
Суть задачи в том, чтобы избавиться от необходимости генерировать вызовы print и printid

2022-08-18 09:34 UTC, IvanArkhipov1999 commented on libs/compiler/AST.h
> +node expression_inline(const item_t type, node_vector *const args, const location loc);
Кажется, описание параметров не совпадает с реальностью

2022-08-18 09:39 UTC, IvanArkhipov1999 commented on libs/compiler/AST.h
> + *	Get size of inline expresssion
С буквами s явный перебор

2022-08-18 09:39 UTC, IvanArkhipov1999 commented on libs/compiler/AST.h
> + *	Get subestatement of inline expression by index
Снова опечатка

2022-08-18 09:40 UTC, IvanArkhipov1999 commented on libs/compiler/AST.h
> + *	@param	index			Subestatement index
Та же опечатка

2022-08-18 09:40 UTC, IvanArkhipov1999 commented on libs/compiler/AST.h
> + *	@param	index			Subestatement index
Та же опечатка

2022-08-18 09:45 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +	//node printf_callee = build_identifier_expression(bldr, BI_PRINTF, loc);
Закомментированный код -- зло, которое нужно выжигать огнём

2022-08-18 09:46 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +	for (size_t i = 0; i < dimensions; i += 1)
i++ красивее выглядит

2022-09-06 16:31 UTC, bugdea1er requested changes
Если в билдер набежало так много строк, их стоит вынести в отдельный файл, который только билдер и будет использовать. В этом новом файле будут свои скрытые функции.
После переноса надо будет еще раз тщательнее перечитать код подстановки строк. К остальным файлам все претензии уже описаны

2022-09-06 16:31 UTC, bugdea1er commented on libs/compiler/llvmgen.c
> +}
Небольшой недочет (относится и к генерации codegen) - если хочется этот узел использовать еще и для inline-оптимизаций, то нужно учитывать возвращаемое выражение. На данный момент все принты внутри таких inline expression не будут ничего оставлять на стеке, и это будет работать, но стоит оставить комментарий на будущее, что это надо будет править:
```c
// FIXME: inline expression cannot return value at the moment
```

2022-09-06 16:31 UTC, bugdea1er commented on libs/compiler/codegen.c
> +
```c
// FIXME: inline expression cannot return value at the moment
```

2022-09-06 16:31 UTC, bugdea1er commented on libs/compiler/AST.h
> +node expression_inline_get_callee(const node *const nd);
Это, наверное, осталось со старых версий? Сейчас оно не используется при генерации и печати

2022-09-06 16:31 UTC, bugdea1er commented on libs/compiler/AST.c
> +}
И это тоже, наверное, уже не нужно

2022-09-06 16:31 UTC, bugdea1er commented on libs/compiler/operations.h
> +	OP_INLINE,				/**< Inline operation node */
Вот тут мне не особо нравится слово `operation`, его б заменить на что-нибудь, @IvanArkhipov1999?
А то кажется, что через полгода и не вспомним, что это такое, в документации языка такого нет, это чисто внутренняя штука компилятора

2022-09-06 16:31 UTC, bugdea1er commented on libs/compiler/builder.c
> +				return node_broken();
Вот тут всякие проблемы со стилем кода, очень не хочется во все такое тыкать, нужно перепроверить

2022-09-06 16:31 UTC, bugdea1er commented on libs/compiler/builder.c
> +	char *str = calloc(1, sizeof(char));
Лучше, наверное, использовать `vector` из `utils` (и не обращать внимание, что оно по памяти не такое оптимальное)

2022-10-06 12:56 UTC, IvanArkhipov1999 reviewed
В inline_expression.c static функции перемешаны с интерфейсными функциями. Хорошо бы их разделить, как, например, в [AST.c](https://github.com/andrey-terekhov/RuC/blob/master/libs/compiler/AST.c#L38)

2022-10-13 14:38 UTC, IvanArkhipov1999 requested changes
Очистка памяти, для проверки valgrind можно использовать

2022-10-13 14:38 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +	const size_t expected_args = evaluate_args(bldr, &fst, format_types, actual_types, placeholders);
Передавать такой массив странно. Туда можно передавать спецификатор на type pointer на type undefined. Надо расширить assignment_operands, чтобы она не ругалась на случаи, когда тип одного из операндов type pointer на type undefined.

2022-10-13 14:38 UTC, IvanArkhipov1999 commented on libs/compiler/inline_expression.h
> +#pragma once
Посмотреть, как это написано, например, в parser.h

2022-10-13 14:38 UTC, IvanArkhipov1999 commented on libs/compiler/inline_expression.c
> +
Доп пустые строки нужны

2022-10-13 14:38 UTC, IvanArkhipov1999 commented on libs/compiler/inline_expression.c
> +	result = statement_compound(&bldr->context, &res_stmts, loc);
Лишняя вложенность, можно сразу в inline expression добавить

2022-10-13 14:38 UTC, IvanArkhipov1999 commented on libs/compiler/inline_expression.c
> +node create_printf_node_by_vector(builder *bldr, const vector *str, node_vector *args, location l_loc, location r_loc)
Везде добавить const на все параметры, локальные переменные, указатель, на что указывает указатель везде, где возможно

2022-10-13 14:38 UTC, IvanArkhipov1999 commented on libs/compiler/inline_expression.c
> +		case TYPE_BOOLEAN:
Хотим писать не 0 или 1, а true или false

2022-10-18 10:25 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +					format_types[args++] = TYPE_UNDEFINED;
Здесь нужен указатель на TYPE_UNDEFINED. Внутренний тип сравнивать не надо, но всё ещё надо сравнить, что это указатель

2022-10-18 10:28 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
>  		return node_broken();
Зачем выделять память под stmts и args_to_print, а потом проверять условие и очищать память, когда можно сначала проверить условие и при выполнении выделить память?

2022-10-18 10:31 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +					node_vector_clear(&args_to_print);
Надо же ещё очищать память из-под str

2022-10-18 10:33 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +					node_vector_clear(&args_to_print);
И тут память из-под str не освободил

2022-10-18 10:33 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +					node_vector_clear(&args_to_print);
И тут str

2022-10-18 10:34 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +				node_vector_clear(&args_to_print);
Ин

2022-10-18 10:34 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +			}
Интересно, почему в условии выше str освобождается, а в условии ниже нет? Надо тоже освобождать

2022-10-18 10:35 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +		node_vector_clear(&args_to_print);
И здесь str освободить

2022-10-18 10:35 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +			node_vector_clear(&args_to_print);
И тут str освободить

2022-10-18 10:36 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +			node_vector_clear(&args_to_print);
И тут str освободить

2022-10-18 10:36 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +			node_vector_clear(&args_to_print);
И тут str освободить

2022-10-18 10:36 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +					node_vector_clear(&args_to_print);
И тут str освободить

2022-10-18 10:36 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +					return node_broken();
И тут str освободить

2022-10-18 10:37 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +				node_vector_clear(&args_to_print);
И тут str освободить

2022-10-18 10:37 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +		node_vector_clear(&args_to_print);
И тут str освободить

2022-10-18 10:40 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +
Это к первому замечанию дополнение. Если один из типов undefined, то не нужно кидать ошибки (они отловились ниже). Надо сравнивать, если и там, и там pointer, но один из них это pointer на undefined, то тогда true

2022-10-18 10:41 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +							 : (location){ op_loc.begin, node_get_location(operand).end };
Можно, пожалуйста, заставить ide так не делать

2022-10-18 10:42 UTC, IvanArkhipov1999 commented on libs/compiler/builder.c
> +						const location if_loc)
Опять всё съехало

2022-10-18 15:23 UTC, IvanArkhipov1999 reviewed
Тесты падают, потому что в кодогенераторах не реализованы операции с массивами. Эти тесты надо вынести в отдельные папки и откорректировать тестирующую систему

2022-10-18 15:30 UTC, merged