Mips codegenerator
andrey-terekhov/RuC pull request #344
Opened 2022-12-20 13:48 UTC by IvanArkhipov1999

2022-12-20 14:16 UTC, Victor-Y-Fadeev requested changes
- [ ] Файлы в корне это совсем недопустимо, положите их в `libs/compiler` или `libs/compiler/mips`
- [ ] Удалите `mipsgen.c` в корне
- [ ] Перестаньте использовать пробелы для отступов, выровняйте комментарии, весь текст скачет
- [ ] Возможно некоторые комментарии надо преобразовать из `//` в Doxygen формат
- [ ] Пусть кто-нибудь проверит styleguide

2022-12-20 14:16 UTC, Victor-Y-Fadeev commented on .gitlab-ci.yml
> +  - R2LIN
Это что-то странное

2022-12-20 14:16 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +	fclose(file);
Используйте `universal_io`.

2022-12-20 14:16 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +	*/
Используйте `universal_io`. И почему у вас есть такие закоментрованные куски?

2022-12-20 14:16 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +	for (size_t i = 0; i < PRESERVED_FP_REG_AMOUNT/2; i++)
Пробелов бы в деление.

2022-12-20 14:16 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +*/
Выглядит не очень

2022-12-20 14:16 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +	IC_MIPS_CVT_W_S, /**< To convert single FP to fixed point value */
Отступы у нас TAB.

2022-12-20 14:16 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +	R_FS11 /**< Saved registers; their values are preserved across function calls */
Выровняйте и не используйте пробелы

2022-12-20 14:16 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +	 без учёта оптимизаций */
Так по моему не работает

2022-12-20 14:16 UTC, Victor-Y-Fadeev commented on runtimeMIPS/defarr.s
> +	jr $ra
Нет последней строки, что небезопасно при копировании.
Сам файл не должен лежать в корне, кладите его в `libs/compiler`

2022-12-20 14:16 UTC, Victor-Y-Fadeev commented on runtimeMIPS/runtime.s
> +szof:
Сам файл не должен лежать в корне, кладите его в `libs/compiler` или `libs/compiler/mips`

2022-12-20 14:16 UTC, Victor-Y-Fadeev commented on mipsgen.c
> +/*
А это вообще что за файл и что он тут делает?

2022-12-20 14:16 UTC, Victor-Y-Fadeev commented on libs/compiler/mipsgen.c
> +}
Перенос строки добавьте

2022-12-22 11:22 UTC, IvanArkhipov1999 commented on runtimeMIPS/defarr.s
> +	jr $ra
А лучше забить его содержимое в какую-нибудь переменную, чтобы exeшник мог запускаться откуда угодно и не зависел от расположения этого файла

2022-12-22 11:22 UTC, IvanArkhipov1999 commented on runtimeMIPS/runtime.s
> +szof:
А лучше забить его содержимое в какую-нибудь переменную, чтобы exeшник мог запускаться откуда угодно и не зависел от расположения этого файла

2022-12-22 11:26 UTC, Victor-Y-Fadeev commented
Супер большое замечание - если файлы не будут лежать рядом с транслятором, то работать не будет. Следовательно вам надо копировать их в выходную папку во время сборки и упаковывать вместе с транслятором.

2023-01-09 18:28 UTC, merged