Fix binexpr
andrey-terekhov/RuC pull request #358
Opened 2023-02-13 15:48 UTC by IgnatSergeev

2023-02-21 12:14 UTC, bugdea1er commented on libs/compiler/mipsgen.c
>  		const rvalue *const var_rvalue = (second_operand->kind == RVALUE_KIND_CONST) ? first_operand : second_operand;
Лучше различать левый и правый операнды, поотму что иначе эта логика различать rvalue тянется слишком далеко

2023-03-14 14:28 UTC, bugdea1er requested changes

2023-03-14 14:28 UTC, bugdea1er commented on libs/compiler/mipsgen.c
> + */
Нужно понятнее писать

2023-03-14 14:28 UTC, bugdea1er commented on libs/compiler/mipsgen.c
> +				if ((operator == BIN_ADD || operator == BIN_OR || operator == BIN_XOR || operator == BIN_AND) && first_operand->kind == RVALUE_KIND_CONST)
Объявление change_order можно сюда и присвоить ей условие if

2023-03-14 14:28 UTC, bugdea1er commented on libs/compiler/mipsgen.c
>  				bool in_reg = false;
Переименовать, чтобы было понятнее и разобраться, почему два if

2023-03-28 14:32 UTC, IvanArkhipov1999 commented on libs/compiler/mipsgen.c
> +			return *operand;
В один тернарный можно

2023-03-28 14:42 UTC, merged