Error standardization
andrey-terekhov/RuC pull request #58
Opened 2020-12-16 12:29 UTC by Egor-Anikin

Смотреть только файл .../preprocessor/errors.c

2020-12-18 15:31 UTC, Victor-Y-Fadeev requested changes
Также отсутствует интерфейс ошибок, документация и не проходят тесты.

2020-12-18 15:31 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +#include <math.h>
Зачем здесь эти библиотеки?

2020-12-18 15:31 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +#include <string.h>
Это можно убрать.

2020-12-18 15:31 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +#include <stdlib.h>
Стоит проверить необходимость этой.

2020-12-18 15:31 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +
Здесь должно быть 2 отступа.

2020-12-18 15:31 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +#define TAG_RUC_MACRO "ruc-macro: "
Откуда такой тег? Как же переносимость препроцессора, имя не должно содержать `RUC`. Двоеточие и пробел тоже не нужны. Должно быть:
```c
#define TAG_MACRO "macro"
```

2020-12-18 15:31 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +
Двойной отступ.

2020-12-18 15:31 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +void get_message_error(int ernum, char *msg)
Указатель `msg` не изменяется, пропущено `const`, должно быть `char *const msg`.

2020-12-18 15:31 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +		{
Зачем здесь блок, переменные же не создаются?

2020-12-18 15:31 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +void m_error(int ernum, const char *name, size_t line_number, const char *line, size_t position)
Несоответствие интерфейсу:
- Название функции должно быть `macro_error`
- Сокращение `ernum` неприемлемо, как минимум потому что неграмотно, лучше просто `num`
- Вместо `name` лучше использовать `path`, также указатель не сделан константным
- Следующим параметром лучше передать код, а не номер и использовать имя `code` (из-за цикла с пропусками)
- Номер строки тогда можно назвать просто `line`, должен быть константой

Итого:
```c
void macro_error(const int num, const char *const path, const char *const code, const size_t line, size_t position)
```

2020-12-18 15:31 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +	char tag[STRIGSIZE] = TAG_RUC_MACRO;
Откуда константа (лучше сверху переопределить, по аналогии с компилятором)?

2020-12-18 15:31 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +	size_t index = strlen(tag);
Неэффективное решение, двойной проход. Стоит использовать:
```c
size_t index = sprintf(tag, "%s", name);
```

2020-12-18 15:31 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +		|| line[position] == '\r' || line[position] == '\n'))
Если пропускать эти символы номер строки сдвинется, некорректно.

2020-12-18 15:31 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +	char msg[STRIGSIZE];
Размер сообщения обычно больше тега (см. выше).

2020-12-19 13:53 UTC, Egor-Anikin commented on libs/preprocessor/error.c
> +void m_error(int ernum, const char *name, size_t line_number, const char *line, size_t position)
Стоит проверить интерфейс  error libs/compiler/error

2020-12-21 12:12 UTC, Victor-Y-Fadeev requested changes

2020-12-21 12:12 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +
Лишний отступ.

2020-12-21 12:12 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +	char msg[STRIGSIZE];
Проблема не решена!

2020-12-21 12:12 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +		|| code[position] == '\r' || code[position] == '\n'))
Если пропускать эти символы номер строки сдвинется, некорректно.
Проблема не решена!

2020-12-21 12:12 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +void get_message_error(int ernum, char *const msg)
Некорректное имя и тип `int ernum`, сокращение error - это `err`. Также пропущено `const`. Должно быть:
```c
const int num
```

2020-12-21 12:12 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.h
> + *http://www.apache.org/licenses/LICENSE-.
Повреждена лицензия.

2020-12-21 12:12 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.h
> + *	Copyright  Andrey Terekhov, Egor Anikin
Не указан год.

2020-12-21 12:12 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.h
> +	ident_begins_with_s,//
Зачем здесь комментарии?

2020-12-21 12:12 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.h
> +	preproces_words_not_exist,//
Аналогично.

2020-12-21 12:12 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.h
> + *	@param	path		Path current file
Неправильный порядок слов, лучше `Current file path`.

2020-12-21 12:12 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.h
> +void macro_error(const int num, const char *const path, const size_t line, const char *const code, size_t position);
Неправильный порядок аргументов. Не исправлено!

2020-12-22 14:34 UTC, Egor-Anikin commented on libs/preprocessor/error.h
> +void macro_error(const int num, const char *const path, const size_t line, const char *const code, size_t position);
Почему он должен быть именно таким ?

2020-12-22 14:35 UTC, Egor-Anikin commented on libs/preprocessor/error.c
> +		|| code[position] == '\r' || code[position] == '\n'))
Читай код внимательно это на номер строки не влияет.

2020-12-22 14:39 UTC, Egor-Anikin commented on libs/preprocessor/error.c
> +	char msg[STRIGSIZE];
Все сообщения влезают, в будущем больших сообщений не предполагается, учитывая что в тег входит путь к файлу он тоже как правило не маленький.

2020-12-23 13:54 UTC, Victor-Y-Fadeev commented on libs/preprocessor/preprocessor.c
> +	int rez = preprocess_h_file(&context);
`res`, от `result` + переменная не нужна.

2020-12-23 13:54 UTC, Victor-Y-Fadeev commented on libs/preprocessor/preprocessor.c
> +	if (rez)
Можно:
```c
   if (preprocess_h_file(&context))
```

2020-12-23 13:54 UTC, Victor-Y-Fadeev commented on libs/preprocessor/preprocessor.c
> +	if (rez)
Аналогично.

2020-12-23 13:54 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.h
> +void macro_error(const int num, const char *const path, const size_t line, const char *const code, size_t position);
Не решено. Не соответствия.

2020-12-23 13:54 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +#define TAG_MACRO "macro"
Нет табов для выравнивания аргументов.

2020-12-23 13:54 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +{
Где проверка входных аргументов?

2020-12-23 13:54 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +	 code[position] == '\n'))
Проблема та же.

2020-12-23 13:54 UTC, Victor-Y-Fadeev commented on libs/preprocessor/error.c
> +	 code[position] == '\n'))
Нет проверки на односточоность переменной `code`.

2020-12-24 14:27 UTC, merged