Рефакторинг сканера
andrey-terekhov/RuC pull request #61
Opened 2020-12-24 19:34 UTC by bugdea1er

- Добавлены функции utf8_is_letter и utf8_is_digit, теперь они используются вместо старых
- Функция чтения лексем разделена на более короткие функции
- Добавлено распознавание новых ошибок, теперь сканер умеет восстанавливаться после их обнаружения
- Ненужные поля удалены из analyzer

2020-12-24 22:00 UTC, Victor-Y-Fadeev reviewed
В общем хорошо, но есть еще пара вопросов/замечаний (см. ревью).

2020-12-24 22:12 UTC, bugdea1er commented on libs/compiler/analyzer.h
> +	struct { int fst; int snd; } numr;	/**< Value of the read double number */
Только для того, чтобы объявление поместилось в одну строку

2020-12-24 23:10 UTC, Victor-Y-Fadeev requested changes
Глобально нет проверки входных аргументов, банально на `NULL`:
```c
char32_t get_char(analyzer *const context);
int lex(analyzer *const context);
```

И еще есть ошибки под Visual Studio 19:
```cmd
  analyzer.c
D:\Desktop\r\libs\compiler\analyzer.c(78,52): error C2220: следующее предупреждение рассматривается как ошибка [D:\Desktop\r\build\libs\compiler\compiler.vcxproj]
D:\Desktop\r\libs\compiler\analyzer.c(78,52): warning C4267: =: преобразование из "size_t" в "int"; возможна потеря данных [D:\Desktop\r\build\libs\compiler\compiler.vcxproj]
D:\Desktop\r\libs\compiler\analyzer.c(80,50): warning C4267: return: преобразование из "size_t" в "int"; возможна потеря данных [D:\Desktop\r\build\libs\compiler\compiler.vcxproj]
  scanner.c
D:\Desktop\r\libs\compiler\scanner.c(120,27): error C2220: следующее предупреждение рассматривается как ошибка [D:\Desktop\r\build\libs\compiler\compiler.vcxproj]
D:\Desktop\r\libs\compiler\scanner.c(120,27): warning C4267: =: преобразование из "size_t" в "int"; возможна потеря данных [D:\Desktop\r\build\libs\compiler\compiler.vcxproj]
D:\Desktop\r\libs\compiler\scanner.c(127,28): warning C4267: =: преобразование из "size_t" в "int"; возможна потеря данных [D:\Desktop\r\build\libs\compiler\compiler.vcxproj]
D:\Desktop\r\libs\compiler\scanner.c(138,44): warning C4267: =: преобразование из "size_t" в "int"; возможна потеря данных [D:\Desktop\r\build\libs\compiler\compiler.vcxproj]
D:\Desktop\r\libs\compiler\scanner.c(139,49): warning C4267: =: преобразование из "size_t" в "int"; возможна потеря данных [D:\Desktop\r\build\libs\compiler\compiler.vcxproj]
D:\Desktop\r\libs\compiler\scanner.c(356,23): warning C4267: =: преобразование из "size_t" в "int"; возможна потеря данных [D:\Desktop\r\build\libs\compiler\compiler.vcxproj]
```

2020-12-24 23:10 UTC, Victor-Y-Fadeev commented on libs/compiler/scanner.h
> + *	Lex next token from io
Что такое `Lex`? Некорректное предложение, в документации не стоит использовать сокращения.

2020-12-24 23:10 UTC, Victor-Y-Fadeev commented on libs/compiler/scanner.c
> +		int exp = 0;
Это экспонента или степень (`power`)?

2020-12-24 23:43 UTC, Victor-Y-Fadeev approved these changes

2020-12-25 00:07 UTC, Victor-Y-Fadeev commented
Увеличилось число наведенных ошибок (было-стало):
```bash
 success = 495, warning = 98, failure = 0, timeout = 0
 success = 486, warning = 107, failure = 0, timeout = 0
```

2020-12-25 14:34 UTC, Victor-Y-Fadeev commented
![изображение](https://user-images.githubusercontent.com/23136222/103137131-5c934380-46d7-11eb-988b-f856fb303aa5.png)

2020-12-25 14:34 UTC, Victor-Y-Fadeev commented
![изображение](https://user-images.githubusercontent.com/23136222/103137139-687f0580-46d7-11eb-85cd-43061f684332.png)

2021-01-06 12:58 UTC, bugdea1er commented
- Лексер вынесен в отдельную структуру.
- Добавлен отдельный класс для токенов. На данный момент все константы перечисления инициализированы старыми значениями из defs для обратной совместимости.
- repr вынесен из syntax, hashtab  и keywordsnum добавлены в syntax. hashtab нужна только для работы reprtab, а после запланированного изменения меток вообще не нужна будет снаружи syntax. Переменная keywordsnum нужна только для инициализации reprtab.
- Добавлен интерфейс для reprtab. Предлагается следующий сценарий работы: структура syntax создается до работы препроцессора, syntax.reprtab инициализируется всеми ключевыми словами, в последнюю очередь словами препроцессора. После работы препроцессора из reprtab необходимо убрать добавленные идентификаторы и ключевые слова препроцессора (для reprtab надо просто сдвинуть rp, чуть-чуть подправить hashtab).
- Препроцессору предлагается вариант работы с reprtab, который используется в анализаторе: при вызове функции добавления идентификатора в reprtab она возвращает ссылку на запись в этой таблице, вне зависимости от того, была она там раньше или нет. Если идентификатор встречается в первый раз, то в поле repr+1 будет стоять 1. В анализаторе это поле используется для того, чтобы отличать встреченные ранее идентификаторы от появившихся впервые: 1 - если не был встречен ранее, любое другое положительное значение - уже был встречен. Именно так и предлагается препроцессору отличать новые идентификаторы от старых

Этих изменений вроде как должно хватить для того, чтобы препроцессор обращался к исходному файлу только через лексер.

2021-01-11 03:44 UTC, Victor-Y-Fadeev requested changes
Изменения осмысленные, но пока вы не исправите основную проблему, я не могу их принять.

Пожалуйста установите виртуалку с ОС Windows и [Build Tools for Visual Studio 2019](https://visualstudio.microsoft.com/ru/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16).
Для удобства отладки воспользуйтесь `gdb` из пакета [MinGW](https://sourceforge.net/projects/mingw/). 
Команды сборки:
```
$ mkdir build && cd build && cmake .. -A Win32 && cd ..
$ cmake --build build --config Debug
$ gdb --args build\Debug\ruc.exe tests\errors\compiler\too_long_string\337_elements.c
```

![image](https://user-images.githubusercontent.com/23136222/104145375-d3b72000-53d7-11eb-8c02-dd531586bb9e.png)

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/lexer.c
> + *	Copyright 2014 Andrey Terekhov, Ilya Andreev
А год точно верный?

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/lexer.c
> +
Здесь двойной отступ.

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/lexer.c
> +	if (err == bad_character)
Не проще ли его добавить в глобальный `enum`?

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/extdecl.c
>  	int numofparams = 0;
Пожалуйста ставьте разделители, `num_of_params`.

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/extdecl.c
> +			if (fsi = (int)formatstr[++i], fsi != '%')
Что значит `fsi`? И почему бы его самого не сделать `char32_t`.

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/lexer.c
> +		lexer->repr = repr;
Нет приведения типов, вы сделали `lexer->repr` типа `int`.

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/extdecl.c
> +		context->stackoperands[++context->sopnd] = context->ansttype = newdecl(context->sx, MARRAY, LCHAR);
А нельзя это разбить на 2 строки?

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/extdecl.c
> +			totree(context, (int)context->lexer->lexstr[i]);
Зачем здесь приведение типов?
P.s. `int` и `char32_t` имеют одинаковый размер.

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/analyzer.c
> +	context.lexer->io = io;
Если уж на то пошло, то внешняя инициализация не лучшее решение.

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +	size_t hash = 0;
Если вы хотите сменить тип хешей на беззнаковый, то выбирайте тип по размеру. Для 256 вполне хватить 1 байтового `uint8_t`, сейчас же вы тратите память на 8 байтный `size_t` (для Win32/Unix систем).

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.h
> +	int hash;					/**< Last value of hash function */
Используйте `uint8_t`.

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.h
> +	int keywordsnum;
Нет комментария.

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.h
> + *	@param	index		Index of record in representations table
Проверяйте текст после копирования)

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.h
> + *	Get a representation spelling from representations table by index
Второе название таблицы можно опустить.

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.h
> +int repr_get_spelling(const syntax *const sx, size_t index, char32_t *const spelling);
Индекс стоит сделать константным.

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.h
> + *	Get a representation reference from representations table by index
Аналогично про повторение.

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.h
> +int repr_get_reference(const syntax *const sx, const size_t index);
Почему ссылка типа `int`? Если это индекс в массиве, то должно быть `size_t` с константой `MAX_SIZE`.

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.h
> + *	Set representation reference by index in representations table
Повторение.

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +		sx.hashtab[i] = 0;
Точно стоит делать это `0`? Может `INT_MAX` или `SIZE_MAX`?

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +				sx->rp = old_repr;
Отсутствует приведение типов.

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +	sx->reprtab[old_repr] = sx->hashtab[hash];
Приведение типов... Пожалуйста проверяйте на MSVC 19.

2021-01-11 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +	int i = 0;
Смените тип.

2021-01-11 03:47 UTC, Victor-Y-Fadeev commented
Также для вашего удобства, обновите свою рабочую ветку, во избежание проблем с кодировками!

2021-01-12 16:23 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	uni_printf(io, "%i %i %i %lu %i %i %i\n", sx->pc, sx->funcnum, sx->id,
Используйте `%zi` для печати `size_t`, иначе получите несовместимость с Windows.

2021-01-12 16:25 UTC, Victor-Y-Fadeev commented on libs/compiler/tokens.h
> +typedef enum Token
Есть другое предложение?

2021-01-12 16:32 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.h
> +	int hash;					/**< Last value of hash function */
Все еще актуально.

2021-01-12 16:34 UTC, Victor-Y-Fadeev commented on libs/compiler/errors.c
> +
А где `break`?

2021-01-12 16:38 UTC, Victor-Y-Fadeev commented on libs/compiler/analyzer.c
> +	context.lexer->io = io;
Стоит обсудить.

2021-01-12 21:51 UTC, Victor-Y-Fadeev commented on libs/compiler/errors.c
> +
Если посмотрите на остальные блоки, то должно быть так:
```c
	case bad_character:
	{
		const char32_t bad_char = va_arg(args, char32_t);
		sprintf(msg, "плохой символ = %i", bad_char);
	}
	break;
```

2021-01-12 21:57 UTC, Victor-Y-Fadeev approved these changes

2021-01-12 22:08 UTC, Victor-Y-Fadeev commented
Отлично, одной проблемой меньше. Вы успешно решили ошибки с тестом `337_elements.c`, но остались еще тесты:
```
 compiling warning : ../tests/errors/ASCII/input/getid/arrays/max/miller.c
 compiling warning : ../tests/errors/ASCII/input/getid/arrays/sort/miller.c
 compiling warning : ../tests/errors/ASCII/input/getid/math/integral/miller.c
 compiling warning : ../tests/errors/ASCII/input/getid/math/sqrt/miller.c
 compiling warning : ../tests/errors/ASCII/input/getid/switch/miller.c
```

Которые падают с:
```cmd
Program received signal SIGSEGV, Segmentation fault.
0x737d1d1f in compiler!compile_to_vm () from D:\Desktop\scan\build32\Debug\compiler.dll 
```

2021-01-14 01:13 UTC, merged