Refactoring multi-file
andrey-terekhov/RuC pull request #66
Opened 2021-01-12 20:05 UTC by Egor-Anikin

2021-01-14 23:45 UTC, Victor-Y-Fadeev requested changes
В общем все плохо, я потратил на чтение этого запроса очень много времени. Мне банально неприятно читать неграмотный текст. Пользуйтесь словарем, переводчиком, проверяйте себя, а также соблюдайте хоть какой-нибудь стайлгайд (в wiki проекта есть базовое описание и очень давно).

Также создается впечатление, что запрос был создан сразу как собралось и в результате я был вынужден потратить свое время на бесконечные проверки грамматики. Я верю, что вы могли бы справится с этим и сами, проверяйте код перед отправкой на ревью.

2021-01-14 23:45 UTC, Victor-Y-Fadeev commented on libs/preprocessor/multi_file.c
> +void mf_gen_way(char *full, const char *path, const char *file, int is_slash)
Следует переписать функцию:
```c
void linker_make_path(char *const output, const char *const source, const char *const header, const int is_slash)
{
	size_t index = 0;

	if (is_slash)
	{
		char *slash = strrchr(source, '/');
		if (slash != NULL)
		{
			index = slash - source + 1;
			strncpy(output, source, index);
		}
	}
	else
	{
		index = sprintf(output, "%s/", source);
	}
	
	strcpy(&output[index], header);
}
```

2021-01-14 23:45 UTC, Victor-Y-Fadeev commented on libs/preprocessor/multi_file.c
>  	if (res == -1)
Здесь не нужен `res`, есть функция `in_is_correct`, должно быть так:
```c
if (!in_is_correct(env->input))
```

2021-01-14 23:45 UTC, Victor-Y-Fadeev commented on libs/preprocessor/multi_file.c
>  	}
- Переменную лучше назвать `header`
- Создавать `res` не нужно
- Индексы в массиве имеют тип `size_t`
- Зачем префикс `temp`, папка тут одна

Итого:
```c
char header[MAX_ARG_SIZE];
linker_make_path(header, ws_get_file(env->lk.ws, env->lk.current), path, 1);

if (in_set_file(env->input, header))
{
	size_t i = 0;
	const char *dir = ws_get_dir(env->lk.ws, i++);
	linker_make_path(header, dir, path, 0);

	while (dir != NULL && in_set_file(env->input, header))
	{
		linker_make_path(header, dir, path, 0);
		dir = ws_get_dir(env->lk.ws, i++);
	}
}
```

2021-01-14 23:45 UTC, Victor-Y-Fadeev commented on libs/preprocessor/multi_file.c
> +	size_t index = ws_add_file(context->fs.ws, full_path);
Не `size_t`, а `const size_t`.

2021-01-14 23:45 UTC, Victor-Y-Fadeev commented on libs/preprocessor/multi_file.c
> +		return -1;
Лишний отступ и здесь:
```c
return SIZE_MAX - 1;
```

2021-01-14 23:45 UTC, Victor-Y-Fadeev commented on libs/preprocessor/multi_file.c
> +		return -2;
```c
return SIZE_MAX;
```

2021-01-14 23:45 UTC, Victor-Y-Fadeev commented on libs/preprocessor/multi_file.c
> +	if(index < context->fs.end_sorse && !context->fs.already_included[index])
Пропущен пробел!

2021-01-14 23:45 UTC, Victor-Y-Fadeev commented on libs/preprocessor/multi_file.c
> +	else if(num == ws_get_files_num(context->fs.ws))
Пробел!

2021-01-14 23:45 UTC, Victor-Y-Fadeev commented on libs/preprocessor/preprocessor.c
>  	context.mfirstrp = context.rp;
Что это делает снаружи?

2021-01-14 23:45 UTC, Victor-Y-Fadeev commented on libs/preprocessor/preprocessor.c
> +		in_clear(&io_input);
По сути это функция - "Сделать все!", тогда уж и инициализацию стоит туда перенести.
Также нужно подумать о роли окружения, выходит снаружи оно требуется только для ключевых слов.
И еще, очистка и вообще весь `input` стоит перенести внутрь.

2021-01-23 14:48 UTC, Egor-Anikin commented on libs/preprocessor/define.c
> +		return function_add_to_macrotext(context);
Работа с define.c не относится к рефакторингу Многофайловости

2021-01-23 14:49 UTC, Egor-Anikin commented on libs/preprocessor/define.c
>  		return define_add_to_macrotext(r, context);
Работа с define.c не относится к рефакторингу многофайловости

2021-01-23 14:49 UTC, Egor-Anikin commented on libs/preprocessor/define.c
>  int set_relis(preprocess_context *context)
Работа с define.c не относится к рефакторингу Многофайловости

2021-01-23 14:51 UTC, Egor-Anikin commented on libs/preprocessor/context_var.h
Это тоже относится к общему рефакторингу.

2021-01-23 15:03 UTC, Egor-Anikin commented on libs/preprocessor/multi_file.c
> +int mf_open_file(preprocess_context *context)
Некорректное название будет lk_process_include_file

2021-01-23 15:20 UTC, Egor-Anikin commented on libs/preprocessor/multi_file.c
>  	if (res == -1)
Нужен, без него много лишних действий и он ничего не стоит.

2021-01-23 15:35 UTC, Egor-Anikin commented on libs/preprocessor/preprocessor.c
>  	context.mfirstrp = context.rp;
Не относится к делу.

2021-01-23 15:36 UTC, Egor-Anikin commented on libs/preprocessor/preprocessor.c
> +		in_clear(&io_input);
Уже обсудили.

2021-01-31 08:35 UTC, Victor-Y-Fadeev requested changes
Для начала все комментарии формата "не относится к делу" отклоняются! Я потратил свое рабочее время на чтение, проверку и разбор вашего кода, поэтому будьте добры учесть мои замечания. Я совершенно не хочу делать одну и ту же работу по 10 раз (вам все равно придется внести эти исправления, рано или поздно). Особенно это касается замечаний по сталгайду: оформление, именование и т.д. Исправление этих замечаний не должно занимать много времени, для справки, пользуйтесь встроенной в `VS Code` функцией рефакторинга (клавиша `F2`).

Следующее, как я уже говорил, проверяйте код перед отправкой на ревью самостоятельно. Почему я должен повторяться касательно одних и тех же замечаний, причем в том же самом месте.

Так как в этом ревью я тщательно проверял только `linker`, то по остальному коду следующие замечания:
- Уберите прямое обращение к полям структуры из других библиотек `ws_get_file(env->lk.ws, env->lk.current)`, это неприемлемо (сделайте функцию, принимающую `linker`)
- Исправьте неграмотные имена, хотя бы те о которых я уже говорил, естественно это касается и их аналогов в других файлах

И напоследок, чем больше вы вносите изменений не сделав `merge` из целевой ветки, тем больше усложняете себе работу в будущем. Я все равно не приму запрос с конфликтами, к тому же он не проходит тесты. Для сравнения, на прошлом ревью у вас были конфликты слияния только в одном файле, теперь же в пяти.

2021-02-04 21:33 UTC, Egor-Anikin commented on libs/preprocessor/environment.c
> +	env->position = 0;
Это действие не нужно, на данном этапе нужно сохранить строчку в изначальном виде.

2021-02-04 21:34 UTC, Egor-Anikin commented on libs/preprocessor/linker.c
> +	env_clear_error_string(env);
Хорошо перенесу, однако в lk_preprocess_all оно не потеряно, оно не нужно.

2021-02-06 12:16 UTC, Victor-Y-Fadeev commented on libs/preprocessor/linker.c
> +		if (lk_preprocess_file(env, i))
Я конечно очень рад, что вы убрали присвоения во внутрь, но я не просто так сказал, что минимум - это убрать только счетчик... Оно вообще работает?

2021-02-06 12:16 UTC, Victor-Y-Fadeev commented on libs/preprocessor/linker.c
> +	env->input = &in;
Вы в курсе что этим сломали `lk_preprocess_include`?

2021-02-06 12:16 UTC, Victor-Y-Fadeev commented on libs/preprocessor/linker.c
> +	}
Тоже самое про `lk_preprocess_include`.

2021-02-06 12:16 UTC, Victor-Y-Fadeev commented on libs/preprocessor/linker.c
> +int lk_open_source(environment *const env, size_t const index)
Уже вот совсем не смешно... Научитесь работать с `const`, он ставится в начале (если это не указатель).

2021-02-06 12:16 UTC, Victor-Y-Fadeev commented on libs/preprocessor/linker.c
> +	env_clear_error_string(env);
На первом ревью оно было.

2021-02-06 15:05 UTC, Egor-Anikin commented on libs/preprocessor/linker.h
> +	size_t count; 				/**< Number of source files */
Нет, данная переменная необходима для того чтобы отделить исходные и добавочные.

2021-02-06 15:49 UTC, Victor-Y-Fadeev reviewed
Стало лучше, все еще хочется сказать о самопроверке и перечитывании старых замечаний (те что открыты). Также стали заметны проблемы с логикой в некоторых местах, поэтому проведите многофайловые тесты и проверьте вывод ошибок макрогенератора в них.

2021-02-06 15:49 UTC, Victor-Y-Fadeev commented on libs/preprocessor/file.h
> +void pred_fprintf(int a, environment *const env);
Удалить, нет реализации и ошибка в имени!

2021-02-06 15:49 UTC, Victor-Y-Fadeev commented on libs/preprocessor/if.h
> +int if_realiz(environment *const env);
Ужас, вот серьезно, ну если проблемы с написанием этого слова почему нельзя было посмотреть в словарь?

Ни слова `relis`, ни `realiz` не существует. Если вы имели в виду реализацию, то она пишется `realize`, если выпуск, как в сборке, то `release`. А вообще в программировании реализация - это `implementation`.

2021-02-06 15:49 UTC, Victor-Y-Fadeev commented on libs/preprocessor/define.h
> +int set_realiz(environment *const env);
Словарь в помощь.

2021-02-06 15:49 UTC, Victor-Y-Fadeev commented on libs/preprocessor/while.h
> +int while_realiz(environment *const env);
Словарь!!!

2021-02-06 15:49 UTC, Victor-Y-Fadeev commented on libs/preprocessor/environment.h
>  #include "workspace.h"
Зачем он здесь?

2021-02-06 15:49 UTC, Victor-Y-Fadeev commented on libs/preprocessor/environment.c
> +#include <string.h>
Это все можно выкинуть, оставив только имя самой библиотеки.

2021-02-06 15:49 UTC, Victor-Y-Fadeev commented on libs/preprocessor/environment.h
>  #include <stdio.h>
Вопрос все еще открыт!

2021-02-06 15:49 UTC, Victor-Y-Fadeev commented on libs/preprocessor/environment.h
> +void env_init(environment *const env, workspace *const ws, universal_io *const output);
Лучше снаружи создать линкер и передать его, а не `workspace`.

2021-02-06 15:49 UTC, Victor-Y-Fadeev commented on libs/preprocessor/utils.h
> +void output_keywods(environment *env);
`keywords` пишется через `r`.

2021-02-06 15:49 UTC, Victor-Y-Fadeev commented on libs/preprocessor/utils.h
> +int collect_mident(environment *env);
Что такое `mident`?

2021-02-08 15:42 UTC, Egor-Anikin commented on libs/preprocessor/linker.c
> +	const size_t num = ws_get_files_num(env->lk.ws);
Объясняю ещё раз массив included и переменная count нужны чтобы не допустить использование входных (sorse) файлов дважды. В переменную count  записывается их количество а, included отмечены те из них что уже использовались.

2021-02-08 15:44 UTC, Egor-Anikin commented on libs/preprocessor/linker.c
> +	}
Смотри предыдущей комментарий.

2021-02-08 15:49 UTC, Egor-Anikin commented on libs/preprocessor/linker.c
> +const char *lk_get_current(linker* lk)
Перенос в конец откланяется, используется в самом файле linker.c .

2021-02-08 16:04 UTC, Egor-Anikin commented on libs/preprocessor/utils.h
> +int collect_mident(environment *env);
Функция которой я планирую заняться на следующий итерации (интеграция map).

2021-02-09 04:07 UTC, Victor-Y-Fadeev reviewed
По стайлгайду стало значительно лучше, осталось совсем чуть чуть. А вот по логике следует внести правки. Да, конечно этот код работает и ошибки тут нет, но он сложен к пониманию, использует ненужные абстракции и глобальную инициализацию массива, что вызовет проблемы в будущем (например с вектором такой фокус не пройдет).

2021-02-09 04:07 UTC, Victor-Y-Fadeev commented on libs/preprocessor/linker.c
> +	}
Начнем с того что разделения на заголовочные и исходные файлы как такового вообще нет. Вы пытаетесь сказать, что все файлы в `workspace` - это исходные, а те что вы добавляете через `#include` - заголовочные, но это неправда, я могу на вход `workspace` подать заголовочный файл и ничего мне за это не будет. Поэтому сознательного разделения этих файлов здесь не требуется, вам нужно просто аккуратно заполнять массив `included` нужными флагами.

Чтобы не пользоваться массовой инициализацией всех значений вам нужно инициализировать требуемую ячейка во время добавления файла в `workspace`, это как раз здесь. А вот установке флага тут не место, так как функция только открывает файл, но не обрабатывает.

Итого замените этот код на указанный ранее, так как текущий вариант нарушает принцип единственности ответственности и усложняет общее понимание из-за введения лишних абстракций.

P.s. `lk->count` у вас вообще используется только 3 раза за весь проект, включая этот и инициализацию.

2021-02-09 04:07 UTC, Victor-Y-Fadeev commented on libs/preprocessor/linker.h
> +	size_t count; 				/**< Number of source files */
И зачем же их отделять? Особенно с учетом того, что это невозможно, я запросто могу передать в `workspace` один из заголовочных файлов и никак вы его оттуда не вытащите.

2021-02-09 04:09 UTC, Victor-Y-Fadeev commented
И вот вам тест для отладки.

2021-02-09 08:59 UTC, Victor-Y-Fadeev reviewed
Еще раз.

2021-02-09 08:59 UTC, Victor-Y-Fadeev commented on libs/preprocessor/environment.c
> +
2 отступа в конце.

2021-02-09 08:59 UTC, Victor-Y-Fadeev commented on libs/preprocessor/environment.c
> +
Лишний отступ

2021-02-09 08:59 UTC, Victor-Y-Fadeev commented on libs/preprocessor/linker.c
> +	env->lk->included[number]++;
Не перенесено.

2021-02-09 08:59 UTC, Victor-Y-Fadeev commented on libs/preprocessor/linker.c
> +	env->lk->included[number] = 1;
Предполагалось перенести сюда 154 строчку:
```c
env->lk->included[number]++;
```

2021-02-09 08:59 UTC, Victor-Y-Fadeev commented on libs/preprocessor/linker.c
> +			, env->error_string, env->line, position);
Не исправлено, уже 4 раз говорю.

2021-02-09 08:59 UTC, Victor-Y-Fadeev commented on libs/preprocessor/linker.c
> +	}
Это работать не будет, запрос значения неинициализированной переменной в первом условном операторе!
```c
const size_t index = ws_add_file(env->lk->ws, full_path);
if (index == env->lk->count)
{
	env->lk.included[env->lk->count++] = 0;
}
else if (env->lk->included[index])
{
	in_clear(env->input);
	return SIZE_MAX;
}
```

2021-02-09 09:11 UTC, Egor-Anikin commented on libs/preprocessor/linker.c
> +	env->lk->included[number] = 1;
Нет, возможны добавления в файл самого себя.

2021-02-09 09:15 UTC, Egor-Anikin commented on libs/preprocessor/linker.c
> +	}
Она инициализируется при создании структуры linker. Читайте внимательнее.

2021-02-09 09:21 UTC, Victor-Y-Fadeev commented on libs/preprocessor/linker.c
> +	}
Она инициализируется только до `env->lk->count`, а вот индекс полученный при вызове `ws_add_file` может быть больше этого числа и по нему может быть записано вообще что угодно!

2021-02-09 09:23 UTC, Victor-Y-Fadeev commented on libs/preprocessor/linker.c
> +	env->lk->included[number] = 1;
И в чем проблема? Замените статическое присвоение и в случае ошибки сможете даже отследить этот случай, для работы флагов достаточно того, что там не ноль.

2021-02-09 09:53 UTC, Victor-Y-Fadeev approved these changes

2021-02-09 09:53 UTC, merged