Интерфейс Identab
andrey-terekhov/RuC pull request #68
Opened 2021-01-14 22:10 UTC by bugdea1er

- Добавлен интерфейс для identab
- Некоторые поля пересены в syntax
- Подредактированы некоторые типы в старых функциях

2021-01-16 08:42 UTC, Victor-Y-Fadeev requested changes
Требуются доработки... Вы откуда код `ident_add` взяли? Почему ему так плохо?

2021-01-16 08:42 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +	}
Это какая-то жесть... Вам нужно просто аккуратно разобрать промежутки к в которые попадает `type`, зачем вы опять делаете вложенные `if` на одно и то же? Это крайне сложно читать и понимать.

С комментариями тоже что-то совсем не хорошее, то пробелов нет, то перенос не по смыслу, то формулировка кривая.

Итератор для цикла `for` мы создаем внутри и опять про `size_t` для индексов.

Мне проще правильно написать, чем делать комментарии к каждой строчке:
```c
if (type < 0)
{
	// Так как < 0, это функция-параметр
	ident_set_displ(sx, lastid, -(sx->displ++));
	sx->maxdispl = sx->displ;
}
else if (type == 0)
{
	ident_set_displ(sx, lastid, get_static(sx, mode));
}
else if (type == 1)
{
	ident_set_mode(sx, lastid, 0);	// 0, если первым встретился goto,
					// когда встретим метку, поставим 1
	ident_set_displ(sx, lastid, 0);	// при генерации кода когда встретим метку, поставим pc
}
else if (type >= 1000)
{
	// Это описание типа, а (type - 1000) – это номер инициирующей процедуры
	ident_set_displ(sx, lastid, type);
}
else // if (type > 1 && type < 1000)
{
	// identtab[sx->id + 3] - номер функции
	ident_set_displ(sx, lastid, type);

	if (func_def == 2)
	{
		sx->identab[lastid + 1] *= -1;	// это предописание
		sx->predef[++sx->prdf] = repr;
	}
	else
	{
		for (size_t i = 0; (int)i <= sx->prdf; i++)
		{
			if (sx->predef[i] == repr)
			{
				sx->predef[i] = 0;
			}
		}
	}
}
```

2021-01-16 08:42 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +	if (sx == NULL)
Надо бы еще остальные указатели на `NULL` проверить.

2021-01-16 08:42 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +		sx->reprtab[sx->identab[i + 1] + 1] = sx->identab[i];
У вас есть интерфейс `repr_set_reference`, используйте его.
И почему `sx->identab[i + 1]`?

2021-01-16 08:42 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +	sx->displ = old_displ;
Отступ бы...

2021-01-16 08:42 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +int enter_block_scope(syntax *const sx, int *const old_displ, int *const old_lg)
Убрать `old`.

2021-01-16 08:42 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +int exit_block_scope(syntax *const sx, const int old_displ, const int old_lg)
Убрать `old`.

2021-01-16 08:42 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +	sx->curid = 2; // все функции описываются на одном уровне
Используйте интерфейс `repr_set_reference` и поставьте отступ после цикла.

2021-01-16 08:42 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +int exit_func_scope(syntax *const sx, const size_t pred, const int scope_start)
Исправьте имена переменных.

2021-01-16 08:46 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +		return SIZE_MAX;
Документацию к функции тогда тоже поправьте, а то нехорошо получается.

2021-01-16 09:55 UTC, bugdea1er commented on libs/compiler/extdecl.c
> +	context->sx->tree[all = context->sx->tc++] = 0;														// all
Это же геттер, который для этого и был написан? Он гарантирует, что он сам ничего не изменит

2021-01-16 09:56 UTC, bugdea1er commented on libs/compiler/extdecl.c
> +		context_error(context, more_than_1_main); //--
Комментарий не мой, кажется, его оставил Егор

2021-01-16 09:57 UTC, bugdea1er commented on libs/compiler/codegen.c
> +	tocode(sx, sx->identab[sx->main_ref + 3]);
Использованием интерфейса в кодгене в прошлый раз занимался Иван

2021-01-16 10:11 UTC, bugdea1er commented on libs/compiler/syntax.h
> +size_t ident_add(syntax *const sx, const size_t repr, const int type, const int mode, const int func_def);
> Почему `mode` второй параметр?

Здесь совсем не понял, о чем речь, он же четвертым по счету идет, и в документации тоже вроде все по порядку

> `func_def == 3` - точно `for variables`, а не `for function variables`?

`analyzer.func_def` используется, чтобы различать функции от скаляров. Но вопрос про именование параметра открыт к обсуждению

2021-01-16 10:21 UTC, bugdea1er commented on libs/compiler/syntax.c
> +	sx->main_ref = 0;
Заполнение таблицы начинается со второго индекса: `0` на всякий случай для этой проверки, `1` для неописанных идентификаторов. Для общего вида можно поменять это и на максимальные значения, но думаю, что так все же правильнее

2021-01-16 11:03 UTC, bugdea1er commented on libs/compiler/syntax.c
> +	}
Не пойдет, в разные поля присваивание

2021-01-16 11:07 UTC, bugdea1er commented on libs/compiler/syntax.h
> +int size_of(syntax *const sx, const int mode);
Эта функция и `mem_get_size` выполняют совсем разные задачи. `mem_get_size` возвращает размер таблицы, а `size_of` – размер памяти, который нужно компилятору ruc выделить под переменную данного типа

2021-01-18 02:52 UTC, Victor-Y-Fadeev commented on libs/compiler/extdecl.c
>  int toidentab(analyzer *context, int f, int type)
Нуу, глобально, теперь вся функция под вопросом, все что она делает это выводит ошибки...

P.s. Можно не отвечать, просто чтобы не потерялся вопрос.

2021-01-18 02:52 UTC, Victor-Y-Fadeev commented on libs/compiler/extdecl.c
> +		totree(context, context->anstdispl = ident_get_displ(context->sx, context->lastid));
Тут 2 выражения было. Не решено, задача та же.

2021-01-18 02:52 UTC, Victor-Y-Fadeev commented on libs/compiler/extdecl.c
> +	const size_t return_value = ident_add(context->sx, REPRTAB_POS, f, type, context->func_def);
Обычно мы используем общепринятое сокращение `ret`, но можно и так... Кстати, не хотите в функцию добавить разделителей, а то все слитно?

2021-01-18 02:52 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +}
Не соответствует документации! Переименуйте `error_flag` в `is_correct` и проинициализируйте ее `1`, а при ошибке ставьте `0`. Также уберите отступ перед первым `if`, а перед `return` добавьте.

2021-01-18 02:52 UTC, Victor-Y-Fadeev commented on libs/compiler/compiler.c
> +		ret = sx_is_correct(&sx, io);
По документации так работать не будет, Поставьте НЕ перед вызовом:
```c
ret = !sx_is_correct(&sx, io);
```

2021-01-18 02:52 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.h
> + *			@c SIZE_MAX on "redefinition of main" error
Думаю лучше без кавычек, все равно это не название ошибки (имею в виду `enum` название, не используйте его).

2021-01-18 02:52 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +	}
Понял, не заметил, тогда просто уберите скобки в 30 строке.

2021-01-18 02:52 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +	sx->main_ref = 0;
Если это учитывается то ладно, но что-то мне подсказывает, что в будущем нулевой индекс будет использоваться...

P.s. Просто оставьте комментарий.

2021-01-18 02:52 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +	const size_t prev = sx->identab[lastid] = repr_get_reference(sx, repr);
А вот тройное присвоение не поправили.

2021-01-18 02:52 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +		// Только определение функции может иметь 2 описания, то есть иметь предописани
Букву `е` при копировании потеряли, в конце.

2021-01-18 02:52 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +		// В поле displ: при генерации кода когда встретим метку, поставим pc
Запятая перед ` когда`.

2021-01-18 02:55 UTC, Victor-Y-Fadeev approved these changes

2021-01-18 15:15 UTC, merged