Refactoring
andrey-terekhov/RuC pull request #79
Opened 2021-01-25 15:29 UTC by IvanArkhipov1999

2021-01-25 18:16 UTC, Victor-Y-Fadeev requested changes
Неплохо, но прямая запись в дерево недопустима, это необходимо исправить.

Также интерфейс работы с деревом через `sx` в данном случае не является необходимым, куда лучше передавать `node *const node` параметром (меньше обращений и проверок).

Для подобного использования нужно только заменить функцию `tree_next_node` на `node_set_next`.

P.s. Отказ от хранения `node` в `sx` будет в следующем запросе, пока можете оставить так.

2021-01-25 18:16 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +			tree_next_node(sx);
Здесь отступ должен быть после `tree_next_node`, а не до (для соответствия старому написанию).

2021-01-25 18:16 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
>  	int element_len;
Перенесите к инициализации или саму инициализацию сюда.

2021-01-25 18:16 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +	{
`TAB` в конце строки - это плохо.

2021-01-25 18:16 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
>  				int i;
Инициализацию счетчика внутрь цикла.

2021-01-25 18:16 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
>  				int i;
Счетчик внутрь цикла.

2021-01-25 18:16 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +				int numproc = sx->tree[node_get_arg(tree_get_node(sx), 0) + 1];
Прямая запись в дерево запрещена.

2021-01-25 18:16 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
> +			int numproc = sx->tree[node_get_arg(tree_get_node(sx), 0) + 1];
Прямая запись запрещена.

2021-01-25 18:16 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
>  			break;
Количество операторов `>1`, создайте блок:
```c
case TBegin:
{
	tree_next_node(sx);
	compstmt_gen(sx, context);
	break;
}
```

2021-01-25 18:17 UTC, Victor-Y-Fadeev commented
И подписывайте запросы более содержательно (можно даже по-русски), называть их все `Refactoring` нехорошо.

2021-01-26 15:28 UTC, IvanArkhipov1999 commented on libs/compiler/codegen.c
> +				eltype = node_get_arg(tree_get_node(sx), (node_get_type(tree_get_node(sx)) == TSlice) ? 0 : 1);
Блок TSlice отвечает не только за обработку TSlice, но и за часть обработки TSliceident, о чём написано в комментариях. Из-за этого в eltype нужно получать значение нулевого аргумента узла в случае TSlice и первого аргумента узла в случае TSliceident. Имя eltype означает тип элемента.

2021-01-27 16:48 UTC, Victor-Y-Fadeev approved these changes

2021-01-27 16:49 UTC, merged