Кодогенератор llvm. Реализация printf.
andrey-terekhov/RuC pull request #86
Opened 2021-02-08 14:17 UTC by IvanArkhipov1999

2021-02-13 17:33 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen_llvm2.c
> +            int n = node_get_arg(nd, 0);
```c
const item_t N = node_get_arg(nd, 0);
```

2021-02-13 17:37 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen_llvm2.c
> +            int args[100];
Скажите мне, зачем вам вообще этот массив?

2021-02-13 17:43 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen_llvm2.c
> +            uni_printf(io, ")\n");
Нет отступа, пропущены пробелы, нет тела, в общем это должно выглядеть как-то так:
```c
uni_printf(info->io, " %%.%i = call i32 (i8*, ...) @printf(i8* getelementptr inbounds "
	"([%i x i8], [%i x i8]* @.str%i, i32 0, i32 0)"
	, info->register_num++
	, string_length + 1
	, string_length + 1
	, info->string_num++);

for (item_t i = 0; i < N; i++)
{
	info->bvar = 0;
	expression(info, nd);
	uni_printf(info->io, ", i32 signext %%.%i", info->areg);
}
uni_printf(info->io, ")\n");
```

2021-02-13 17:45 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen_llvm2.c
> +        break;
Ничего что они вообще одинаковые? Проблемы как всегда: `const`, `item_t`, отсутствие тела...

2021-02-13 17:46 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen_llvm2.c
> +            case TStructend:
Прикольно конечно их пропускать, но мне кажется тут что-то не так...

2021-02-13 17:47 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen_llvm2.c
> +    do
Точно `do`? А если я вот такой классный код напишу:
```c
{}
```

2021-02-13 17:48 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen_llvm2.c
> +                int ref_ident = node_get_arg(nd, 0) / 4;
`const item_t`

2021-02-13 17:50 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen_llvm2.c
> +                uni_printf(io, ") {\n");
Для начала нет тела, и это нормально что у вас посередине кода закрывающаяся скобка ставится? Она не отклеилась от `main`?

2021-02-13 17:51 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen_llvm2.c
> +                int n = node_get_arg(nd, 0);
```c
const item_t N = node_get_arg(nd, 0);
```

2021-02-13 17:51 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen_llvm2.c
> +                    expression(io, sx, nd, context);
Нет тела.

2021-02-13 17:52 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen_llvm2.c
> +                    N = node_get_arg(nd, 2), all = node_get_arg(nd, 3);
Ой как не хорошо так делать. Одна переменная - одна строчка, ну и они все `const item_t` внезапно. И еще не `eltype`, а `elem_type` хотя бы.

2021-02-13 17:54 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen_llvm2.c
> +                    init(io, sx, nd, context);
Тело...

2021-02-13 17:54 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen_llvm2.c
> +/** Генерация кодов llvm. Первый проход по дереву */
А вот не первый он...

2021-02-13 17:55 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen_llvm2.c
> +}
Зачем вам вообще эта функция? Перенесите ее содержимое в `encode_to_llvm`.

2021-02-13 17:56 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen_llvm2.c
> +}
Отступа в конце нет.

2021-02-17 13:54 UTC, IvanArkhipov1999 commented on libs/compiler/codegen_llvm2.c
> +            int args[100];
Перед самой генерацией кода для printf мне необходимо сгенерировать код для аргументов printf и запомнить, в каких регистрах эти аргументы находятся, так как номера этих регистров нужны для кодогенерации printf.

2021-02-17 14:04 UTC, IvanArkhipov1999 commented on libs/compiler/codegen_llvm2.c
> +        break;
Я их разделил с рассчётом на то, что в дальнейшем при реализации инициализации массивов и структур обработка TBeginit и TStructinit будет различной. Сейчас могу их обработку объединить, чтобы не смущало наличие одинакового кода.

2021-02-17 14:05 UTC, IvanArkhipov1999 commented on libs/compiler/codegen_llvm2.c
> +            case TStructend:
Возможно, потом они понадобятся, но не сейчас

2021-02-17 14:14 UTC, IvanArkhipov1999 commented on libs/compiler/codegen_llvm2.c
> +                uni_printf(io, ") {\n");
Сейчас готова кодогенерация только для main, когда буду реализовывать кодогенерацию определения функций, здесь будет более общая обработка. Например, между скобками могут стоять аргументы. Поэтому сейчас это странно выглядит, но потом, надеюсь, всё станет нормально

2021-02-17 15:37 UTC, bugdea1er commented on libs/compiler/codegen_llvm2.c
> +            int args[100];
Тогда размер лучше задавать константой MAXPRINTFPARAMS

2021-02-18 19:00 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +static void block(node *const nd, information *const info);
Сделайте `information *const info` первым параметром, будет проще читать и искать, когда начнете создавать временные ноды.

P.s. Относится ко всем функциям.

2021-02-18 19:05 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			uni_printf(info->io, " %%.%li = load i32, i32* %%var.%li, align 4\n", info->register_num, displ);
`item_t` тип вы так просто не распечатаете... Используйте для этого `PRIitem` по аналогии с `codegen.c`:
```c
uni_printf(info->io, " %%.%" PRIitem " = load i32, i32* %%var.%" PRIitem ", align 4\n"
	, info->register_num, displ);
```

2021-02-18 19:05 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				uni_printf(info->io, " store i32 %li, i32* %%var.%li, align 4\n", num, info->request_reg);
`PRIitem`

2021-02-18 19:07 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			const item_t parameters_num = node_get_arg(nd, 0);
Думаю `_num` тут точно можно опустить и как насчет имени `args`?

2021-02-18 19:12 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				uni_printf(info->io, " ret i32 %li\n", info->answer_num);
`PRIitem`

2021-02-18 19:22 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				, info->string_num++);
- Нужен отступ после `for`
- `PRIitem`
- Нельзя использовать 2 инкрементирования в одном операторе, это может вызвать непредсказуемое поведение, перенесите наружу

2021-02-18 19:23 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				info->variable_location = LREG;
Раньше этого не было, все правильно?

2021-02-18 19:24 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +				expression(nd, info);
Это часть предложенного кода, раньше у вас этого не было, здесь точно нужна обработка выражений (вы никак не используете результат)?

2021-02-18 19:29 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen_llvm2.c
> +        break;
Объедините.

2021-02-19 08:05 UTC, Victor-Y-Fadeev requested changes
В общем на исправления, и где интерфейс для `compiler`? У вас этот код не запускается и не тестируется, поэтому вы даже не можете увидеть по нему предупреждений компиляции!

2021-02-19 08:05 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +	}
Это часть тестирующей системы, удалите ее отсюда.

2021-02-19 08:05 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +	size_t index = 0;
Вам это не нужно и удалите отступ.

2021-02-19 08:05 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +	return index != SIZE_MAX && index == vector_size(nd.tree) ? 0 : -1;
Зачем? А главное, как собралось (`SIZE_MAX` сильно больше, чем `int`)?

2021-02-19 13:31 UTC, IvanArkhipov1999 commented on libs/compiler/llvmgen.c
> +				info->variable_location = LREG;
Так объявляется запрос на переменную в регистре. Возможно, раньше это по умолчанию происходило, я решил явно делать запрос.

2021-02-23 08:51 UTC, Victor-Y-Fadeev requested changes
Давайте создадим отдельную ветку для `llvm`, пока не закончим работу, и включим в ней тестирование? Добавьте в `.travis.yml` флаг `-i` к тестовой системе. А в `main` замените `compile_to_vm` на `compile_to_llvm` и добавьте в `if`:
```c
if (argc < 2)
{
	ws_add_file(&ws, name);
	ws_set_output(&ws, "export.ll");
}
```

2021-02-23 08:51 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +
Думаю этот отступ можно убрать.

2021-02-23 08:51 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	optimize_for_llvm(ws, io, sx);
Это конечно хорошо, но нужно еще и код возврата проверить.

2021-02-23 08:51 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +	item_t string_num;					/**< Номер строки */
Отступ.

2021-02-23 08:51 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +				uni_printf(info->io, "@.str%" PRIitem " = private unnamed_addr constant [%zi x i8] c\"", info->string_num++, N + 1);
Отступ лучше поставить после `uni_printf`, а не до. И у вас строка 133 символа, перенесите переменные на следующую:
```c
uni_printf(info->io, "@.str%" PRIitem " = private unnamed_addr constant [%zi x i8] c\""
	, info->string_num++, N + 1);
```

2021-02-23 08:51 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +	if (!out_is_correct(io) || !ws_is_correct(ws) || sx == NULL)
Лучше проверку `workspace` сделать первой, по аналогии с параметром.

2021-02-23 08:51 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +
Этот отступ можно убрать.

2021-02-23 08:51 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +		flag = ws_get_flag(ws, ++i);
Отступ.

2021-02-23 08:51 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +		if (strcmp(flag, "--mipsel") == 0)
Нормально, но почему 2 минуса?

2021-02-23 08:51 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +		else if (strcmp(flag, "--x86_64-pc-linux-gnu") == 0)
Стоит укоротить флаг, это точно все нужно (проверка то дорогая)? И разве эта платформа не является приоритетной, стоит располагать флаги в порядке частоты использования.

2021-02-23 08:51 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +	}
Не указана платформа по умолчанию, и что если будет 2 разных флага? Вы не выходите после установки платформы, так что даже при правильной работе будут лишние проверки.

Должно быть что-то в духе:
```c
for (size_t i = 0; ; i++)
{
	const char *flag = ws_get_flag(ws, i);

	if (flag == NULL || strcmp(flag, "--x86_64-pc-linux-gnu") == 0)
	{
		uni_printf(io, "target datalayout = \"e-m:e-i64:64-f80:128-n8:16:32:64-S128\"\n");
		uni_printf(io, "target triple = \"x86_64-pc-linux-gnu\"\n\n");
		return;
	}
	else if (strcmp(flag, "--mipsel") == 0)
	{
		uni_printf(io, "target datalayout = \"e-m:m-p:32:32-i8:8:32-i16:16:32-i64:64-n32-S64\"\n");
		uni_printf(io, "target triple = \"mipsel\"\n\n");
		return;
	}
}
```

P.s. Проверка на `NULL` и архитектура по умолчанию должны быть строго первым параметром.

2021-02-23 08:51 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +
Лишний отступ.

2021-02-24 14:36 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +		if (strcmp(flag, "--mipsel") == 0)
В clang архитектура указывается через 2 минуса (например, --target=mips). Хотелось и здесь сделать подобным образом.

2021-02-24 18:30 UTC, Victor-Y-Fadeev commented on libs/compiler/compiler.h
Внутри группы должен быть один отступ.

2021-02-24 18:30 UTC, Victor-Y-Fadeev commented on libs/compiler/compiler.h
Один отступ.

2021-02-24 18:30 UTC, Victor-Y-Fadeev commented on libs/compiler/compiler.h
> +
Один.

2021-02-24 18:30 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +	if (ret)
Зачем? Напишите просто:
```c
if (optimize_for_llvm(ws, io, sx))
```

2021-02-24 18:30 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmgen.c
> +			exit(EXIT_SUCCESS);
Вот вообще не пойдет, лучше уж вечный цикл! Мы с огромным трудом избавились от `exit` не для этого. И удалите `stdlib.h` заодно.

2021-02-24 18:30 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						, info->string_num++, N + 1);
`TAB` должен быть один.

2021-02-24 18:30 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +
Этот отступ удалите.

2021-02-24 18:30 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +				for (size_t j = 0; j < N; j++)
А сюда добавьте отступ.

2021-02-24 18:30 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +	node nd = node_get_root(&sx->tree);
Не туда приклеили, это часть обхода, логичнее было бы объединить с `for`, а не с инициализацией.

2021-02-24 18:30 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +		else if (strcmp(flag, "-mipsel") == 0)
Можно было не убирать `--`, аргумент принят, верните.

2021-02-24 18:30 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +		if (flag == NULL || strcmp(flag, "-x86_64") == 0)
`--x86_64`

2021-02-24 18:30 UTC, Victor-Y-Fadeev commented on .travis.yml
> +  - ./scripts/test.sh -i
Так, если будем оставлять вечный цикл, давайте ка ее ускорим:
```bash
  - ./scripts/test.sh -i -w 0.25
```

2021-02-24 18:49 UTC, Victor-Y-Fadeev approved these changes

2021-02-24 18:50 UTC, merged