Рефакторинг половины парсера
andrey-terekhov/RuC pull request #90
Opened 2021-02-12 10:08 UTC by bugdea1er

Рефакторинг парсера операторов и объявлений (на старом интерфейсе дерева)

- Парсер разнесен по нескольким файлам
- Средний размер функций стал меньше
- Интерфейс разбора выражений максимально сокращен, все обращение к стекам только внутри parse_expr.c
- Распутаны вызовы при разборе инициализации
- Количество наведенных ошибок уменьшилось (после рефакторинга parse_expr.c уменьшится сильнее)
- Метки теперь не используют syntax.hash
- Удалены устаревшие тесты

Разбор выражений не трогал совсем, он просто скопирован
Странно, что для functions и processes нет нужного интерфейса, приходится обращаться к этим полям syntax вручную

2021-02-13 13:20 UTC, Victor-Y-Fadeev requested changes
В общем, парсер выглядит очень прилично, по крайней мере теперь понятно что делается (`parser_expr.c` не в счет). Глобально по исправлениям:
- Не используйте одинаковые имена для переменных и типов:
  - Для `lexer` используйте сокращение `lxr`
  - Для `parser` - [`prs`](https://www.allacronyms.com/PRS/Parser)
- Называйте сами структуры и перечисления, даже если используете `typedef`
- Для статических типов используйте постфикс `_t`
- Используйте общие префиксы в функциях и группируйте их, это упрощает поиск
- Не используйте пробелы вперемешку с табами и не ставьте лишние
- Называйте файлы единообразно, в принципе, это ко всему относится

Касательно динамических параметров, следует отдельно поговорить, но не пользуйтесь ими не прочитав о том как они работают (я удивлен, что вы до сих пор по сегментации не упали)!

И `parser_expr.c` требует доработок, так как - это copy-paste `extdecl.c`. Часть я проверил, но дальше не вижу смысла, он просто не доделан.

2021-02-13 13:20 UTC, Victor-Y-Fadeev commented on libs/compiler/parse_expr.c
> +}
Не пишите так, если не нравится старая реализация, используйте `switch`. Плюс проблемы с названием функции и типом аргумента.

2021-02-13 13:20 UTC, Victor-Y-Fadeev commented on libs/compiler/parse_expr.c
> +	int i;
Перенесите внутрь цикла.

2021-02-13 13:20 UTC, Victor-Y-Fadeev commented on libs/compiler/parse_expr.c
> +	vector_remove(&parser->sx->tree);
Почему?

2021-02-14 12:00 UTC, bugdea1er commented on libs/compiler/defs.h
> +} mode;
mode_t уже занято системными библиотеками

2021-02-14 12:21 UTC, bugdea1er commented on libs/compiler/parser.h
> +void insert_widen(parser *const parser);
Ну вообще предполагалось, что parse_ в начале названий функций – не префикс, а действие, которое выполняет  функция. insert_widen не делает никакого разбора, она не работает с токенами и не двигается по исходному файлу

2021-02-14 12:33 UTC, bugdea1er commented on libs/compiler/lexer.c
> +		case (char32_t)EOF:
Ругался

2021-02-14 12:51 UTC, bugdea1er commented on libs/compiler/parser.h
> +item_t to_modetab(parser *const parser, const item_t mode, const item_t element);
https://github.com/andrey-terekhov/RuC/pull/50#discussion_r538422957
Это переименованная newdecl

2021-02-14 12:52 UTC, bugdea1er commented on libs/compiler/parser.c
> +		parser->lastid = (int)ret;
Потому что теперь он используется только в parse_expr, который пока не изменен, и вообще я планирую от него избавиться

2021-02-14 12:54 UTC, bugdea1er commented on libs/compiler/parser.c
> +				}
Если встреченный токен находится в tokens, то мы выходим из функции, иначе этот break выходит из switch, и цикл продолжается

2021-02-14 12:55 UTC, bugdea1er commented on libs/compiler/parser.c
> +	return parser->was_error || parser->lexer->was_error;
Лексер работает независимо от парсера, и имеет свой флаг ошибок, а при ошибке парсера странно как-то ставить флажок ошибки лексера

2021-02-14 12:56 UTC, bugdea1er commented on libs/compiler/parser_stmt.c
> +	// переходов на нее
Переходов на одну и ту же метку может быть несколько

2021-02-14 12:58 UTC, bugdea1er commented on libs/compiler/parser_stmt.c
> +	vector_remove(&parser->sx->tree);
Потому что перед оператором print в дереве не должно быть TExprend

2021-02-14 13:01 UTC, bugdea1er commented on libs/compiler/parser_stmt.c
> +				case '\0':
Эта функция работает со строками, которые из входного файла уже считал лексер. Лексер на конец строки ставит '\0', то есть здесь проверяется, не является ли '%' последним символом с строке. EOF тут быть и не может

2021-02-14 13:02 UTC, bugdea1er commented on libs/compiler/parser_stmt.c
> +void parse_scanf_statement(parser *const parser);
Вообще здесь должен быть ее код, когда оператор scanf появится в ruc

2021-02-14 13:03 UTC, bugdea1er commented on libs/compiler/parser_stmt.c
> +	char32_t placeholders[MAXPRINTFPARAMS];
https://www.wordnik.com/words/placeholder

2021-02-14 13:06 UTC, bugdea1er commented on libs/compiler/parser_stmt.c
> +				break;
Да, если после идентификатора нет ':', то это начало выражения, которое разбирается в блоке default ниже

2021-02-14 13:08 UTC, bugdea1er commented on libs/compiler/parser_stmt.c
> +			break;
Ну вообще они так и сгруппированы: сначала вырожденный случай - null statement, затем сгруппированные по грамматике операторы, затем те, которых нет в С - один для нитей и остальные для ввода/вывода

2021-02-14 13:33 UTC, bugdea1er commented on libs/compiler/parse_decl.c
> +void parse_init_declarator(parser *const parser, item_t type)
Это именно разбор декларатора - термин есть такой в документации С (см. С99 6.7)

2021-02-14 13:35 UTC, bugdea1er commented on libs/compiler/parse_decl.c
> + *	Parse declarator with optional initializer
Ответил выше

2021-02-14 13:37 UTC, bugdea1er commented on libs/compiler/parse_decl.c
> + *	Parse function declarator
Нет, тут именно декларатор - заголовочная часть функции.

2021-02-14 13:45 UTC, bugdea1er commented on libs/compiler/parse_expr.c
> +	vector_remove(&parser->sx->tree);
На конце выражения стоит TExprend, его быть не должно, если вставляем WIDEN

2021-02-14 13:52 UTC, bugdea1er commented on libs/compiler/parse_decl.c
> +				if (id == 1)
В таблицах идентификаторов и видов первые несколько полей зарезервированы под такие проверки ошибок

2021-02-14 14:09 UTC, bugdea1er commented on libs/compiler/parser.h
> + *	If that 'peek token' is expected, parser consumes it, otherwise an error is emited
Исправил под First Conditional

2021-02-14 14:27 UTC, bugdea1er commented
- Про именования: parse_ предполагался не как префикс, а как часть названия функции, они ведь именно производят разбор; statement и declaration в названиях функций - не суффикс, а часть названия грамматических конструкций в С; parser_error не производит разбора, поэтому в это название вставлять parse_ странно. Если нужны суффиксы, то тогда функции стоит называть parser_decl_parse_init_declarator или parser_stmt_parse_compound_statement. Мне кажется, что такие названия делать не стоит, и для данных случаев стоит отказаться от префиксов, как это было сделано в кодгене
- Аналогично и про названия файлов, но тут уже я не против называть parser_decl и так далее
- Про try_consume: не думаю, что менять коды возврата на 0 и -1 хорошая идея. Это что-то вроде предиката, который дополнительно умеет кушать один токен (ситуация, в которой после такой проверки нужно съесть именно этот токен, очень часто встречается). Если следующий токен не совпадает с ожидаемым, это ни в коем случае не ошибка в рамках данной функции. Если на самом деле это и является ошибкой в файле, то обрабатывает это не try_consume, а тот код, который ее вызвал
- Касательно разбора выражений: обязательно учту замечания, но на данный момент править там нужно очень много. Возможно, вместо этого кода использую код разбора выражений из mips, так как он там обновлялся Андреем Николаевичем 

На все остальное вроде либо исправил, либо ответил прямо там

2021-02-14 14:30 UTC, bugdea1er commented on libs/compiler/parser.h
> +size_t to_identab(parser *const parser, const size_t repr, const item_t type, const item_t mode);
Это прослойка именно для парсера, здесь же парсер должен выводить ошибки и тыкать в конкретное место в исходном файле

2021-02-15 14:41 UTC, Victor-Y-Fadeev requested changes
Про именования и префиксы:
- Предложенный вариант слишком длинный и содержит дубликаты
- Функция `parser_error` у вас всего одна с таким префиксом и можно просто сделать исключение, назвав ее  `parse_error`
- Касательно `parse_expression`, `parse_declaration` и `parse_statement` - их можно читать как "разбор того-то сделай то-то", тогда получится и сохранить читаемость и использовать их как суффиксы
- В кодогенераторе функции внутренние и статические, они не видны снаружи, у вас же они в интерфейсе
- Файлы все же стоит переименовать на `parser_*.c`

`try_consume` - принято. Замечания по разбору выражений все же лучше исправить, если их предполагается мержить в этом запросе. 

Также у вас на [этом](https://github.com/andrey-terekhov/RuC/pull/90/commits/39843404b7b9e78db379cd37b151053cc089cbd3) коммите упали тесты:
```c
 execution failure : ../tests/executable/structures/structarr1.c
```

P.s. Не закрывайте самостоятельно мои комментарии, мне приходится их раскрывать для проверки, наибольшие сложности возникнут когда придется смотреть комментарии от прошлого ревью.

2021-02-15 14:41 UTC, Victor-Y-Fadeev commented on libs/compiler/parse_decl.c
> +		// parser_error(parser, empty_struct);
`// parse_error`, а то потеряется.

2021-02-15 14:41 UTC, Victor-Y-Fadeev commented on libs/compiler/parse_decl.c
> +		prs->flag_array_in_struct = procd;
После слияния вставьте сюда:
```c
tree_add(prs->sx, TStructend);
tree_add(prs->sx, (item_t)prs->sx->procd);
tree_set(prs->sx, ref_struct_begin + 1, (item_t)prs->sx->procd);
prs->flag_array_in_struct = (int)prs->sx->procd++;
```

2021-02-15 14:41 UTC, Victor-Y-Fadeev commented on libs/compiler/parse_decl.c
> +				token_expect_and_consume(prs, l_paren, wrong_fun_as_param);
Не решено, переименуйте ошибки. Используйте `func`, вместо `fun`, и `arg`, вместо `param`.

2021-02-15 14:46 UTC, Victor-Y-Fadeev commented
Чтобы не забыть:
```
Conflicting files:
	libs/compiler/analyzer.c
	libs/compiler/codegen.c
	libs/compiler/errors.h
	libs/compiler/extdecl.c
	libs/compiler/syntax.c
```

2021-02-15 16:35 UTC, bugdea1er commented on libs/compiler/parser.h
> +
Разные же блоки функций: эта вызывается только извне, остальные - только изнутри

2021-02-15 16:35 UTC, bugdea1er commented on libs/compiler/parser.h
> +
Разные же блоки функций: эта вызывается только извне, остальные - только изнутри

2021-02-15 16:37 UTC, bugdea1er commented on libs/compiler/parser.c
> +	error(prs->lxr->io, err, args);
Давайте

2021-02-15 16:38 UTC, bugdea1er commented on libs/compiler/parser.c
> +void parser_error(parser *const prs, const int err, ...)
А вот на тип error_t вместо int для получения va_start компилятор ругается

2021-02-15 17:13 UTC, bugdea1er commented on libs/compiler/parse_expr.c
> +void binop(parser *context, int sp)
sp - stack pointer

2021-02-15 22:41 UTC, bugdea1er commented
- Файлы переименовал
- Потерявшийся тест вернулся
- Вопрос про префиксы решили отложить на следующий раз
- Про ошибки - лучше бы функции для ошибок парсера и лексера принимали vargs, давайте на verror договоримся

Вроде теперь все подправил

2021-02-16 00:30 UTC, Victor-Y-Fadeev reviewed
Про `parse_error` и `parse_declaration_*` вроде же договорились и там не проблем с перестановкой? 

Итого остались только мелочи. По изменениям `parser_expr.c`, незакрытые комментарии все еще актуальны. Так как что-то не работает, попробуйте исправлять по одному.

2021-02-16 00:30 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.h
> +typedef enum
```c
typedef enum BLOCK
{
	...
} block_t;
```

2021-02-16 00:30 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.h
> +void insert_widen(parser *const prs);
Здесь то вроде нет проблем с порядком слов.
```c
void parse_expression_insert_widen(parser *const prs);
```

2021-02-16 00:30 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.h
> +item_t parse_condition(parser *const prs);
Если с выражениями пока все к одному виду привести не получается, тогда эту функцию вниз блока.

2021-02-16 00:30 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.h
> +item_t parse_expression(parser *const prs);
А эту в начало блока.

2021-02-16 00:30 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.h
> +void parse_inner_declaration(parser *const prs);
```c
void parse_declaration_inner(parser *const prs);
```

2021-02-16 00:30 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.h
> +void parse_external_declaration(parser *const prs);
void parse_declaration_external(parser *const prs);

2021-02-16 00:30 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +	}
```c
if (prs->ansttype == LFLOAT &&
	((op >= ASS && op <= DIVASS) || (op >= ASSAT && op <= DIVASSAT) || (op >= EQEQ && op <= UNMINUS)))
{
	vector_add(&TREE, op + 50);
}
else
{
	vector_add(&TREE, op);
}
```

2021-02-16 10:31 UTC, Victor-Y-Fadeev reviewed
Все отлично, все старые комментарии удалось закрыть, думаю через пару коммитов закончим.

2021-02-16 10:31 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.h
> + *	@return	@c 1 on consuming 'peek token', @c 0 otherwise
Все таки `on otherwise` выйдет конкретнее.

2021-02-16 10:31 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +void must_be(parser *const prs, int what, int e)
Пропустили типы и названия переменных:
```c
void must_be(parser *const prs, const token_t what, const error_t num)
```

2021-02-16 10:31 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.h
> +void parse_expression_insert_widen(parser *const prs);
Насчет этого блока, может такой порядок сделаем (и раз уж остались функции без `_expression`? то уберем его из `parse_insert_widen`):
```c
item_t parse_expression(parser *const prs);
item_t parse_assignment_expression(parser *const prs);
item_t parse_parenthesized_expression(parser *const prs);
item_t parse_constant_expression(parser *const prs);
item_t parse_condition(parser *const prs);
void parse_string_literal(parser *const prs);
void parse_insert_widen(parser *const prs);
```

2021-02-16 10:31 UTC, Victor-Y-Fadeev commented on libs/compiler/analyzer.c
> +	prs.lxr->io = io;
У меня есть к вам замечательное предложение, перенести работу со временным `io` в `read_keywords`, тогда здесь останется:
```c
lexer lxr = create_lexer(io, sx);
parser prs = parser_create(sx, &lxr);

read_keywords(&prs);
init_modetab(&prs);
```

2021-02-16 10:31 UTC, Victor-Y-Fadeev commented on libs/compiler/analyzer.c
> +	prs->sx->keywords = 0;
А здесь получится:
```c
universal_io *old_io = prs->lxr->io;
universal_io io = io_create();
prs->lxr->io = &io;

in_set_buffer(prs->lxr->io, KEYWORDS);
prs->sx->keywords = 1;

get_char(prs->lxr);
get_char(prs->lxr);
while (lex(prs->lxr) != LEOF)
{
	; // чтение ключевых слов
}

prs->sx->keywords = 0;
in_clear(prs->lxr->io);

prs->lxr->io = old_io;
```

2021-02-16 10:42 UTC, bugdea1er commented on libs/compiler/errors.c
> -			sprintf(msg, "этот код ошибки я прозевал");
У нас же теперь в условии switch стоит переменная типа перечисления, и компилятор проверяет, все ли случаи перечислены. Если оставить default, то можно что-нибудь случайно упустить

2021-02-16 10:54 UTC, Victor-Y-Fadeev approved these changes

2021-02-16 11:58 UTC, merged