Start refactoring the interface
andrey-terekhov/RuC pull request #91
Opened 2021-02-12 19:17 UTC by Egor-Anikin

В рамках данного pull request-а планируется зафиксировать название библиотек и функций интерфейсов препроцессора. Необходимо проверить сведущие файлы:
-	calculator.h
-	get_macro.h
-	parser.h
-	save_macro.h
-	utils.h
В интерфейсе utils функции без документации, либо исчезнут, либо сильно изменятся после интеграции map, сейчас их можно не смотреть. Интерфейс environment затрагивает все части работы над препроцессором, в связи с чем он будет меняться по ходу работы. В файлах помимо выше указанных параллельно ведётся работа в других ветках, поэтому их сейчас смотреть не стоит.

2021-02-14 16:08 UTC, 6easy9 requested changes
Общие замечания:
- **Запрещено использовать глобальные переменные**;
- Не следует присылать незавершенную работу, тем более, если не собирается;
- Необходимо проставлять `const` перед типом каждой переменной/аргумента, если они в дальнейшем не изменяются;
- Прямое обращение к элементам структуры крайне не желательно;
- В функциях интерфейса нужна проверка входных параметров;
- Документация должна быть написана для каждой функции интерфейса;
- Объявление переменных необходимо делать непосредственно перед использованием;
- Имена переменных/аргументов функций, тем более интерфейсных должны соответствовать тому, для чего они используются.

2021-02-14 16:08 UTC, 6easy9 commented on libs/preprocessor/save_macro.c
> +					if(get_macro(k, env))
Отсутствует пробел.

2021-02-14 16:08 UTC, 6easy9 commented on libs/preprocessor/save_macro.c
> +		size_t position = env_skip_str(env);
Нужен `const`.

2021-02-14 16:08 UTC, 6easy9 commented on libs/preprocessor/save_macro.c
> +		size_t position = env_skip_str(env);
Нужен `const`.

2021-02-14 16:08 UTC, 6easy9 commented on libs/preprocessor/save_macro.c
> +		size_t position = env_skip_str(env);
Нужен `const`.

2021-02-14 16:08 UTC, 6easy9 commented on libs/preprocessor/save_macro.c
> +		size_t position = env_skip_str(env);
Нужен `const`.

2021-02-14 16:08 UTC, 6easy9 commented on libs/preprocessor/save_macro.c
> +		size_t position = env_skip_str(env);
Нужен `const`.

2021-02-18 22:51 UTC, Egor-Anikin commented on libs/preprocessor/environment.c
> +void m_nextch(environment *const env);
Присутствует ниже.

2021-02-18 22:53 UTC, Egor-Anikin commented on libs/preprocessor/environment.c
> +void m_fprintf(int a, environment *const env)
Временный файл, это делать осмысленно после более глобальных изменений.

2021-02-19 10:13 UTC, 6easy9 requested changes
- Проверить старые комментарии, есть несколько незакрытых.

2021-02-19 10:13 UTC, 6easy9 commented on libs/preprocessor/calculator.c
>  			int r = collect_mident(env);
Нужен `const`.

2021-02-19 10:13 UTC, 6easy9 commented on libs/preprocessor/save_macro.c
> +			const size_t position = env_skip_str(env);
Пробел в конце строки.

2021-02-20 08:32 UTC, 6easy9 requested changes
- Названия переменных заменить на осмысленные;
- Названия функций и переменных проверить по словарю.

2021-02-20 08:32 UTC, 6easy9 commented on libs/preprocessor/environment.h
>  	int dipp;
Такого слова не существует. Если подразумевается глубина, то следует использовать `depth`. Если глубокий, то следует использовать `deep`.

2021-02-20 08:32 UTC, 6easy9 commented on libs/preprocessor/macro_load.c
> +int function_scob_collect(environment *const env, const int t, const int num)
Слова `scob` в английском языке нет. Следует заменить на `scope`. `t` заменить на что-то более осмысленное.

2021-02-20 08:32 UTC, 6easy9 commented on libs/preprocessor/macro_load.c
> +				int ldip;
Названия переменных следует заменить.

2021-02-20 08:32 UTC, 6easy9 commented on libs/preprocessor/macro_save.c
> +int funktionleter(environment *const env, int flag_macro)
Название функции заменить.
С 63 по 70 переделать, заменить названия переменных.

2021-02-20 08:32 UTC, 6easy9 commented on libs/preprocessor/macro_save.c
>  	}
В 137 строке `j` заменить на `i` и перенести в цикл `for`.

2021-02-20 08:32 UTC, 6easy9 commented on libs/preprocessor/macro_save.c
>  	int j;
Перенести в `for`.
Заменить на `i`.

2021-02-20 08:32 UTC, 6easy9 commented on libs/preprocessor/macro_save.c
> +int macrotext_add_define(environment *const env, int r)
`r` заменить на осознанное название.

2021-02-20 08:32 UTC, 6easy9 commented on libs/preprocessor/macro_save.c
>  				int k = collect_mident(env);
Изменить название, сделать константой.

2021-02-20 08:32 UTC, 6easy9 commented on libs/preprocessor/macro_save.c
> +	const int j = collect_mident(env);
Заменить название.

2021-02-21 10:02 UTC, 6easy9 requested changes
Новых замечаний нет, старое было не до конца исправлено..

2021-02-21 12:09 UTC, 6easy9 approved these changes

2021-02-23 07:33 UTC, Victor-Y-Fadeev requested changes
На доработку.

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.c
> +	int empty = 0;
К месту использования.

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.c
> +	}
Можно проще и `const`:
```c
const int flag_macro = env->cur == SH_MACRO;
```

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.c
> +		int res = fn_add_ident(env);
`const`

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.c
> +				for (int i = 0; i < env->calc_prt; i++)
`size_t`

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.c
> +				for (int i = 0; i < env->reprtab[env->rp]; i++)
`size_t`

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.c
> +	int r;
Перенести по месту использования и переименовать.

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.c
> +int macrotext_add_define(environment *const env, int rep_prt)
`rep_prt` неудачное имя переменной.

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.c
> +	int lmp = env->macro_prt;
Что значит имя и пропущен `const`.

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.c
> +					for (int i = 0; i < env->calc_prt; i++)
`size_t`

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.c
> +					for (int i = 0; i < env->reprtab[env->rp]; i++)
`size_t`

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.c
> +					for (int i = 0; i < env->msp; i++)
`size_t`

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.c
> +	int r;
Перенести по месту использования, переименовать и сделать `const`.

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.c
> +	}
Эту проверку нужно перенести в `define_add_to_reprtab`.

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.c
> +	}
Насчет этого большие вопросы, так как данная проверка является частью `collect_mident`... Надеюсь в будущем будет исправлено.

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.c
> +
Лишний отступ.

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/utils.h
> + *	Skip all spaces and tabs up to a significant character
Что за символ? Как это отражено в названии функции? Уточнить и переименовать функцию.

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/utils.h
> +int skip_space_end_line(environment *const env);
Переименовать из-за проблем со `skip_space`. И почему код возврата только у этой функции?

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/utils.h
>  void skip_file(environment *const env);
Нет кодов возврата.

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/parser.h
> +int preprocess_scan(environment *const env);
Тогда уж `preprocess_token`, а не `preprocess_scan`.

2021-02-23 07:33 UTC, Victor-Y-Fadeev commented on libs/preprocessor/calculator.h
> + *	@param	env				Preprocessor environment
Неправильный порядок (везде проверьте, а то часто стал встречаться). `logic_flag` - крайне неудачное имя, особенно для внешнего интерфейса, назовите `type`.

2021-02-25 13:28 UTC, Victor-Y-Fadeev requested changes
На доработку.

2021-02-25 13:28 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_load.h
> +int macros_get(environment *const env, const int index);
Это внешний интерфейс, тем более он претендует на релиз, исправить.
Кстати не заметил, что у вас тут множественное число, исправить.

2021-02-25 13:28 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_load.h
> + *	@param	index		Pointer to macro in macro_tab
`Index of macro in macro table`

2021-02-25 13:28 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.h
> +int macros_add(environment *const env);
Множественное число.

2021-02-25 13:28 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.h
> +int macros_set(environment *const env);
Множественное число.

2021-02-25 13:28 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_save.c
> +	if (r == -1)
```c
if (define_add_to_reprtab(env))
```

2021-03-09 13:08 UTC, Victor-Y-Fadeev reviewed
Внимательнее.

2021-03-09 13:08 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_load.h
> + *	@param	index		Pointer to macro in macro_tab
Не исправлено, читайте внимательнее к какой строчке написан комментарий.
И верните описание самой функции `Change input to macro replacement text`.

2021-03-09 13:08 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_load.c
> +				: get_depth(env);
Переносы строк и отступы здесь добавляется для улучшения читаемости, а не просто так. Как должно выглядеть:
```c
const int loc_depth = env->nextch_type == FTYPE
			? get_depth(env) - 1
			: get_depth(env);
```

2021-03-10 00:56 UTC, Victor-Y-Fadeev reviewed
Если так продолжится то никогда не закончим. Вызовите просто `in_clear` для закрытия файла.

2021-03-10 00:56 UTC, Victor-Y-Fadeev commented on libs/preprocessor/preprocessor.c
> +
Не нужно, эта проверка уже выполнена в `macro` и `macro_to_file`.

2021-03-10 00:56 UTC, Victor-Y-Fadeev commented on libs/preprocessor/utils.h
> +void finish_file(environment *const env);
Это выглядит крайне печально, от переименования суть не меняется... Зачем в цикле пробегать весь файл посимвольно? Его нужно просто закрывать. В общем, раз на вопросы я не получаю ответа, удалите эту функцию и не копируйте ее содержание никуда, закрывайте файл.

2021-03-10 00:56 UTC, Victor-Y-Fadeev commented on libs/preprocessor/constants.h
> +#define SH_FILE		-81
Нет отступа в конце файла.

2021-03-10 00:56 UTC, Victor-Y-Fadeev commented on libs/preprocessor/macro_load.h
> + *	Index of macro in macro table
Не вернули сломанное описание самой функции:
```c
 *	Change input to macro replacement text
```

2021-03-10 00:56 UTC, Victor-Y-Fadeev commented on libs/preprocessor/linker.h
> +int lk_set_current(linker *const lk, size_t index);
Зачем? Этот файл уже был ранее утвержден, обоснуйте или верните как было. А еще глобальная проблема пробелов в описаниях!

2021-03-10 00:56 UTC, Victor-Y-Fadeev commented on libs/preprocessor/parser.h
> +int preprocess_file(environment *const env, const size_t number);
Зачем поменяли? И проблемы с пробелами!

2021-03-12 09:06 UTC, Egor-Anikin commented on libs/preprocessor/utils.h
> +void finish_file(environment *const env);
С начало на тело посмотри, потом делай какие-то, выводы. in_clear в данном месте сделать не получится, вызовет много сложностей.

2021-03-12 09:07 UTC, Egor-Anikin commented on libs/preprocessor/macro_load.h
> + *	Index of macro in macro table
Ты описание этой функции уже дважды менял определись уже.

2021-03-12 09:19 UTC, Egor-Anikin commented on libs/preprocessor/linker.h
> +int lk_set_current(linker *const lk, size_t index);
Мы уже раз 10 обсуждали изменения linker, так чтобы устроить двойные зависимости, по менять lk и env.
Утверждён не значит не будет меняться, утвержден значит после любых изменений будет соответствовать сталгайду, если речь про конкретно этот pull request если хочешь я могу откатить но это вызовет потом множество конфликтов которые замедлят работу.

2021-03-12 09:20 UTC, Egor-Anikin commented on libs/preprocessor/parser.h
> +int preprocess_file(environment *const env, const size_t number);
Смотри предыдущий комментарий.

2021-03-22 00:13 UTC, Victor-Y-Fadeev approved these changes

2021-03-22 00:49 UTC, merged