Перевод reprtab на map
andrey-terekhov/RuC pull request #93
Opened 2021-02-16 17:09 UTC by bugdea1er

- reprtab теперь map
- Инициализация reprtab теперь не использует keywords.c

2021-02-16 20:32 UTC, Victor-Y-Fadeev requested changes
В общем по мелочи, но `repr_get_name` нужно исправлять.

2021-02-16 20:32 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +			const item_t id = repr_get_reference(prs->sx, prs->lxr->repr);
А кастануть один раз дешевле (не переживайте `ITEM_MAX` не бывает больше `SIZE_MAX`).

2021-02-16 20:32 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_decl.c
> +				const item_t id = repr_get_reference(prs->sx, repr);
`size_t`

2021-02-16 20:32 UTC, Victor-Y-Fadeev commented on libs/compiler/parser_expr.c
> +	prs->lastid = (size_t)id;
Кхе, кхе, а почему бы сразу не записать в `prs->lastid`?

2021-02-16 20:32 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.h
> + *	@param	spelling	Unique string key
`Unique UTF-8 string key`

2021-02-16 20:32 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.h
> + *	Add a new record to representations table from io or return existing
Вот только не `from io`.

2021-02-16 20:32 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +}
Одну строчку можно было бы и не экономить... Удалите, вы вместо одной семь написали.

2021-02-16 20:32 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +	// repr_add_keyword(reprtab, U"register", U"регистровый", kw_register);
Новые имена утвердили с Андреем Николаевичем?

2021-02-16 20:32 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +void repr_add_keyword(map *const reprtab, const char32_t *eng_spelling, const char32_t *rus_spelling, const token_t token)
Может постфикс `_spelling` выкинете?

2021-02-16 20:32 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +	buffer[i] = '\0';
Вроде как использовать значение итератора за циклом `for` нехорошо:
```c
buffer[0] = utf8_to_upper(eng[0]);
for (size_t i = 1; eng_spelling[i - 1] != '\0'; i++)
{
	buffer[i] = utf8_to_upper(eng[i]);
}
```

2021-02-16 20:32 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +	buffer[i] = '\0';
Тоже самое.

2021-02-16 20:32 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +void repr_init(map *const reprtab)
Мне почему-то кажется что эта функция должна быть в паре с `init_modetab`...

2021-02-16 20:32 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
>  }
Это вообще работать не будет, `map_to_string` возвращает обычную строку, а не `UTF-8`!
Смените интерфейс, этот буфер был сделан в качестве временного решения:
```c
const char *repr_get_name(const syntax *const sx, const size_t index)
{
	return map_to_string(&sx->reprtab, index);
}
```

2021-02-16 21:59 UTC, bugdea1er commented on libs/compiler/parser_decl.c
> +			const item_t id = repr_get_reference(prs->sx, prs->lxr->repr);
Не проходят тесты на windows

2021-02-16 22:01 UTC, bugdea1er commented
- Изменения с типами откатил обратно для работы на windows
- modetab_init перенес в syntax
- analyzer стал каким-то очень пустым, убрал его функционал в parser

2021-02-17 05:24 UTC, Victor-Y-Fadeev reviewed
По содержанию все отлично, осталось несколько комментариев по оформлению.

2021-02-17 05:24 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +void repr_add_keyword(map *const reprtab, const char32_t *eng, const char32_t *rus, const token_t token)
```c
void repr_add_keyword(map *const reprtab, const char32_t *const eng, const char32_t *const rus, const token_t token)
```

2021-02-17 05:24 UTC, Victor-Y-Fadeev commented on libs/compiler/syntax.c
> +void mode_init(syntax *const sx)
У вас `modes` инициализируется после `representations`. Перенесите `repr_add_keyword` и `repr_init` на самый верх (первой и второй функцией). А `mode_init` будет тогда третьей.

2021-02-17 05:24 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.h
> +typedef struct parser
Стоит поставить ее на первое место.

2021-02-17 05:24 UTC, Victor-Y-Fadeev commented on libs/compiler/parser.c
> +
2 отступа.

2021-02-17 05:24 UTC, Victor-Y-Fadeev commented on libs/compiler/codegen.c
Думаю теперь этот отступ можно убрать.

2021-02-17 06:39 UTC, merged