Refactoring calculator
andrey-terekhov/RuC pull request #94
Opened 2021-02-19 23:02 UTC by Egor-Anikin

На данный момент приведены в порядок следующие функции:
- char get_opiration
- get_prior
- implementation_opiration  
В дальнейшем планируется:
- привести в порядок остальные и разбить calculate на более мелкие 
-  избавится от лишних действий 
- перенести в calculator переменные environment касающееся только этой библиотеки

2021-02-26 09:05 UTC, 6easy9 requested changes
Необходимо удалить `printf`, выполнить авто замену `if(` -> `if (`, исправить названия.

2021-02-26 09:05 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +	int locl_type = type;
Перенести перед 450 строкой. Сделать константой.

2021-02-26 09:05 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +			if(calc_digit(env, stack, is_int, &stk_size))
Пропущен пробел.

2021-02-26 09:05 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +		else if(opration_flag)
Пропущен пробел.

2021-02-26 09:05 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +		else if(opration_flag)
Пропущен пробел.

2021-02-26 09:05 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +			if(calc_opiration(env, stack, is_int, operation, &op_size, &stk_size, locl_type))
Пропущен пробел.

2021-02-26 09:05 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +		if(calc_close(stack, is_int, operation, &op_size, &stk_size))
Пропущен пробел.

2021-02-26 09:05 UTC, 6easy9 commented on libs/preprocessor/calculator.c
>  }
Отсутствует перенос строки в конце файла.

2021-02-28 16:17 UTC, Egor-Anikin commented on libs/preprocessor/calculator.c
> +	int locl_type = type;
Значение меняется в 426 и 383 строках.

2021-02-28 19:17 UTC, Egor-Anikin commented on libs/preprocessor/calculator.c
>  	int d = 1;
Планируется, исправить в следующей итерации.

2021-02-28 19:17 UTC, Egor-Anikin commented on libs/preprocessor/calculator.c
>  	double k;
Планируется, исправить в следующей итерации.

2021-02-28 19:17 UTC, Egor-Anikin commented on libs/preprocessor/calculator.c
Планируется, исправить в следующей итерации.

2021-02-28 19:17 UTC, Egor-Anikin commented on libs/preprocessor/calculator.c
Планируется, исправить в следующей итерации.

2021-02-28 19:18 UTC, Egor-Anikin commented on libs/preprocessor/calculator.c
>  	char s[30] = "\0";
Планируется, исправить в следующей итерации.

2021-02-28 19:18 UTC, Egor-Anikin commented on libs/preprocessor/calculator.c
>  		int l = 0;
Планируется, исправить в следующей итерации.

2021-03-02 10:29 UTC, 6easy9 requested changes
Исправить не закрытые комментарии.
Нужно быть внимательнее с написанием слов, поскольку, некоторые опечатки крайне трудно обнаружить.

2021-03-02 10:29 UTC, 6easy9 commented on libs/preprocessor/constants.h
> +#define TEXTTYPE			10
`M*`, `C*`, `I*`, `F*` надо заменить на более понятный префикс. 
Нужно нижнее подчеркивание перед `TYPE`.

2021-03-02 10:29 UTC, 6easy9 commented on libs/preprocessor/constants.h
> +#define FILETYPE			0
Поменять местами с 39 строкой.

2021-03-02 10:29 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +	int opration_flag = 0;
В названии ошибка.

2021-03-02 10:29 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +	int locl_type = type;
В названии ошибка.

2021-03-04 13:26 UTC, 6easy9 requested changes
Должно собираться!
Необходимо проверять правильность написания слов.

2021-03-04 13:26 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +		char bufer[STRING_SIZE];
`buffer` пишется с двумя буквами `'f'`.

2021-03-16 14:28 UTC, 6easy9 requested changes
Исправить ошибки в названиях и оформлении.

2021-03-16 14:28 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +	if(in == NULL || rez == NULL || (cur != '-'  && !utf8_is_digit(cur)))
Пропущен пробел

2021-03-16 14:28 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +	if(last != NULL)
Пропущен пробел.

2021-03-16 14:28 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +				if(utf8_is_power(env->curchar) &&  (env->nextchar == '+' || env->curchar == '-'))
Пробел.

2021-03-16 14:28 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +		int cur =  env->curchar;
Двойной пробел.

2021-03-19 14:33 UTC, 6easy9 requested changes
Проверить типы переменных и аргументов.
Исправить прошлую ошибку

2021-03-19 14:33 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +char get_operation(const char cur, const char next)
Почему здесь `next` имеет тип `char`, в функции `get_digit` `next` и `cur` имеют тип `int`, и при этом присваиваются в переменную с типом `char32_t`?

2021-03-19 14:33 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +				if(utf8_is_power(env->curchar) &&  (env->nextchar == '+' || env->curchar == '-'))
Пробел.

2021-03-23 00:34 UTC, 6easy9 requested changes
Разобраться с типами.

2021-03-23 00:34 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +char get_operation(const char cur, const char next)
Почему здесь `next` имеет тип `char`, в функции `get_digit` `next` и `cur` имеют тип `char32_t`, и при этом в структуре `enviroment` поля, используемые в качестве аргументов для `get_operation` имеют тип `int`?

2021-03-25 19:20 UTC, 6easy9 requested changes
Функции калькулятора нужно окончательно перевести на `char32_t` без неуместного приведения типов.

2021-03-25 19:20 UTC, 6easy9 commented on libs/preprocessor/calculator.h
>   *	Calculate an arithmetic or logical expression
Calculate an arithmetic expression

2021-03-25 19:20 UTC, 6easy9 commented on libs/preprocessor/calculator.h
> + *	Calculate an arithmetic or logical expression
Calculate a logical expression

2021-03-25 19:20 UTC, 6easy9 commented on libs/preprocessor/calculator.c
> +char get_operation(const char32_t cur, const char32_t next)
Функции должны возвращать `char32_t`, иначе нет смысла во всех этих телодвижениях.

2021-03-27 21:03 UTC, 6easy9 requested changes
Исправить совместимость с текущей версии ветки "refactoring", Изучить стайлгайд (находится в википедии репозитория RuC на GitHub) и исправить ошибки оформления.

2021-03-31 17:09 UTC, Egor-Anikin commented on libs/preprocessor/error.c
> +			sprintf(msg, "слишком большая целая константа, преобразована в ДЛИН (DOUBLE)");
Это предупреждение относится к обработки числовых констант, такая обработка необходима как препроцессору так и лексеру. По обсуждению которое состоялось в начале рефакторинга, метод get_digit реализован таким образом чтобы его мог переиспользовать лексер.

2021-04-01 00:56 UTC, 6easy9 approved these changes
Похоже на правду.

2021-04-04 20:41 UTC, Victor-Y-Fadeev reviewed
- В препроцессоре не бывает типизации -> работы с вещественными числами
- Улучшите читаемость (сложно понять что делает код)

Не собирается под Visual Studio 16 2019:
```cmd
  environment.c
D:\RuC\libs\preprocessor\environment.c(133,19): error C2220: следующее предупреждение рассматривается как ошибка
D:\RuC\libs\preprocessor\environment.c(133,19): warning C4267: return: преобразование из "size_t" в "int"; возможна потеря данных
D:\RuC\libs\preprocessor\environment.c(141,40): warning C4267: =: преобразование из "size_t" в "int"; возможна потеря данных
  macro_load.c
D:\RuC\libs\preprocessor\macro_load.c(139,64): error C2220: следующее предупреждение рассматривается как ошибка
D:\RuC\libs\preprocessor\macro_load.c(139,64): warning C4267: =: преобразование из "size_t" в "int"; возможна потеря данных
D:\RuC\libs\preprocessor\macro_load.c(152,66): warning C4267: =: преобразование из "size_t" в "int"; возможна потеря данных
  macro_save.c
D:\RuC\libs\preprocessor\macro_save.c(59,1): error C2220: следующее предупреждение рассматривается как ошибка
D:\RuC\libs\preprocessor\macro_save.c(59,1): warning C4267: инициализация: преобразование из "size_t" в "const int"; возможна потеря данных
```
**Проверяйте это самостоятельно! И исправления по сборке оформляйте отдельным коммитом (важно).**

2021-04-04 20:41 UTC, Victor-Y-Fadeev commented on libs/preprocessor/calculator.c
> +int get_digit(universal_io *in, double *res, char32_t cur, char32_t next, char32_t *last)
Слишком много аргументов, в идеале бы только `io`, но можно и с `last` (для ускорения).

P.s. Можно откатить позицию перед вызовом.

2021-04-04 20:41 UTC, Victor-Y-Fadeev commented on libs/preprocessor/calculator.c
> +	int flag_too_long = 0;
Зачем? Если возникла ошибка, сразу выходите или выводите. Как вариант можно пропустить значащие символы.

2021-04-04 20:41 UTC, Victor-Y-Fadeev commented on libs/preprocessor/calculator.c
> +	int num_int = 0;
В `int64_t` поместится побольше, его и возвращайте.
Для ошибок используйте `LLONG_MAX`, `LLONG_MAX - 1`, `LLONG_MAX - 2` и т.д.
Не забывайте в таком случае и про документацию.

2021-04-04 20:41 UTC, Victor-Y-Fadeev commented on libs/preprocessor/calculator.c
> +	if (cur == '-')
Эту проверку можно объединить с проверкой корректности.

2021-04-04 20:41 UTC, Victor-Y-Fadeev commented on libs/preprocessor/calculator.c
> +			curchar = uni_scan_char(in);
Удалить, только целочисленные.

2021-04-04 20:41 UTC, Victor-Y-Fadeev commented on libs/preprocessor/calculator.c
> +	char32_t curchar = next;
Именование не по стайлгайду.

2021-04-04 20:41 UTC, Victor-Y-Fadeev commented on libs/preprocessor/calculator.c
> +			if ((next == cur && cur != '!') || (cur == '!' && next == '='))
Повторная проверка.

2021-04-04 20:41 UTC, Victor-Y-Fadeev commented on libs/preprocessor/calculator.c
> +		case '=':
Как насчет побитовых операций?

2021-04-04 20:41 UTC, Victor-Y-Fadeev commented on libs/preprocessor/calculator.c
> +			}
Что это?

2021-04-04 20:41 UTC, Victor-Y-Fadeev commented on libs/preprocessor/calculator.c
> +int get_prior(const char32_t operation)
Вот такой `prior`?

![Prior](https://static.wikia.nocookie.net/stargate/images/7/76/Prior.jpg/revision/latest/scale-to-width-down/720?cb=20070728222823)

**P.s. На сокращайте без надобности!**

2021-04-04 20:41 UTC, Victor-Y-Fadeev commented on libs/preprocessor/calculator.c
>  	{
Внутри вообще что-то странное... У вас все вперемешку и неправильные приоритеты. Как минимум операция отрицания должна иметь самый высокий приоритет из возможных.

2021-04-04 20:41 UTC, Victor-Y-Fadeev commented on libs/preprocessor/calculator.c
> +	switch (operation)
- Все вперемешку
- Нет побитовых операций
- `double` нельзя сравнивать через `==`
- Остаток от деления нельзя брать от вещественных

2021-04-04 20:41 UTC, Victor-Y-Fadeev commented on libs/preprocessor/calculator.c
> +void double_to_string(const double x, const int is_int, char *const arithmetic_res)
Удалить.

2021-04-04 20:41 UTC, Victor-Y-Fadeev commented on libs/preprocessor/calculator.c
>  int calc_digit(environment *const env, double *stack, int *is_int, int *stk_size)
Это невозможно читать, если так нужно постоянно передавать много переменных заведите локальную структуру.

2021-04-07 16:43 UTC, Egor-Anikin commented on libs/preprocessor/constants.h
> +#define DEPTH		10
Это относится к local_io, и реализовано более корректно в соответствующей, ветки.

2021-04-07 16:43 UTC, Egor-Anikin commented on libs/preprocessor/constants.h
> +#define FILE_TYPE			0
Это относится к local_io, и реализовано более корректно в соответствующей, ветки.

2021-04-07 16:43 UTC, Egor-Anikin commented on libs/preprocessor/constants.h
> +#define MACRO_DEF		1
Это относится к local_io, и реализовано более корректно в соответствующей, ветки.

2021-04-10 09:34 UTC, Egor-Anikin commented on libs/preprocessor/calculator.c
> +		case '=':
Побитовые операции и отрицание меня делать не просили, если нужно могу добавить.

2021-04-10 10:28 UTC, Egor-Anikin commented on libs/preprocessor/calculator.c
>  	{
Операция отрицания не предусмотрена, символ '!' отвечает за !=, приоритет операций правильный, проверено тестами.

2021-04-10 10:31 UTC, Egor-Anikin commented on libs/preprocessor/calculator.c
> +	switch (operation)
Не вижу смысла в разделении так как у арифметических и логических операций одинаковый принцип применения бинарной операции.

2021-06-14 09:19 UTC, Victor-Y-Fadeev commented
Закрыто в связи с введением новой архитектуры.

2021-06-14 09:19 UTC, closed without merging