Перестановка узлов выражений в дереве
andrey-terekhov/RuC pull request #99
Opened 2021-03-16 15:25 UTC by IvanArkhipov1999

2021-03-17 03:11 UTC, Victor-Y-Fadeev requested changes
Поставьте сразу после создания `workspace` в `main.c` (временно):
```c
ws_add_flag(&ws, "-LLVM");
```

У вас падают 3 теста по таймауту:
```bash
 compiling timeout : ../tests/executable/output/print/graphics/anikin.c
 compiling timeout : ../tests/executable/output/print/graphics/stasya.c
 compiling timeout : ../tests/executable/pointer/LA_9461.c
```

2021-03-17 03:11 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +			}
У вас 3 таких операции, тянет на отдельную функцию:
```c
static void transposition(node_info fst, node_info snd);
```

Также, стоит назвать временную ноду `temp` и цикл начать с `j = 1`, а не вычитать ее.

2021-03-17 03:11 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +			expr_node_info first_operand = expr_stack_pop(info);
Лучше использовать `fst` и `snd` в данном случае, легче будут читаться обращения к полям.
В крайнем случае просто `first` и `second`.

2021-03-17 03:11 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +			first_operand.node_num = first_operand.node_num + second_operand.node_num + 1;
```c
first_operand.node_num += second_operand.node_num + 1;
```

2021-03-17 03:44 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +			}
Кстати `operand.node_num++` тоже внутрь отправляется, и наверное переменные лучше назвать `parent`/`child` или `expr`/`cur`, где `parent`/`expr` - это `operand`. Что-то в духе:
```c
static void transposition(node_info expr, node_info cur)
{
	// перестановка с операндом
	node_order(expr.parent, expr.child, cur.parent, cur.child);
	node temp = node_get_child(expr.parent, expr.child);
	for (size_t i = 1; i < expr.depth; i++)
	{
		node_order(cur.parent, cur.child, &temp, 0);
		temp = node_get_child(&temp, 0);
	}

	// добавляем в стек переставленное выражение
	expr.depth += cur.depth;
}
```

2021-03-17 03:51 UTC, Victor-Y-Fadeev commented
Также думаю стоит перейти на указатели, вместо копирования структур (будет быстрее работать):
```c
static inline void stack_push(information *const info, node_info *const nd);
static inline node_info *stack_pop(information *const info);

static void transposition(node_info *const expr, node_info *const cur);
```

**P.s. Если так сделать, то внутри `for` вложенным станет уже не первый, а второй `switch`. Так как вам понадобится общая `node_info nd_info = { nd, i, 1 };`**

2021-03-22 14:39 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +			node_info.node_num = 1;
К сожалению, на такие чародейства travis на windows выдаёт предупреждение "warning C4204: nonstandard extension used: non-constant aggregate initializer".

2021-03-23 22:22 UTC, Victor-Y-Fadeev requested changes
Поскольку у вас теперь не должно быть timeout уберите из `.travis.yml`:
```diff
-  - ./scripts/test.sh -i -w 0.25
+  - ./scripts/test.sh -i
```

Также у вас разный вывод под разными ОС, это очень плохо и пока не исправите я не смогу принять. Такое обычно бывает при неаккуратной работе с памятью (пишите/читаете не оттуда).

```bash
# Windows
 success = 220, warning = 0, failure = 219, timeout = 0
# macOS
 success = 189, warning = 0, failure = 114, timeout = 136
# Ubuntu
 success = 189, warning = 0, failure = 250, timeout = 0
```

2021-03-23 22:22 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +			break;
- `break` надо сдвинуть вправо
- Возможно стоит добавить отступы до и после
- Комментарий лучше поставить после case, а не до

2021-03-23 22:22 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +					break;
Сдвинуть вправо.

2021-03-23 22:22 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						node_info* fst_operand = stack_pop(info);
- Про названия я уже говорил, возьмите `first` и `second` лучше
- Звездочки не с той стороны

2021-03-23 22:22 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +				nd_info.depth = 1;
Чтобы сработало:
```c
node_info nd_info = { nd, i, 1 };
```

Измените корневой `CMakeLists.txt`:
```diff
-	add_compile_options(/W4 /WX /wd5105 /utf-8
+	add_compile_options(/W4 /WX /wd4204 /wd5105 /utf-8
```

P.s. Это все равно устаревшее предупреждение и в MSVC 2019 его нет.

2021-03-23 22:22 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +	return &(info->stack[--info->stack_size]);
Где проверка на `info->stack_size == 0`? Возвращайте `NULL` в таком случае. Возможно из-за этого у вас проблемы с памятью...

И скобки тут не нужны.

2021-03-23 22:23 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						fst_operand->depth += snd_operand->depth + 1;
Это тоже лишнее.

2021-03-24 14:12 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +					break;
Без этого выдаётся предупреждение "warning: enumeration value ‘NOT_EXPRESSION’ not handled in switch".

2021-03-24 14:17 UTC, IvanArkhipov1999 commented on libs/compiler/llvmopt.c
> +						operand->depth++;
Комментарий про добавление в стек не относится к transposition, а комментарий про перестановку указывает больше на то, с кем переставляется, поэтому, мне кажется, ему место около вызова перестановки.

2021-03-25 10:00 UTC, Victor-Y-Fadeev reviewed
Стало сильно лучше, но проверки лучше сократить как я сказал, а то код станет сложно читать. Вы кстати выяснили почему выходите за нижнюю границу стека?

2021-03-25 10:00 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
>  {
Создайте здесь:
```c
	int has_error = 0;
```

И поставьте после нее отступ.

2021-03-25 10:00 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						}
Эти проверки вынесите в `transposition`.

2021-03-25 10:00 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						transposition(operand, &nd_info);
Здесь используйте:
```c
has_error |= transposition(operand, &nd_info);
```

2021-03-25 10:00 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						}
has_error |= stack_push(info, operand);

2021-03-25 10:00 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						}
Выкинуть.

2021-03-25 10:00 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +						}
По аналогии с предыдущими комментариями.

2021-03-25 10:00 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +		}
```c
if (has_error || node_recursive(info, &child))
{
	return has_error;
}
```

2021-03-25 10:00 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +}
- Сделайте ее `int`
- Поставьте отступы
- Добавьте проверку аргументов

```c
static void transposition(node_info *const expr, node_info *const cur)
{
	if (expr == NULL || cur == NULL)
	{
		return -1;
	}

	node_order(expr->parent, expr->child, cur->parent, cur->child);
	node temp = node_get_child(expr->parent, expr->child);
	for (size_t i = 1; i < expr->depth; i++)
	{
		node_order(cur->parent, cur->child, &temp, 0);
		temp = node_get_child(&temp, 0);
	}

	expr->depth += cur->depth;
	return 0;
}
```

2021-03-25 11:44 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +		if (node_recursive(&info, &child) == -1)
Не будет работать, вернее непредсказуемое поведение. Напишите:
```c
if (node_recursive(&info, &child))
```

2021-03-25 11:44 UTC, Victor-Y-Fadeev commented on libs/compiler/llvmopt.c
> +		return -1;
Сюда бы ошибку еще отпечатать... Что-то в духе:
```c
system_error(transposition_not_possible);
```

C сообщением `"Перестановка узлов невозможна"`. Добавьте в `errors.h` сразу после `tables_cannot_be_compressed`.

2021-03-25 12:06 UTC, Victor-Y-Fadeev approved these changes

2021-03-25 12:07 UTC, merged